//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ACTPinger.h"

@interface ACTPinger (Store)
+ (id)pingerWithRequestString:(id)arg1 retryParameters:(id)arg2;
- (id)requestString;
- (id)parameters;
@end

