//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "AiCommonConfig.h"

@class NSString;

@interface AIError : AiCommonConfig
{
    NSString *KEY_ERROR_ID;
    NSString *KEY_ERROR_DESCP;
    NSString *KEY_RECORD_ID;
}

- (void).cxx_destruct;
- (void)toErrorJson:(id)arg1 errorId:(unsigned long long)arg2 errorDescription:(id)arg3;
- (id)init;

@end

