//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface AIOpenUDID : NSObject
{
}

+ (void)setaiOptOut:(_Bool)arg1;
+ (id)aivalueWithError:(id *)arg1;
+ (id)aivalue;
+ (id)_generateFreshAIOpenUDID;
+ (id)_getDictFromPasteboard:(id)arg1;
+ (void)_setDict:(id)arg1 forPasteboard:(id)arg2;

@end

