//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "AiQEngineDelegate.h"

@class AiQEngine, BaseRequestParams, NSString;

@interface AiResEngine : NSObject <AiQEngineDelegate>
{
    AiQEngine *engine;
    BaseRequestParams *startParams;
    id <AiResEngineDelegate> delegate;
}

@property(nonatomic) id <AiResEngineDelegate> delegate; // @synthesize delegate;
- (void).cxx_destruct;
- (void)aiQEngine:(id)arg1 didReceive:(id)arg2 errorJson:(id)arg3;
- (void)aiQEngine:(id)arg1 didReceive:(id)arg2 responseBinary:(id)arg3;
- (void)aiQEngine:(id)arg1 didReceive:(id)arg2 responseJson:(id)arg3;
- (void)aiQEngine:(id)arg1 onInit:(id)arg2;
- (id)callError:(id)arg1 errorId:(unsigned long long)arg2 errorDescription:(id)arg3;
- (id)getInfo:(int)arg1;
- (void)releaseEngine;
- (int)cancel;
- (id)start:(id)arg1;
- (void)dealloc;
- (id)initWithDelegate:(id)arg1 Delegate:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

