//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "AiQEngineDelegate.h"
#import "IRecorderDelegate.h"

@class AiEngineConfig, AiQEngine, IRecorder, NSString, SpeechParams;

@interface AiSpeechEngine : NSObject <IRecorderDelegate, AiQEngineDelegate>
{
    IRecorder *recorder;
    AiQEngine *engine;
    AiEngineConfig *_engineCfg;
    SpeechParams *engineParams;
    _Bool configVadEnable;
    _Bool paramVadEnable;
    double recordStartTime;
    int noSpeechTimeout;
    int maxSpeechTimeout;
    NSString *recordId;
    int status;
    id <AiSpeechEngineDelegate> delegate;
}

@property(nonatomic) id <AiSpeechEngineDelegate> delegate; // @synthesize delegate;
- (void).cxx_destruct;
- (_Bool)isStopRecorder;
- (void)aiQEngine:(id)arg1 didReceive:(id)arg2 wakeUpJson:(id)arg3;
- (void)aiQEngine:(id)arg1 didReceive:(id)arg2 vadJson:(id)arg3;
- (void)aiQEngine:(id)arg1 didReceive:(id)arg2 errorJson:(id)arg3;
- (void)aiQEngine:(id)arg1 didReceive:(id)arg2 responseJson:(id)arg3;
- (void)aiQEngine:(id)arg1 onInit:(id)arg2;
- (void)IRecorderIsRecording:(id)arg1 passedTime:(double)arg2;
- (void)IRecorderDidFinishRecording:(id)arg1 stopType:(int)arg2;
- (void)IRecorderPerformRecording:(id)arg1 audioData:(const void *)arg2 size:(int)arg3;
- (id)callError:(id)arg1 errorId:(unsigned long long)arg2 errorDescription:(id)arg3;
- (id)getInfo:(int)arg1;
- (void)releaseEngine;
- (int)cancel;
- (int)stop;
- (int)startRecord;
- (id)start:(id)arg1;
- (void)dealloc;
- (id)initWithDelegate:(id)arg1 Delegate:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

