//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class AiSpeechEngine, NSData, NSNumber, NSString;

@protocol AiSpeechEngineDelegate <NSObject>

@optional
- (void)aiSpeechEngine:(AiSpeechEngine *)arg1 didReceive:(NSString *)arg2 wakeUpJson:(NSString *)arg3;
- (void)aiSpeechEngine:(AiSpeechEngine *)arg1 didReceive:(NSString *)arg2 volume:(NSNumber *)arg3;
- (void)aiSpeechEngine:(AiSpeechEngine *)arg1 didReceive:(NSString *)arg2 errorJson:(NSString *)arg3;
- (void)aiSpeechEngine:(AiSpeechEngine *)arg1 didReceive:(NSString *)arg2 responseJson:(NSString *)arg3;
- (void)aiSpeechEngine:(AiSpeechEngine *)arg1 didReceive:(NSString *)arg2 responseBinary:(NSData *)arg3;
- (void)aiSpeechEngineDidFinishRecording:(AiSpeechEngine *)arg1 stopType:(int)arg2;
- (void)aiSpeechEngine:(AiSpeechEngine *)arg1 onInit:(NSNumber *)arg2;
@end

