//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class AiTTSEngine, NSData, NSNumber, NSString;

@protocol AiTTSEngineDelegate <NSObject>

@optional
- (void)aiTTSPlayerContinue:(AiTTSEngine *)arg1;
- (void)aiTTSPlayerPause:(AiTTSEngine *)arg1;
- (void)aiTTSPlayerReady:(AiTTSEngine *)arg1;
- (void)aiTTSPlayerComplete:(AiTTSEngine *)arg1;
- (void)aiTTSEngine:(AiTTSEngine *)arg1 didReceive:(NSString *)arg2 errorJson:(NSString *)arg3;
- (void)aiTTSEngine:(AiTTSEngine *)arg1 didReceive:(NSString *)arg2 responseJson:(NSString *)arg3;
- (void)aiTTSEngine:(AiTTSEngine *)arg1 didReceive:(NSString *)arg2 responseBinary:(NSData *)arg3;
- (void)aiTTSEngine:(AiTTSEngine *)arg1 onInit:(NSNumber *)arg2;
@end

