//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "UIApplicationDelegate.h"
#import "WXApiDelegate.h"

@class BMKMapManager, CSNavController, NSString, UIWindow;

@interface AppDelegate : NSObject <UIApplicationDelegate, WXApiDelegate>
{
    _Bool _firstActiveTag;
    UIWindow *_window;
    CSNavController *_nav;
    BMKMapManager *_mapManager;
    unsigned long long _bgTaskId;
}

@property(nonatomic) unsigned long long bgTaskId; // @synthesize bgTaskId=_bgTaskId;
@property(nonatomic) _Bool firstActiveTag; // @synthesize firstActiveTag=_firstActiveTag;
@property(retain, nonatomic) BMKMapManager *mapManager; // @synthesize mapManager=_mapManager;
@property(retain, nonatomic) CSNavController *nav; // @synthesize nav=_nav;
@property(retain, nonatomic) UIWindow *window; // @synthesize window=_window;
- (void)onResp:(id)arg1;
- (unsigned long long)application:(id)arg1 supportedInterfaceOrientationsForWindow:(id)arg2;
- (void)saveAppIconBadge;
- (void)applicationDidReceiveMemoryWarning:(id)arg1;
- (void)application:(id)arg1 didReceiveRemoteNotification:(id)arg2;
- (void)application:(id)arg1 didRegisterUserNotificationSettings:(id)arg2;
- (void)application:(id)arg1 didFailToRegisterForRemoteNotificationsWithError:(id)arg2;
- (void)application:(id)arg1 didRegisterForRemoteNotificationsWithDeviceToken:(id)arg2;
- (_Bool)application:(id)arg1 openURL:(id)arg2 sourceApplication:(id)arg3 annotation:(id)arg4;
- (void)handleFinishBgTask;
- (void)stopFinishBgTaskTimer;
- (void)startFinishBgTaskTimer;
- (void)endBackgroundTask;
- (void)applicationDidEnterBackground:(id)arg1;
- (void)applicationWillEnterForeground:(id)arg1;
- (void)applicationWillResignActive:(id)arg1;
- (void)applicationDidBecomeActive:(id)arg1;
- (void)dealloc;
- (_Bool)application:(id)arg1 didFinishLaunchingWithOptions:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

