//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface ArcTempletData : NSObject
{
    _Bool _selTag;
    NSString *_str;
    long long _num;
    double _price;
}

@property(nonatomic) _Bool selTag; // @synthesize selTag=_selTag;
@property(nonatomic) double price; // @synthesize price=_price;
@property(nonatomic) long long num; // @synthesize num=_num;
@property(retain, nonatomic) NSString *str; // @synthesize str=_str;
- (void).cxx_destruct;
- (void)unitTest;
- (id)initWithObj:(id)arg1;

@end

