//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface AudioStreamAnalyzer : NSObject
{
    struct OpaqueAudioFileStreamID *streamID;
    CDStruct_e8964c13 propertyInfo;
    _Bool isStreamOpened;
    id delegate;
    SEL analysisPropertyDidFinished;
    SEL audioStreamDidReceivedData;
}

@property(nonatomic) SEL audioStreamDidReceivedData; // @synthesize audioStreamDidReceivedData;
@property(nonatomic) SEL analysisPropertyDidFinished; // @synthesize analysisPropertyDidFinished;
@property(readonly, nonatomic) _Bool isStreamOpened; // @synthesize isStreamOpened;
- (void).cxx_destruct;
- (CDStruct_e8964c13)get_AudioFilePropertyInfo;
- (void)doWithPacketData:(id)arg1 WithPacketCount:(unsigned int)arg2 WithPacketDesc:(struct AudioStreamPacketDescription *)arg3;
- (void)analysisProperty:(unsigned int)arg1;
- (void)printASBD:(struct AudioStreamBasicDescription)arg1;
- (_Bool)parseBytes:(id)arg1;
- (_Bool)closeStream;
- (_Bool)openStream;
- (unsigned int)fileTypeID:(id)arg1;
- (id)initWithDelegate:(id)arg1;

@end

