//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "AiCommonConfig.h"

@class AudioParams, CommonParams;

@interface BaseRequestParams : AiCommonConfig
{
    AudioParams *audioParams;
    CommonParams *commonParams;
}

- (void).cxx_destruct;
- (id)getDic;
- (id)getAudioSampleRate;
- (int)setAudioSampleRate:(id)arg1;
- (id)getAudioType;
- (int)setAudioType:(id)arg1;
- (id)getCompress;
- (int)setCompress:(id)arg1;
- (id)getAudioSpxQuality;
- (int)setAudioSpxQuality:(id)arg1;
- (id)getAppUserId;
- (int)setAppUserId:(id)arg1;
- (id)getVolumeEnable;
- (int)setVolumeEnable:(id)arg1;
- (id)getVadEnable;
- (int)setVadEnable:(id)arg1;
- (id)getReqRes;
- (int)setReqRes:(id)arg1;
- (id)getReqCoreType;
- (int)setReqCoreType:(id)arg1;
- (id)getType;
- (int)setType:(id)arg1;
- (id)init;

@end

