//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class BaseLayoutSupportVc, NSString;

@interface BaseView : UIView
{
    BaseLayoutSupportVc *_nrVc;
    NSString *_uniqueCellId1;
    NSString *_uniqueCellId2;
    NSString *_uniqueCellIdForLoading;
    NSString *_uniqueCellIdForSingleList;
}

@property(retain, nonatomic) NSString *uniqueCellIdForSingleList; // @synthesize uniqueCellIdForSingleList=_uniqueCellIdForSingleList;
@property(retain, nonatomic) NSString *uniqueCellIdForLoading; // @synthesize uniqueCellIdForLoading=_uniqueCellIdForLoading;
@property(retain, nonatomic) NSString *uniqueCellId2; // @synthesize uniqueCellId2=_uniqueCellId2;
@property(retain, nonatomic) NSString *uniqueCellId1; // @synthesize uniqueCellId1=_uniqueCellId1;
@property BaseLayoutSupportVc *nrVc; // @synthesize nrVc=_nrVc;
- (id)uniqueTableCellReuseIdentifierWithTag:(int)arg1;
- (id)uniqueTableCellReuseIdentifier;
- (void)onPageShowAfterWaiting:(id)arg1;
- (void)onPageShowAfterWaiting;
- (void)waitUntilPageShow:(id)arg1;
- (void)waitUntilPageShow;
- (void)alertView:(id)arg1 hideWithBtnIdx:(long long)arg2;
- (void)alertView:(id)arg1 didDismissWithButtonIndex:(long long)arg2;
- (void)confirmWithTitle:(id)arg1 msg:(id)arg2 okBtnName:(id)arg3 cancelBtnName:(id)arg4 dic:(id)arg5 tag:(int)arg6;
- (void)confirmWithTitle:(id)arg1 msg:(id)arg2 tag:(int)arg3;
- (void)confirmWithMsg:(id)arg1 okBtnName:(id)arg2 cancelBtnName:(id)arg3 tag:(int)arg4;
- (void)confirmWithMsg:(id)arg1 okBtnName:(id)arg2 tag:(int)arg3;
- (void)confirmWithMsg:(id)arg1 dic:(id)arg2 tag:(int)arg3;
- (void)confirmWithMsg:(id)arg1 tag:(int)arg2;
- (void)alertWithTitle:(id)arg1 msg:(id)arg2 tag:(int)arg3;
- (void)alert:(id)arg1 tag:(int)arg2;
- (void)alert:(id)arg1;
- (void)dealloc;
- (void)onInit;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)init;

@end

