//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BaseLayoutSupportVc.h"

#import "CSBvShareDelegate.h"
#import "CSBvcPhotoPickerDelegate.h"
#import "CSUIImageViewDelegate.h"
#import "UIActionSheetDelegate.h"
#import "UIScrollViewDelegate.h"

@class CSBvErrorReport, CSBvLargePhoto, CSBvPhoneCall, CSBvShare, CSBvcPhotoPicker, NSDate, NSString;

@interface BaseBizVc : BaseLayoutSupportVc <CSBvcPhotoPickerDelegate, UIActionSheetDelegate, CSUIImageViewDelegate, UIScrollViewDelegate, CSBvShareDelegate>
{
    _Bool _needProcessGpsMsgTag;
    _Bool _mainPageFirstChkCityTag;
    CSBvPhoneCall *_soPhoneCall;
    CSBvcPhotoPicker *_soBvcPhotoPicker;
    CSBvShare *_soBvShare;
    CSBvErrorReport *_soBvErrorReport;
    CSBvLargePhoto *_soBvLargePhoto;
    NSDate *_soLastOpenOrderDetailPageDate;
}

@property(nonatomic) _Bool mainPageFirstChkCityTag; // @synthesize mainPageFirstChkCityTag=_mainPageFirstChkCityTag;
@property(retain, nonatomic) NSDate *soLastOpenOrderDetailPageDate; // @synthesize soLastOpenOrderDetailPageDate=_soLastOpenOrderDetailPageDate;
@property(nonatomic) _Bool needProcessGpsMsgTag; // @synthesize needProcessGpsMsgTag=_needProcessGpsMsgTag;
@property(retain, nonatomic) CSBvLargePhoto *soBvLargePhoto; // @synthesize soBvLargePhoto=_soBvLargePhoto;
@property(retain, nonatomic) CSBvErrorReport *soBvErrorReport; // @synthesize soBvErrorReport=_soBvErrorReport;
@property(retain, nonatomic) CSBvShare *soBvShare; // @synthesize soBvShare=_soBvShare;
@property(retain, nonatomic) CSBvcPhotoPicker *soBvcPhotoPicker; // @synthesize soBvcPhotoPicker=_soBvcPhotoPicker;
@property(retain, nonatomic) CSBvPhoneCall *soPhoneCall; // @synthesize soPhoneCall=_soPhoneCall;
- (void)needShareForWapWithUuid:(id)arg1 showType:(id)arg2;
- (void)needShareForWapWithUuid:(id)arg1;
- (void)confirmToChangeCityWithCityDataForMainPage:(id)arg1 title:(id)arg2;
- (id)newHintForChangeCityWithCityData:(id)arg1 hintName:(id)arg2;
- (void)hintForChangeCityForMainPage;
- (_Bool)chkIsNeedProcessGpsCityMsgAndHideWaiting;
- (void)alertView:(id)arg1 didDismissWithButtonIndex:(long long)arg2;
- (_Bool)chkNeedResponsePushMsgOrSchemeUrl;
- (_Bool)chkIsAlipayParamsSchemeUrl:(id)arg1;
- (void)receivingMsgChatNeedProcessXmsUrlListener:(id)arg1;
- (void)receivingMsgForNeedOpenOrderNotifyListener:(id)arg1;
- (void)receivingMsgForAppSchemeLinkListener:(id)arg1;
- (void)receivingMsgHavePushMsgListener:(id)arg1;
- (void)receivingMsgCurrentGpsCityNotOpenListener:(id)arg1;
- (void)receivingMsgNotFindGpsListener:(id)arg1;
- (void)receivingMsgFindNewGpsCityListener:(id)arg1;
- (id)getOrCreateLargePhoto;
- (void)openLargePhotoWithUrl:(id)arg1 storeDir:(id)arg2 smallPhoto:(id)arg3;
- (void)openLargePhotoWithUrl:(id)arg1 smallPhoto:(id)arg2;
- (id)getOrCreateReport;
- (void)openReportSheetForFoodWithUuid:(id)arg1;
- (void)openReportSheetForRestWithUuid:(id)arg1 restInfoData:(id)arg2;
- (void)onBvShareCancel;
- (void)onBvShareSelectShareWithKey:(id)arg1;
- (id)getOrCreateShare;
- (void)openShareSheetForOthers:(id)arg1;
- (void)openShareSheetForOrderState:(id)arg1;
- (void)openShareSheetForWap:(id)arg1 showType:(id)arg2;
- (void)openShareSheetForTakeout:(id)arg1;
- (void)openShareSheetForRecom:(id)arg1;
- (void)openShareSheetForApp;
- (void)openShareSheetForRest:(id)arg1;
- (void)cancelPickPhoto:(long long)arg1;
- (void)cancelPickPhoto;
- (void)finishPickPhotoWithDataList:(id)arg1 tag:(long long)arg2;
- (void)finishPickPhotoWithDataList:(id)arg1;
- (void)onBvcPhotoPickerCanceled:(long long)arg1;
- (void)onBvcPhotoPickerFinished:(id)arg1 tag:(long long)arg2;
- (id)getOrCreatePhotoPicker;
- (void)confirmPickPhotoWithSelAlbum:(_Bool)arg1 selCamera:(_Bool)arg2 maxPickNum:(long long)arg3;
- (void)confirmPickPhoto:(long long)arg1 multiTag:(_Bool)arg2;
- (void)confirmMultiPickPhoto:(long long)arg1;
- (void)confirmPickPhoto:(long long)arg1;
- (void)confirmMultiPickPhotoWithMaxPickNum:(long long)arg1;
- (void)confirmMultiPickPhoto;
- (void)confirmPickPhoto;
- (id)getOrCreatePhoneCall;
- (void)callTelForCouopnPage:(id)arg1 couponId:(id)arg2;
- (void)callTelForTakeoutPage:(id)arg1 takeoutId:(id)arg2;
- (void)callTelForRestPage:(id)arg1 restId:(id)arg2;
- (void)callTelForMainPage:(id)arg1 restId:(id)arg2;
- (void)callTel:(id)arg1;
- (void)queryViewQueryKeywordYyBtnClicked:(id)arg1;
- (void)queryViewQueryKeywordBtnClicked:(id)arg1;
- (void)changeQueryKeywordHolderPlace:(id)arg1;
- (void)makeQueryKeywordViewForWhere:(_Bool)arg1;
- (void)makeQueryKeywordView;
- (void)makeQueryKeywordViewForCurrentPage;
- (void)_onCloseBegin;
- (void)_onCreateBegin;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

