//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray, NSString;

@interface BwcCommentData : NSObject
{
    NSString *_userName;
    NSString *_userPicUrl;
    long long _createTime;
    NSString *_detail;
    NSMutableArray *_picList;
}

@property(retain, nonatomic) NSMutableArray *picList; // @synthesize picList=_picList;
@property(retain, nonatomic) NSString *detail; // @synthesize detail=_detail;
@property long long createTime; // @synthesize createTime=_createTime;
@property(retain, nonatomic) NSString *userPicUrl; // @synthesize userPicUrl=_userPicUrl;
@property(retain, nonatomic) NSString *userName; // @synthesize userName=_userName;
- (void)transToList:(id)arg1;
- (void)dealloc;
- (id)initWithObj:(id)arg1;

@end

