//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray, NSString;

@interface BwcDetailData : NSObject
{
    _Bool _favTag;
    _Bool _needOrderTag;
    int _favNum;
    int _friendNum;
    NSString *_uuid;
    NSString *_picUrl;
    NSString *_name;
    double _overallNum;
    NSString *_priceHint;
    NSString *_oldPrice;
    NSString *_useHint;
    NSString *_restId;
    NSString *_restName;
    NSString *_restAvgPrice;
    NSString *_restDistrictName;
    NSString *_restDistance;
    NSMutableArray *_otherBwcList;
    NSMutableArray *_commentList;
}

@property(retain, nonatomic) NSMutableArray *commentList; // @synthesize commentList=_commentList;
@property(retain, nonatomic) NSMutableArray *otherBwcList; // @synthesize otherBwcList=_otherBwcList;
@property(retain, nonatomic) NSString *restDistance; // @synthesize restDistance=_restDistance;
@property(retain, nonatomic) NSString *restDistrictName; // @synthesize restDistrictName=_restDistrictName;
@property(retain, nonatomic) NSString *restAvgPrice; // @synthesize restAvgPrice=_restAvgPrice;
@property(retain, nonatomic) NSString *restName; // @synthesize restName=_restName;
@property(retain, nonatomic) NSString *restId; // @synthesize restId=_restId;
@property(nonatomic) _Bool needOrderTag; // @synthesize needOrderTag=_needOrderTag;
@property(retain, nonatomic) NSString *useHint; // @synthesize useHint=_useHint;
@property(nonatomic) _Bool favTag; // @synthesize favTag=_favTag;
@property(retain, nonatomic) NSString *oldPrice; // @synthesize oldPrice=_oldPrice;
@property(retain, nonatomic) NSString *priceHint; // @synthesize priceHint=_priceHint;
@property(nonatomic) int friendNum; // @synthesize friendNum=_friendNum;
@property(nonatomic) int favNum; // @synthesize favNum=_favNum;
@property(nonatomic) double overallNum; // @synthesize overallNum=_overallNum;
@property(retain, nonatomic) NSString *name; // @synthesize name=_name;
@property(retain, nonatomic) NSString *picUrl; // @synthesize picUrl=_picUrl;
@property(retain, nonatomic) NSString *uuid; // @synthesize uuid=_uuid;
- (void)unitTest;
- (void)transCommentToList:(id)arg1;
- (void)transBwcToList:(id)arg1;
- (void)dealloc;
- (id)initWithObj:(id)arg1;

@end

