//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDate, NSString;

@interface CacheFields : NSObject
{
    _Bool haveTag;
    NSString *dir;
    NSString *key;
    NSString *value;
    NSString *updateStamp;
    NSDate *saveTime;
    int expireMinute;
    _Bool expireTag;
    NSString *version;
    int readCount;
    _Bool needNewDataTag;
}

@property(nonatomic) _Bool needNewDataTag; // @synthesize needNewDataTag;
@property(nonatomic) int readCount; // @synthesize readCount;
@property(retain, nonatomic) NSString *version; // @synthesize version;
@property(nonatomic) _Bool expireTag; // @synthesize expireTag;
@property(nonatomic) int expireMinute; // @synthesize expireMinute;
@property(retain, nonatomic) NSDate *saveTime; // @synthesize saveTime;
@property(retain, nonatomic) NSString *updateStamp; // @synthesize updateStamp;
@property(retain, nonatomic) NSString *value; // @synthesize value;
@property(retain, nonatomic) NSString *key; // @synthesize key;
@property(retain, nonatomic) NSString *dir; // @synthesize dir;
@property(nonatomic) _Bool haveTag; // @synthesize haveTag;
- (void)dealloc;
- (id)init;

@end

