//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BaseDto.h"

@class NSMutableArray;

@interface CashCouponList2DTO : BaseDto
{
    NSMutableArray *_list;
    NSMutableArray *_regionList;
    NSMutableArray *_menuList;
    NSMutableArray *_sortTypeList;
    NSMutableArray *_advList;
}

@property(retain, nonatomic) NSMutableArray *advList; // @synthesize advList=_advList;
@property(retain, nonatomic) NSMutableArray *sortTypeList; // @synthesize sortTypeList=_sortTypeList;
@property(retain, nonatomic) NSMutableArray *menuList; // @synthesize menuList=_menuList;
@property(retain, nonatomic) NSMutableArray *regionList; // @synthesize regionList=_regionList;
@property(retain, nonatomic) NSMutableArray *list; // @synthesize list=_list;
- (void)unitTestAdvList;
- (void)unitTest;
- (void)appendData:(id)arg1;
- (void)dealloc;
- (id)initWithObj:(id)arg1;

@end

