//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface ChatMsgText : NSObject
{
    NSString *detail;
}

@property(retain, nonatomic) NSString *detail; // @synthesize detail;
- (void)dealloc;
- (id)jsonString;
- (id)initWithObj:(id)arg1;

@end

