//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface ChkUtil : NSObject
{
}

+ (_Bool)isDoubleStr:(id)arg1;
+ (_Bool)isIntegerStr:(id)arg1;
+ (_Bool)isIntStr:(id)arg1;
+ (_Bool)isEmptyStr:(id)arg1;
+ (_Bool)isExistNetwork;
+ (_Bool)chkStrExistIn:(id)arg1 str:(id)arg2;
+ (_Bool)chkIsIos7;
+ (_Bool)chkIsIphone5;
+ (_Bool)chkIsIpad;

@end

