//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray, NSString;

@interface CommentData : NSObject
{
    _Bool _gradeTag;
    _Bool _likeTag;
    int _replyNum;
    NSString *_uuid;
    NSString *_userName;
    NSString *_userSmallPicUrl;
    NSString *_userPicUrl;
    double _createTime;
    NSString *_noGradeIntro;
    double _overallNum;
    double _tasteNum;
    double _envNum;
    double _serviceNum;
    NSString *_detail;
    NSMutableArray *_picList;
    NSString *_clientName;
}

@property(retain, nonatomic) NSString *clientName; // @synthesize clientName=_clientName;
@property(nonatomic) int replyNum; // @synthesize replyNum=_replyNum;
@property(retain, nonatomic) NSMutableArray *picList; // @synthesize picList=_picList;
@property(retain, nonatomic) NSString *detail; // @synthesize detail=_detail;
@property(nonatomic) double serviceNum; // @synthesize serviceNum=_serviceNum;
@property(nonatomic) double envNum; // @synthesize envNum=_envNum;
@property(nonatomic) double tasteNum; // @synthesize tasteNum=_tasteNum;
@property(nonatomic) double overallNum; // @synthesize overallNum=_overallNum;
@property(nonatomic) _Bool likeTag; // @synthesize likeTag=_likeTag;
@property(retain, nonatomic) NSString *noGradeIntro; // @synthesize noGradeIntro=_noGradeIntro;
@property(nonatomic) _Bool gradeTag; // @synthesize gradeTag=_gradeTag;
@property(nonatomic) double createTime; // @synthesize createTime=_createTime;
@property(retain, nonatomic) NSString *userPicUrl; // @synthesize userPicUrl=_userPicUrl;
@property(retain, nonatomic) NSString *userSmallPicUrl; // @synthesize userSmallPicUrl=_userSmallPicUrl;
@property(retain, nonatomic) NSString *userName; // @synthesize userName=_userName;
@property(retain, nonatomic) NSString *uuid; // @synthesize uuid=_uuid;
- (void)unitTest;
- (void)dealloc;
- (id)initWithObj:(id)arg1;

@end

