//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray, NSString;

@interface CommonSelectGroupData : NSObject
{
    NSString *_key;
    NSMutableArray *_list;
}

@property(retain, nonatomic) NSMutableArray *list; // @synthesize list=_list;
@property(retain, nonatomic) NSString *key; // @synthesize key=_key;
- (void)dealloc;
- (id)initWithKey:(id)arg1 list:(id)arg2;

@end

