//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray, NSString;

@interface CommonSelectListData : NSObject
{
    _Bool _canSelectTag;
    _Bool _groupTag;
    NSString *_selectId;
    NSString *_selectName;
    NSMutableArray *_list;
    NSMutableArray *_groupIndexList;
}

@property(retain, nonatomic) NSMutableArray *groupIndexList; // @synthesize groupIndexList=_groupIndexList;
@property(retain, nonatomic) NSMutableArray *list; // @synthesize list=_list;
@property(nonatomic) _Bool groupTag; // @synthesize groupTag=_groupTag;
@property(nonatomic) _Bool canSelectTag; // @synthesize canSelectTag=_canSelectTag;
@property(retain, nonatomic) NSString *selectName; // @synthesize selectName=_selectName;
@property(retain, nonatomic) NSString *selectId; // @synthesize selectId=_selectId;
- (void)dealloc;
- (id)initWithSelectId:(id)arg1 selectName:(id)arg2 list:(id)arg3 groupTag:(_Bool)arg4;
- (id)initWithSelectId:(id)arg1 selectName:(id)arg2 groupList:(id)arg3;
- (id)initWithSelectId:(id)arg1 selectName:(id)arg2 list:(id)arg3;
- (id)initWithSelectId:(id)arg1 selectName:(id)arg2;

@end

