//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface CommonTypeDto : NSObject
{
    NSString *uuid;
    NSString *parentId;
    NSString *name;
    int num;
    _Bool succTag;
    NSString *phone;
    _Bool selectTag;
    NSString *firstLetter;
    NSString *memo;
}

@property(retain, nonatomic) NSString *memo; // @synthesize memo;
@property(retain, nonatomic) NSString *firstLetter; // @synthesize firstLetter;
@property(nonatomic) _Bool selectTag; // @synthesize selectTag;
@property(retain, nonatomic) NSString *phone; // @synthesize phone;
@property(nonatomic) _Bool succTag; // @synthesize succTag;
@property(nonatomic) int num; // @synthesize num;
@property(retain, nonatomic) NSString *name; // @synthesize name;
@property(retain, nonatomic) NSString *parentId; // @synthesize parentId;
@property(retain, nonatomic) NSString *uuid; // @synthesize uuid;
- (id)newDic;
- (id)newOne;
- (void)dealloc;
- (id)initWithObj:(id)arg1;

@end

