//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface CommonPostPayResultData : NSObject
{
    _Bool _chkPassTag;
    NSString *_unionPayXml;
    NSString *_aliPayInfo;
    NSString *_wapAliPayUrl;
    NSString *_wapAliPayCreditCardUrl;
    NSString *_weixinInfo;
    NSString *_kqInfo;
    NSString *_wapUrl;
    NSString *_errorHint;
    NSString *_orderId;
}

@property(retain, nonatomic) NSString *orderId; // @synthesize orderId=_orderId;
@property(retain, nonatomic) NSString *errorHint; // @synthesize errorHint=_errorHint;
@property(nonatomic) _Bool chkPassTag; // @synthesize chkPassTag=_chkPassTag;
@property(retain, nonatomic) NSString *wapUrl; // @synthesize wapUrl=_wapUrl;
@property(retain, nonatomic) NSString *kqInfo; // @synthesize kqInfo=_kqInfo;
@property(retain, nonatomic) NSString *weixinInfo; // @synthesize weixinInfo=_weixinInfo;
@property(retain, nonatomic) NSString *wapAliPayCreditCardUrl; // @synthesize wapAliPayCreditCardUrl=_wapAliPayCreditCardUrl;
@property(retain, nonatomic) NSString *wapAliPayUrl; // @synthesize wapAliPayUrl=_wapAliPayUrl;
@property(retain, nonatomic) NSString *aliPayInfo; // @synthesize aliPayInfo=_aliPayInfo;
@property(retain, nonatomic) NSString *unionPayXml; // @synthesize unionPayXml=_unionPayXml;
- (void)unitTest;
- (void)dealloc;
- (id)initWithObj:(id)arg1;

@end

