//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray, NSString;

@interface CouponRestData : NSObject
{
    NSString *_restId;
    NSString *_restName;
    NSString *_restAddress;
    NSString *_distanceMeter;
    NSMutableArray *_telList;
}

@property(retain, nonatomic) NSMutableArray *telList; // @synthesize telList=_telList;
@property(retain, nonatomic) NSString *distanceMeter; // @synthesize distanceMeter=_distanceMeter;
@property(retain, nonatomic) NSString *restAddress; // @synthesize restAddress=_restAddress;
@property(retain, nonatomic) NSString *restName; // @synthesize restName=_restName;
@property(retain, nonatomic) NSString *restId; // @synthesize restId=_restId;
- (void)unitTest;
- (void)dealloc;
- (id)initWithObj:(id)arg1;

@end

