//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class BaseVc, CSUIPlaceHolderTextView, NSData, NSObject<CSAddRRPicPanelDelegate>, UIButton, UIImageView, UILabel;

@interface CSAddRRPicPanel : UIView
{
    _Bool _isHidingTag;
    _Bool _isCheckedAsCover;
    _Bool _isPicLoaded;
    BaseVc *_nrVc;
    NSObject<CSAddRRPicPanelDelegate> *_delegate;
    UIView *_ctrlFrame;
    UIButton *_ctrlCloseBtn;
    UIButton *_ctrlImageFrameBg;
    UIImageView *_ctrlImageShown;
    NSData *_imgData;
    UIImageView *_ctrlTextViewBg;
    CSUIPlaceHolderTextView *_ctrlTextView;
    UIButton *_ctrlCheckAsCoverBtn;
    UILabel *_ctrlCheckAsCoverLbl;
}

@property(nonatomic) _Bool isPicLoaded; // @synthesize isPicLoaded=_isPicLoaded;
@property(nonatomic) _Bool isCheckedAsCover; // @synthesize isCheckedAsCover=_isCheckedAsCover;
@property(nonatomic) _Bool isHidingTag; // @synthesize isHidingTag=_isHidingTag;
@property(retain, nonatomic) UILabel *ctrlCheckAsCoverLbl; // @synthesize ctrlCheckAsCoverLbl=_ctrlCheckAsCoverLbl;
@property(retain, nonatomic) UIButton *ctrlCheckAsCoverBtn; // @synthesize ctrlCheckAsCoverBtn=_ctrlCheckAsCoverBtn;
@property(retain, nonatomic) CSUIPlaceHolderTextView *ctrlTextView; // @synthesize ctrlTextView=_ctrlTextView;
@property(retain, nonatomic) UIImageView *ctrlTextViewBg; // @synthesize ctrlTextViewBg=_ctrlTextViewBg;
@property(retain, nonatomic) NSData *imgData; // @synthesize imgData=_imgData;
@property(retain, nonatomic) UIImageView *ctrlImageShown; // @synthesize ctrlImageShown=_ctrlImageShown;
@property(retain, nonatomic) UIButton *ctrlImageFrameBg; // @synthesize ctrlImageFrameBg=_ctrlImageFrameBg;
@property(retain, nonatomic) UIButton *ctrlCloseBtn; // @synthesize ctrlCloseBtn=_ctrlCloseBtn;
@property(retain, nonatomic) UIView *ctrlFrame; // @synthesize ctrlFrame=_ctrlFrame;
@property NSObject<CSAddRRPicPanelDelegate> *delegate; // @synthesize delegate=_delegate;
@property BaseVc *nrVc; // @synthesize nrVc=_nrVc;
- (void)updateCheckAsCoverBtnSelection:(_Bool)arg1;
- (void)selectPicBtnClicked:(id)arg1;
- (void)checkAsCoverBtnClicked:(id)arg1;
- (void)closeBtnClicked:(id)arg1;
- (void)reloadPicData:(id)arg1;
- (void)checkAsCoverOn;
- (void)checkAsCoverOff;
- (void)refreshDetailHint:(id)arg1 andCoverHint:(id)arg2;
- (void)reset;
- (void)refresh;
- (void)dealloc;
- (id)initWithVc:(id)arg1;

@end

