//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class BaseBizVc, NSObject<CSAdWebWaitPanelDelegate>, UIActivityIndicatorView;

@interface CSAdWebWaitPanel : UIView
{
    NSObject<CSAdWebWaitPanelDelegate> *_delegate;
    BaseBizVc *_nrVc;
    UIActivityIndicatorView *_ctrlIndicator;
}

@property(retain, nonatomic) UIActivityIndicatorView *ctrlIndicator; // @synthesize ctrlIndicator=_ctrlIndicator;
@property BaseBizVc *nrVc; // @synthesize nrVc=_nrVc;
@property NSObject<CSAdWebWaitPanelDelegate> *delegate; // @synthesize delegate=_delegate;
- (void)hide;
- (void)show;
- (void)dealloc;
- (id)initWithVc:(id)arg1;

@end

