//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BaseHttpView.h"

#import "UITextFieldDelegate.h"

@class CSZyInput, NSString, UILabel;

@interface CSAddDebugUserPanel : BaseHttpView <UITextFieldDelegate>
{
    UILabel *_ctrlDebugTitle;
    CSZyInput *_ctrlTfName;
    CSZyInput *_ctrlTfPwd;
}

@property(retain, nonatomic) CSZyInput *ctrlTfPwd; // @synthesize ctrlTfPwd=_ctrlTfPwd;
@property(retain, nonatomic) CSZyInput *ctrlTfName; // @synthesize ctrlTfName=_ctrlTfName;
@property(retain, nonatomic) UILabel *ctrlDebugTitle; // @synthesize ctrlDebugTitle=_ctrlDebugTitle;
- (_Bool)textFieldShouldReturn:(id)arg1;
- (void)debugAuthOkBtnClick;
- (void)debugAuthCancelBtnClick;
- (void)hideKeyboard;
- (void)onHttpRequestFail:(long long)arg1 errorMsg:(id)arg2;
- (void)onHttpRequestSuccess:(id)arg1 tag:(long long)arg2;
- (void)toAddTestAccountWithDebugName:(id)arg1 debugPwd:(id)arg2;
- (void)close;
- (void)open;
- (void)dealloc;
- (id)initWithVc:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

