//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class BaseBizVc, NSObject<CSArcTempletPanelDelegate>, UILabel;

@interface CSArcTempletPanel : UIView
{
    _Bool _isHidingTag;
    NSObject<CSArcTempletPanelDelegate> *_delegate;
    BaseBizVc *_nrVc;
    UILabel *_ctrlTitleLabel;
}

@property(nonatomic) _Bool isHidingTag; // @synthesize isHidingTag=_isHidingTag;
@property(retain, nonatomic) UILabel *ctrlTitleLabel; // @synthesize ctrlTitleLabel=_ctrlTitleLabel;
@property(nonatomic) __weak BaseBizVc *nrVc; // @synthesize nrVc=_nrVc;
@property(nonatomic) __weak NSObject<CSArcTempletPanelDelegate> *delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)finishHideAnimation;
- (void)handleHidePanel;
- (void)open;
- (void)dealloc;
- (id)initWithVc:(id)arg1;

@end

