//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class BaseVc, CSbubble, NSMutableArray, NSObject<CSBpMorePanelDelegate>, UIButton, UIImageView;

@interface CSBpMorePanel : NSObject
{
    NSObject<CSBpMorePanelDelegate> *_delegate;
    BaseVc *_nrVc;
    UIButton *_ctrlMask;
    UIImageView *_ctrlBtnPanel;
    CSbubble *_ctrlOrderBubble;
    NSMutableArray *_btnList;
}

@property(retain, nonatomic) NSMutableArray *btnList; // @synthesize btnList=_btnList;
@property(retain, nonatomic) CSbubble *ctrlOrderBubble; // @synthesize ctrlOrderBubble=_ctrlOrderBubble;
@property(retain, nonatomic) UIImageView *ctrlBtnPanel; // @synthesize ctrlBtnPanel=_ctrlBtnPanel;
@property(retain, nonatomic) UIButton *ctrlMask; // @synthesize ctrlMask=_ctrlMask;
@property BaseVc *nrVc; // @synthesize nrVc=_nrVc;
@property NSObject<CSBpMorePanelDelegate> *delegate; // @synthesize delegate=_delegate;
- (void)btnClicked:(id)arg1;
- (void)bgBtnClicked;
- (void)createPanels;
- (void)open;
- (void)dealloc;
- (id)initWithVc:(id)arg1;

@end

