//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class BaseVc, NSObject<CSBvcWaitDelegate>, UIActivityIndicatorView, UILabel, UIView;

@interface CSBvcWait : NSObject
{
    _Bool _haveAnimeTag;
    NSObject<CSBvcWaitDelegate> *_delegate;
    BaseVc *_nrVc;
    UIView *_ctrlIndicator;
    UIActivityIndicatorView *_ctrlAi;
    UILabel *_ctrlLabel;
    UIView *_ctrlMask;
    UIView *_ctrlTopRightMask;
}

@property(nonatomic) _Bool haveAnimeTag; // @synthesize haveAnimeTag=_haveAnimeTag;
@property(retain, nonatomic) UIView *ctrlTopRightMask; // @synthesize ctrlTopRightMask=_ctrlTopRightMask;
@property(retain, nonatomic) UIView *ctrlMask; // @synthesize ctrlMask=_ctrlMask;
@property(retain, nonatomic) UILabel *ctrlLabel; // @synthesize ctrlLabel=_ctrlLabel;
@property(retain, nonatomic) UIActivityIndicatorView *ctrlAi; // @synthesize ctrlAi=_ctrlAi;
@property(retain, nonatomic) UIView *ctrlIndicator; // @synthesize ctrlIndicator=_ctrlIndicator;
@property BaseVc *nrVc; // @synthesize nrVc=_nrVc;
@property NSObject<CSBvcWaitDelegate> *delegate; // @synthesize delegate=_delegate;
- (void)hideWaitingWithDoEnd:(_Bool)arg1;
- (void)showWaitingAnimationDidStop:(id)arg1 finished:(_Bool)arg2 context:(void *)arg3;
- (void)handleShowWaitingAnimationsTimer:(id)arg1;
- (void)showWaitingWithTitle:(id)arg1 doEnd:(_Bool)arg2;
- (void)hideMask;
- (void)showMask:(_Bool)arg1;
- (void)dealloc;
- (id)initWithVc:(id)arg1;

@end

