//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "UIActionSheetDelegate.h"

@class BaseLayoutSupportVc, NSObject<CSBvShareDelegate>, NSString, RestInfoData, RestRecomInfoData, ShareInfoData, TakeoutInfoData2;

@interface CSBvShare : NSObject <UIActionSheetDelegate>
{
    int _typeTag;
    NSObject<CSBvShareDelegate> *_delegate;
    BaseLayoutSupportVc *_nrVc;
    NSString *_uuid;
    RestInfoData *_restInfoData;
    RestRecomInfoData *_restRecomInfoData;
    TakeoutInfoData2 *_takeoutInfoData;
    ShareInfoData *_shareInfoData;
    NSString *_showType;
}

@property(retain, nonatomic) NSString *showType; // @synthesize showType=_showType;
@property(retain, nonatomic) ShareInfoData *shareInfoData; // @synthesize shareInfoData=_shareInfoData;
@property(retain, nonatomic) TakeoutInfoData2 *takeoutInfoData; // @synthesize takeoutInfoData=_takeoutInfoData;
@property(retain, nonatomic) RestRecomInfoData *restRecomInfoData; // @synthesize restRecomInfoData=_restRecomInfoData;
@property(retain, nonatomic) RestInfoData *restInfoData; // @synthesize restInfoData=_restInfoData;
@property(retain, nonatomic) NSString *uuid; // @synthesize uuid=_uuid;
@property int typeTag; // @synthesize typeTag=_typeTag;
@property BaseLayoutSupportVc *nrVc; // @synthesize nrVc=_nrVc;
@property NSObject<CSBvShareDelegate> *delegate; // @synthesize delegate=_delegate;
- (void)toShareToWeixinPage:(_Bool)arg1;
- (void)toShareToWbPage;
- (void)toEmailPage;
- (void)toSmsPage;
- (void)okShare:(id)arg1;
- (void)cancelShare;
- (void)actionSheet:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)openWithTypeTag:(int)arg1 uuid:(id)arg2;
- (void)openForOthers:(id)arg1;
- (void)openForOrderState:(id)arg1;
- (void)openForWap:(id)arg1 showType:(id)arg2;
- (void)openForTakeout:(id)arg1;
- (void)openForRecom:(id)arg1;
- (void)openForApp;
- (void)openForRest:(id)arg1;
- (void)dealloc;
- (id)initWithVc:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

