//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class BaseVc, NSObject<CSBvcGuideViewDelegate>, UIImageView;

@interface CSBvcGuideView : UIView
{
    NSObject<CSBvcGuideViewDelegate> *_delegate;
    BaseVc *_nrVc;
    UIImageView *_ctrlImg;
}

@property(retain, nonatomic) UIImageView *ctrlImg; // @synthesize ctrlImg=_ctrlImg;
@property BaseVc *nrVc; // @synthesize nrVc=_nrVc;
@property NSObject<CSBvcGuideViewDelegate> *delegate; // @synthesize delegate=_delegate;
- (void)btnClicked;
- (void)createGuideView;
- (void)toShowGuide:(id)arg1;
- (void)showGuide:(id)arg1 needCache:(_Bool)arg2;
- (void)dealloc;
- (id)initWithVc:(id)arg1;

@end

