//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class BaseBizVc, CSUIButton, CSZyShareButtonSet, NSObject<CSCaBtnPanelDelegate>, UILabel;

@interface CSCaBtnPanel : UIView
{
    NSObject<CSCaBtnPanelDelegate> *_delegate;
    BaseBizVc *_nrVc;
    UILabel *_ctrlTitleLabel;
    CSZyShareButtonSet *_ctrlShare;
    CSUIButton *_ctrlBtn;
}

@property(retain, nonatomic) CSUIButton *ctrlBtn; // @synthesize ctrlBtn=_ctrlBtn;
@property(retain, nonatomic) CSZyShareButtonSet *ctrlShare; // @synthesize ctrlShare=_ctrlShare;
@property(retain, nonatomic) UILabel *ctrlTitleLabel; // @synthesize ctrlTitleLabel=_ctrlTitleLabel;
@property BaseBizVc *nrVc; // @synthesize nrVc=_nrVc;
@property NSObject<CSCaBtnPanelDelegate> *delegate; // @synthesize delegate=_delegate;
- (void)submitBtnClicked;
- (void)refresh:(id)arg1;
- (void)reset;
- (void)dealloc;
- (id)initWithVc:(id)arg1;

@end

