//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class BaseBizVc, CSDecoratedLabel, CSHtmLabel, CouponInfoData, NSObject<CSCDPricePanelDelegate>, UIButton, UILabel;

@interface CSCDPricePanel : UIView
{
    NSObject<CSCDPricePanelDelegate> *_delegate;
    BaseBizVc *_nrVc;
    UILabel *_ctrlNowPriceLabel;
    CSDecoratedLabel *_ctrlOldPriceLabel;
    CSHtmLabel *_ctrlLabel;
    UIButton *_ctrlBtn;
    CouponInfoData *_dto;
}

+ (float)panelHeight;
@property(retain, nonatomic) CouponInfoData *dto; // @synthesize dto=_dto;
@property(retain, nonatomic) UIButton *ctrlBtn; // @synthesize ctrlBtn=_ctrlBtn;
@property(retain, nonatomic) CSHtmLabel *ctrlLabel; // @synthesize ctrlLabel=_ctrlLabel;
@property(retain, nonatomic) CSDecoratedLabel *ctrlOldPriceLabel; // @synthesize ctrlOldPriceLabel=_ctrlOldPriceLabel;
@property(retain, nonatomic) UILabel *ctrlNowPriceLabel; // @synthesize ctrlNowPriceLabel=_ctrlNowPriceLabel;
@property BaseBizVc *nrVc; // @synthesize nrVc=_nrVc;
@property NSObject<CSCDPricePanelDelegate> *delegate; // @synthesize delegate=_delegate;
- (void)btnClick:(id)arg1;
- (void)reset;
- (void)refreshPanel:(id)arg1;
- (void)dealloc;
- (id)initWithVc:(id)arg1;

@end

