//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "ASIProgressDelegate.h"

@class ASINetworkQueue, BaseVc, NSObject<CSDownBookPanelDelegate>, NSString;

@interface CSChatDownZipPanel : UIView <ASIProgressDelegate>
{
    NSObject<CSDownBookPanelDelegate> *_delegate;
    BaseVc *_nrVc;
    ASINetworkQueue *_ctrlNq;
    NSString *_chatVer;
}

@property(retain, nonatomic) NSString *chatVer; // @synthesize chatVer=_chatVer;
@property(retain, nonatomic) ASINetworkQueue *ctrlNq; // @synthesize ctrlNq=_ctrlNq;
@property BaseVc *nrVc; // @synthesize nrVc=_nrVc;
@property NSObject<CSDownBookPanelDelegate> *delegate; // @synthesize delegate=_delegate;
- (void)requestFailed:(id)arg1;
- (void)requestFinished:(id)arg1;
- (void)downWithZipUrl:(id)arg1 ver:(id)arg2;
- (void)dealloc;
- (id)initWithVc:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

