//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class CSUIButton;

@interface CSCommentBottomView : UIView
{
    CSUIButton *_ctrlBtnReply;
    CSUIButton *_ctrlBtnFromSource;
}

@property(retain, nonatomic) CSUIButton *ctrlBtnFromSource; // @synthesize ctrlBtnFromSource=_ctrlBtnFromSource;
@property(retain, nonatomic) CSUIButton *ctrlBtnReply; // @synthesize ctrlBtnReply=_ctrlBtnReply;
- (void)setCommentData:(id)arg1;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

@end

