//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "UIScrollViewDelegate.h"

@class BaseBizVc, NSObject<CSDishPeoplePanelDelegate>, NSString, UIImageView, UILabel, UIScrollView;

@interface CSDishPeoplePanel : UIView <UIScrollViewDelegate>
{
    _Bool _haveShiJiaTag;
    NSObject<CSDishPeoplePanelDelegate> *_delegate;
    BaseBizVc *_nrVc;
    UIView *_ctrlNumPanel;
    UILabel *_ctrlCuNumLabel;
    UIImageView *_ctrlTotalIcon;
    UILabel *_ctrlTotalLabel;
    UIScrollView *_ctrlSv;
    double _totalMoney;
}

@property(nonatomic) _Bool haveShiJiaTag; // @synthesize haveShiJiaTag=_haveShiJiaTag;
@property(nonatomic) double totalMoney; // @synthesize totalMoney=_totalMoney;
@property(retain, nonatomic) UIScrollView *ctrlSv; // @synthesize ctrlSv=_ctrlSv;
@property(retain, nonatomic) UILabel *ctrlTotalLabel; // @synthesize ctrlTotalLabel=_ctrlTotalLabel;
@property(retain, nonatomic) UIImageView *ctrlTotalIcon; // @synthesize ctrlTotalIcon=_ctrlTotalIcon;
@property(retain, nonatomic) UILabel *ctrlCuNumLabel; // @synthesize ctrlCuNumLabel=_ctrlCuNumLabel;
@property(retain, nonatomic) UIView *ctrlNumPanel; // @synthesize ctrlNumPanel=_ctrlNumPanel;
@property(nonatomic) __weak BaseBizVc *nrVc; // @synthesize nrVc=_nrVc;
@property(nonatomic) __weak NSObject<CSDishPeoplePanelDelegate> *delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)createIcons;
- (void)updateCurNum:(_Bool)arg1;
- (long long)curPage;
- (struct CGPoint)nearestTargetOffsetForOffset:(struct CGPoint)arg1;
- (void)snapToNearestItem;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(_Bool)arg2;
- (void)scrollViewDidScroll:(id)arg1;
- (void)refresh;
- (void)dealloc;
- (id)initWithVc:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

