//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface CSDragItem : NSObject
{
    long long tag;
    NSString *imageURL;
    double x;
    double y;
}

@property(nonatomic) double y; // @synthesize y;
@property(nonatomic) double x; // @synthesize x;
@property(retain, nonatomic) NSString *imageURL; // @synthesize imageURL;
@property(nonatomic) long long tag; // @synthesize tag;
- (id)newDictionary;
- (id)initWithObj:(id)arg1;
- (id)initWithTag:(int)arg1 andImageURL:(id)arg2;

@end

