//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@protocol CSHotDistrictCellDelegate <NSObject>
- (void)onCSHotDistrictCellSelOnMore:(int)arg1;
- (void)onCSHotDistrictCellSelOnCellType:(int)arg1 uuid:(NSString *)arg2 withParentId:(NSString *)arg3 andName:(NSString *)arg4;
@end

