//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class BaseVc, CSUIImageView, NSObject<CSMainJhCellDelegate>, UILabel;

@interface CSMainJhCell : UIView
{
    NSObject<CSMainJhCellDelegate> *_delegate;
    BaseVc *_nrVc;
    CSUIImageView *_ctrlImg;
    UILabel *_ctrlRestNameLabel;
    UILabel *_ctrlTitleLabel;
    UILabel *_ctrlHitLabel;
    UILabel *_ctrlFavLabel;
    UILabel *_ctrlDistrictLabel;
    CSUIImageView *_ctrlCouponIcon;
}

+ (int)panelHeight;
@property(retain, nonatomic) CSUIImageView *ctrlCouponIcon; // @synthesize ctrlCouponIcon=_ctrlCouponIcon;
@property(retain, nonatomic) UILabel *ctrlDistrictLabel; // @synthesize ctrlDistrictLabel=_ctrlDistrictLabel;
@property(retain, nonatomic) UILabel *ctrlFavLabel; // @synthesize ctrlFavLabel=_ctrlFavLabel;
@property(retain, nonatomic) UILabel *ctrlHitLabel; // @synthesize ctrlHitLabel=_ctrlHitLabel;
@property(retain, nonatomic) UILabel *ctrlTitleLabel; // @synthesize ctrlTitleLabel=_ctrlTitleLabel;
@property(retain, nonatomic) UILabel *ctrlRestNameLabel; // @synthesize ctrlRestNameLabel=_ctrlRestNameLabel;
@property(retain, nonatomic) CSUIImageView *ctrlImg; // @synthesize ctrlImg=_ctrlImg;
@property BaseVc *nrVc; // @synthesize nrVc=_nrVc;
@property NSObject<CSMainJhCellDelegate> *delegate; // @synthesize delegate=_delegate;
- (void)refresh:(id)arg1;
- (void)dealloc;
- (id)initWithVc:(id)arg1;

@end

