//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class BaseVc, MdbRestInfoData, NSObject<CSMdbRdDingPanelDelegate>, UIButton;

@interface CSMdbRdDingPanel : UIView
{
    NSObject<CSMdbRdDingPanelDelegate> *_delegate;
    BaseVc *_nrVc;
    UIButton *_ctrlBtn;
    MdbRestInfoData *_dto;
}

@property(retain, nonatomic) MdbRestInfoData *dto; // @synthesize dto=_dto;
@property(retain, nonatomic) UIButton *ctrlBtn; // @synthesize ctrlBtn=_ctrlBtn;
@property BaseVc *nrVc; // @synthesize nrVc=_nrVc;
@property NSObject<CSMdbRdDingPanelDelegate> *delegate; // @synthesize delegate=_delegate;
- (void)btnClicked;
- (void)refreshPanel:(id)arg1;
- (void)dealloc;
- (id)initWithVc:(id)arg1 top:(int)arg2;

@end

