//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class BaseBizVc, CSHtmLabel, CSMdbFlower, CSUIImageView, NSObject<CSMdbRlCellDelegate>, UIImageView, UILabel;

@interface CSMdbRlCell : UIView
{
    NSObject<CSMdbRlCellDelegate> *_delegate;
    BaseBizVc *_nrVc;
    UIView *_ctrlBg;
    CSUIImageView *_ctrlImg;
    UILabel *_ctrlRestName;
    UIImageView *_ctrlLocIcon;
    UILabel *_ctrlDistance;
    UILabel *_ctrlReason;
    UILabel *_ctrlAvg;
    CSMdbFlower *_ctrlFlower;
    CSHtmLabel *_ctrlFreeNum;
    UIImageView *_ctrlFreePctIcon;
    UILabel *_ctrlFreePct;
}

+ (float)panelMaxHeight;
+ (float)panelDefaultHeight;
@property(retain, nonatomic) UILabel *ctrlFreePct; // @synthesize ctrlFreePct=_ctrlFreePct;
@property(retain, nonatomic) UIImageView *ctrlFreePctIcon; // @synthesize ctrlFreePctIcon=_ctrlFreePctIcon;
@property(retain, nonatomic) CSHtmLabel *ctrlFreeNum; // @synthesize ctrlFreeNum=_ctrlFreeNum;
@property(retain, nonatomic) CSMdbFlower *ctrlFlower; // @synthesize ctrlFlower=_ctrlFlower;
@property(retain, nonatomic) UILabel *ctrlAvg; // @synthesize ctrlAvg=_ctrlAvg;
@property(retain, nonatomic) UILabel *ctrlReason; // @synthesize ctrlReason=_ctrlReason;
@property(retain, nonatomic) UILabel *ctrlDistance; // @synthesize ctrlDistance=_ctrlDistance;
@property(retain, nonatomic) UIImageView *ctrlLocIcon; // @synthesize ctrlLocIcon=_ctrlLocIcon;
@property(retain, nonatomic) UILabel *ctrlRestName; // @synthesize ctrlRestName=_ctrlRestName;
@property(retain, nonatomic) CSUIImageView *ctrlImg; // @synthesize ctrlImg=_ctrlImg;
@property(retain, nonatomic) UIView *ctrlBg; // @synthesize ctrlBg=_ctrlBg;
@property BaseBizVc *nrVc; // @synthesize nrVc=_nrVc;
@property NSObject<CSMdbRlCellDelegate> *delegate; // @synthesize delegate=_delegate;
- (void)refresh:(id)arg1;
- (void)dealloc;
- (id)initWithVc:(id)arg1;

@end

