//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "CSPickBtnDelegate.h"

@class BaseListVc, CSPickBtn, MdbRlQueryParams, NSObject<CSMdbRlSelectPanelDelegate>, NSString;

@interface CSMdbRlSelectPanel : NSObject <CSPickBtnDelegate>
{
    NSObject<CSMdbRlSelectPanelDelegate> *_delegate;
    BaseListVc *_nrVc;
    MdbRlQueryParams *_nrPm;
    CSPickBtn *_ctrlLeftBtn;
    CSPickBtn *_ctrlMiddleBtn;
    CSPickBtn *_ctrlRightBtn;
}

@property(retain, nonatomic) CSPickBtn *ctrlRightBtn; // @synthesize ctrlRightBtn=_ctrlRightBtn;
@property(retain, nonatomic) CSPickBtn *ctrlMiddleBtn; // @synthesize ctrlMiddleBtn=_ctrlMiddleBtn;
@property(retain, nonatomic) CSPickBtn *ctrlLeftBtn; // @synthesize ctrlLeftBtn=_ctrlLeftBtn;
@property MdbRlQueryParams *nrPm; // @synthesize nrPm=_nrPm;
@property BaseListVc *nrVc; // @synthesize nrVc=_nrVc;
@property NSObject<CSMdbRlSelectPanelDelegate> *delegate; // @synthesize delegate=_delegate;
- (void)addSplitLineToRightList:(id)arg1 name:(id)arg2;
- (id)splitLineSelectId;
- (id)rightKeyWithSid1:(id)arg1 sid2:(id)arg2;
- (_Bool)chkIs0:(id)arg1;
- (void)invokeDelegate;
- (void)processWithLid:(id)arg1 lsname:(id)arg2 rid:(id)arg3 rsname:(id)arg4 tag:(int)arg5;
- (void)processRightWithSelectId:(id)arg1 sname:(id)arg2;
- (void)pickBtn:(id)arg1 leftSelectRow:(long long)arg2 leftSelectId:(id)arg3 leftSelectName:(id)arg4 rightSelectRow:(long long)arg5 rightSelectId:(id)arg6 rightSelectName:(id)arg7;
- (void)transToRightBtn;
- (void)transToLeftMiddleBtnWithBtnTag:(int)arg1;
- (void)pickBtnBeforeShowPicker:(id)arg1;
- (void)changeBtnTitleWithStartIndex:(long long)arg1;
- (void)reset;
- (void)dealloc;
- (id)initWithVc:(id)arg1 queryParams:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

