//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class BaseBizVc, CSNmBubble, CSUIImageView, MainPageBtnData, NSObject<CSNmBtnDelegate>, UILabel;

@interface CSNmBtn : UIView
{
    int _btnStyleTag;
    NSObject<CSNmBtnDelegate> *_delegate;
    BaseBizVc *_nrVc;
    CSUIImageView *_ctrlIcon;
    UILabel *_ctrlTitleLabel;
    UILabel *_ctrlHintLabel;
    CSNmBubble *_ctrlBubble;
    MainPageBtnData *_data;
}

+ (struct CGSize)btnSizeWithStyle:(int)arg1;
@property(nonatomic) int btnStyleTag; // @synthesize btnStyleTag=_btnStyleTag;
@property(retain, nonatomic) MainPageBtnData *data; // @synthesize data=_data;
@property(retain, nonatomic) CSNmBubble *ctrlBubble; // @synthesize ctrlBubble=_ctrlBubble;
@property(retain, nonatomic) UILabel *ctrlHintLabel; // @synthesize ctrlHintLabel=_ctrlHintLabel;
@property(retain, nonatomic) UILabel *ctrlTitleLabel; // @synthesize ctrlTitleLabel=_ctrlTitleLabel;
@property(retain, nonatomic) CSUIImageView *ctrlIcon; // @synthesize ctrlIcon=_ctrlIcon;
@property BaseBizVc *nrVc; // @synthesize nrVc=_nrVc;
@property NSObject<CSNmBtnDelegate> *delegate; // @synthesize delegate=_delegate;
- (void)btnClicked;
- (void)refresh;
- (_Bool)chkBubbleCacheNeedProcess;
- (id)numCacheKey;
- (void)saveBubbleClickToCache;
- (int)correctBubbleNum;
- (void)dealloc;
- (id)initWithVc:(id)arg1 data:(id)arg2 style:(int)arg3;

@end

