//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "CSNmBtnPanelDelegate.h"

@class BaseBizVc, CSNmBtnPanel, CSZyMainAdvImgPanel, NSObject<CSNmTopPanelDelegate>, NSString;

@interface CSNmTopPanel : UIView <CSNmBtnPanelDelegate>
{
    NSObject<CSNmTopPanelDelegate> *_delegate;
    BaseBizVc *_nrVc;
    CSZyMainAdvImgPanel *_ctrlAdPanel;
    CSNmBtnPanel *_ctrlMainBtnPanel;
    CSNmBtnPanel *_ctrlSecBtnPanel;
    UIView *_ctrlBottomLine;
}

@property(retain, nonatomic) UIView *ctrlBottomLine; // @synthesize ctrlBottomLine=_ctrlBottomLine;
@property(retain, nonatomic) CSNmBtnPanel *ctrlSecBtnPanel; // @synthesize ctrlSecBtnPanel=_ctrlSecBtnPanel;
@property(retain, nonatomic) CSNmBtnPanel *ctrlMainBtnPanel; // @synthesize ctrlMainBtnPanel=_ctrlMainBtnPanel;
@property(retain, nonatomic) CSZyMainAdvImgPanel *ctrlAdPanel; // @synthesize ctrlAdPanel=_ctrlAdPanel;
@property BaseBizVc *nrVc; // @synthesize nrVc=_nrVc;
@property NSObject<CSNmTopPanelDelegate> *delegate; // @synthesize delegate=_delegate;
- (void)onNmBtnPanelTryToNearTakeoutList;
- (void)onNmBtnPanelTryToNearRestList;
- (void)refresh:(id)arg1;
- (void)dealloc;
- (id)initWithVc:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

