//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "CSZyPicPanelDelegate.h"
#import "UITextFieldDelegate.h"

@class BaseBizVc, CSHtmLabel, CSUIButton, CSZyPicPanel, NSObject<CSOdTicketPanelDelegate>, NSString, UITextField;

@interface CSOdTicketPanel : UIView <UITextFieldDelegate, CSZyPicPanelDelegate>
{
    NSObject<CSOdTicketPanelDelegate> *_delegate;
    BaseBizVc *_nrVc;
    UIView *_ctrlContainer;
    CSHtmLabel *_ctrlReceiptHint;
    CSZyPicPanel *_ctrlReceiptPic;
    CSUIButton *_ctrlUploadReceiptBtn;
    UIView *_ctrlLine;
    CSHtmLabel *_ctrlInputPriceHint;
    UIView *_ctrlInputPricePanel;
    UITextField *_ctrlInputPrice;
    UIView *_ctrlPriceHintPanel;
    CSHtmLabel *_ctrlPriceHint;
    CSUIButton *_ctrlReportBtn;
}

@property(retain, nonatomic) CSUIButton *ctrlReportBtn; // @synthesize ctrlReportBtn=_ctrlReportBtn;
@property(retain, nonatomic) CSHtmLabel *ctrlPriceHint; // @synthesize ctrlPriceHint=_ctrlPriceHint;
@property(retain, nonatomic) UIView *ctrlPriceHintPanel; // @synthesize ctrlPriceHintPanel=_ctrlPriceHintPanel;
@property(retain, nonatomic) UITextField *ctrlInputPrice; // @synthesize ctrlInputPrice=_ctrlInputPrice;
@property(retain, nonatomic) UIView *ctrlInputPricePanel; // @synthesize ctrlInputPricePanel=_ctrlInputPricePanel;
@property(retain, nonatomic) CSHtmLabel *ctrlInputPriceHint; // @synthesize ctrlInputPriceHint=_ctrlInputPriceHint;
@property(retain, nonatomic) UIView *ctrlLine; // @synthesize ctrlLine=_ctrlLine;
@property(retain, nonatomic) CSUIButton *ctrlUploadReceiptBtn; // @synthesize ctrlUploadReceiptBtn=_ctrlUploadReceiptBtn;
@property(retain, nonatomic) CSZyPicPanel *ctrlReceiptPic; // @synthesize ctrlReceiptPic=_ctrlReceiptPic;
@property(retain, nonatomic) CSHtmLabel *ctrlReceiptHint; // @synthesize ctrlReceiptHint=_ctrlReceiptHint;
@property(retain, nonatomic) UIView *ctrlContainer; // @synthesize ctrlContainer=_ctrlContainer;
@property BaseBizVc *nrVc; // @synthesize nrVc=_nrVc;
@property NSObject<CSOdTicketPanelDelegate> *delegate; // @synthesize delegate=_delegate;
- (id)newUploadButton;
- (id)newLabel:(struct CGRect)arg1;
- (void)btnClick_reportError;
- (void)btnClick_submitPrice;
- (void)btnClick_uploadReceipt;
- (void)onZyPicPanelClicked:(id)arg1;
- (_Bool)textFieldShouldBeginEditing:(id)arg1;
- (_Bool)textFieldShouldReturn:(id)arg1;
- (void)hideKeyBoard;
- (void)refresh:(id)arg1;
- (void)dealloc;
- (id)initWithVc:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

