//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "UIPickerViewDataSource.h"
#import "UIPickerViewDelegate.h"

@class BaseLayoutSupportVc, NSMutableArray, NSObject<CSOpPickerPanelDelegate>, NSString, UIPickerView;

@interface CSOpPickerPanel : UIView <UIPickerViewDelegate, UIPickerViewDataSource>
{
    float _scaleX;
    float _scaleY;
    NSObject<CSOpPickerPanelDelegate> *_delegate;
    BaseLayoutSupportVc *_nrVc;
    UIPickerView *_ctrlPicker;
    NSMutableArray *_pickerList;
}

@property(nonatomic) float scaleY; // @synthesize scaleY=_scaleY;
@property(nonatomic) float scaleX; // @synthesize scaleX=_scaleX;
@property(retain, nonatomic) NSMutableArray *pickerList; // @synthesize pickerList=_pickerList;
@property(retain, nonatomic) UIPickerView *ctrlPicker; // @synthesize ctrlPicker=_ctrlPicker;
@property BaseLayoutSupportVc *nrVc; // @synthesize nrVc=_nrVc;
@property NSObject<CSOpPickerPanelDelegate> *delegate; // @synthesize delegate=_delegate;
- (_Bool)chkCanDoWithCompont:(long long)arg1;
- (id)findSelectIdWithComponent:(int)arg1;
- (void)changeSelRowWithComponent:(long long)arg1 sid:(id)arg2;
- (void)pickerView:(id)arg1 didSelectRow:(long long)arg2 inComponent:(long long)arg3;
- (id)pickerView:(id)arg1 viewForRow:(long long)arg2 forComponent:(long long)arg3 reusingView:(id)arg4;
- (double)pickerView:(id)arg1 rowHeightForComponent:(long long)arg2;
- (long long)pickerView:(id)arg1 numberOfRowsInComponent:(long long)arg2;
- (long long)numberOfComponentsInPickerView:(id)arg1;
- (id)newRoomSelListWithTransData:(id)arg1;
- (void)addRoomSelListWithTransData:(id)arg1;
- (void)addPeopleSelList;
- (void)addTimeSelList;
- (void)addDateSelList;
- (int)selRoomType;
- (int)selPeopleNum;
- (double)selReserveTime;
- (void)changeSelWithTransData:(id)arg1;
- (void)refreshWithTransData:(id)arg1;
- (void)changeRoomTypePickerWithData:(id)arg1;
- (void)resetWithRoomTypeInfoData:(id)arg1;
- (void)dealloc;
- (id)initWithVc:(id)arg1 height:(float)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

