//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BaseDlgView.h"

@class CSOpPickerPanel, NSObject<CSOpSelDlgPanelDelegate>;

@interface CSOpSelDlgPanel : BaseDlgView
{
    NSObject<CSOpSelDlgPanelDelegate> *_delegate;
    CSOpPickerPanel *_ctrlPickerPanel;
}

@property(retain, nonatomic) CSOpPickerPanel *ctrlPickerPanel; // @synthesize ctrlPickerPanel=_ctrlPickerPanel;
@property NSObject<CSOpSelDlgPanelDelegate> *delegate; // @synthesize delegate=_delegate;
- (void)onHideAnimeFinished;
- (void)okBtnClick;
- (void)open:(id)arg1 fromRect:(struct CGRect)arg2;
- (void)refresh:(id)arg1;
- (void)dealloc;
- (id)initWithVc:(id)arg1;

@end

