//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BaseDlgView.h"

#import "CSUIComboBoxDelegate.h"

@class CSUIComboBox, NSObject<CSOrderCalSelPanelDelegate>, OrderInfoData3, UITextView;

@interface CSOrderCalSelPanel : BaseDlgView <CSUIComboBoxDelegate>
{
    NSObject<CSOrderCalSelPanelDelegate> *_delegate;
    UITextView *_ctrlTextView;
    CSUIComboBox *_ctrlComboBox;
    OrderInfoData3 *_data;
    long long _alertSelected;
}

@property(nonatomic) long long alertSelected; // @synthesize alertSelected=_alertSelected;
@property(retain, nonatomic) OrderInfoData3 *data; // @synthesize data=_data;
@property(retain, nonatomic) CSUIComboBox *ctrlComboBox; // @synthesize ctrlComboBox=_ctrlComboBox;
@property(retain, nonatomic) UITextView *ctrlTextView; // @synthesize ctrlTextView=_ctrlTextView;
@property NSObject<CSOrderCalSelPanelDelegate> *delegate; // @synthesize delegate=_delegate;
- (void)hide;
- (id)titleWithData:(id)arg1;
- (void)cancelBtnClick;
- (void)okBtnClick;
- (void)makeComboBox:(id)arg1;
- (void)comboBox:(id)arg1 didSelected:(long long)arg2 selectId:(id)arg3 selectName:(id)arg4;
- (void)comboBoxBeforeShowPicker:(id)arg1;
- (void)showWithData:(id)arg1;
- (void)dealloc;
- (id)initWithVc:(id)arg1;

@end

