//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class CSOrderRtTimeBtnView, NSString;

@protocol CSOrderRtTimeBtnViewDelegate <NSObject>

@optional
- (void)onCSOrderRtTimeBtnViewClicked:(CSOrderRtTimeBtnView *)arg1 uuid:(NSString *)arg2;
@end

