//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class BaseLayoutSupportVc, CSOpPickerPanel, NSObject<CSOrderPanelDelegate>, SuggestResultData, UIButton, UILabel;

@interface CSOrderPanel : UIView
{
    NSObject<CSOrderPanelDelegate> *_delegate;
    BaseLayoutSupportVc *_nrVc;
    UIView *_ctrlBookView;
    UIView *_ctrlTelView;
    CSOpPickerPanel *_ctrlPicker;
    UIButton *_ctrlTelBtn;
    UILabel *_ctrlTelLabel;
    SuggestResultData *_dto;
}

@property(retain, nonatomic) SuggestResultData *dto; // @synthesize dto=_dto;
@property(retain, nonatomic) UILabel *ctrlTelLabel; // @synthesize ctrlTelLabel=_ctrlTelLabel;
@property(retain, nonatomic) UIButton *ctrlTelBtn; // @synthesize ctrlTelBtn=_ctrlTelBtn;
@property(retain, nonatomic) CSOpPickerPanel *ctrlPicker; // @synthesize ctrlPicker=_ctrlPicker;
@property(retain, nonatomic) UIView *ctrlTelView; // @synthesize ctrlTelView=_ctrlTelView;
@property(retain, nonatomic) UIView *ctrlBookView; // @synthesize ctrlBookView=_ctrlBookView;
@property BaseLayoutSupportVc *nrVc; // @synthesize nrVc=_nrVc;
@property NSObject<CSOrderPanelDelegate> *delegate; // @synthesize delegate=_delegate;
- (void)btnClick_tel;
- (void)btnClick_submit;
- (void)refresh:(id)arg1 needResetPicker:(_Bool)arg2;
- (void)refreshForSelect:(id)arg1;
- (void)refresh:(id)arg1;
- (void)dealloc;
- (id)initWithVc:(id)arg1;

@end

