//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSObject<CSOrderRefreshViewDelegate>, UIActivityIndicatorView, UIImageView, UILabel;

@interface CSOrderRefreshView : UIView
{
    NSObject<CSOrderRefreshViewDelegate> *delegate;
    UIView *ctrlPanelHint;
    UIImageView *ctrlArrowImageView;
    UILabel *ctrlHintLabel;
    UIView *ctrlPanelLoading;
    UIActivityIndicatorView *ctrlIndicator;
    UILabel *ctrlLoadingLabel;
    _Bool needRefreshTag;
    _Bool isLoadingTag;
    _Bool showOnBottomTag;
}

@property(nonatomic) _Bool showOnBottomTag; // @synthesize showOnBottomTag;
@property(nonatomic) _Bool isLoadingTag; // @synthesize isLoadingTag;
@property(nonatomic) _Bool needRefreshTag; // @synthesize needRefreshTag;
@property(retain, nonatomic) UILabel *ctrlLoadingLabel; // @synthesize ctrlLoadingLabel;
@property(retain, nonatomic) UIActivityIndicatorView *ctrlIndicator; // @synthesize ctrlIndicator;
@property(retain, nonatomic) UIView *ctrlPanelLoading; // @synthesize ctrlPanelLoading;
@property(retain, nonatomic) UILabel *ctrlHintLabel; // @synthesize ctrlHintLabel;
@property(retain, nonatomic) UIImageView *ctrlArrowImageView; // @synthesize ctrlArrowImageView;
@property(retain, nonatomic) UIView *ctrlPanelHint; // @synthesize ctrlPanelHint;
@property NSObject<CSOrderRefreshViewDelegate> *delegate; // @synthesize delegate;
- (void)waitForNextRefresh:(id)arg1;
- (void)hideRefresh:(id)arg1;
- (void)animationPanel:(id)arg1 finished:(_Bool)arg2 context:(void *)arg3;
- (void)setTopPosition:(id)arg1 needHide:(_Bool)arg2;
- (void)resetWithNeedHide:(_Bool)arg1;
- (void)refreshWhenScrollViewDidEndDragging;
- (void)refreshWhenScrollViewDidScroll;
- (void)dealloc;
- (id)initWithStyle:(int)arg1 width:(int)arg2 showOnBottom:(_Bool)arg3;

@end

