//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "CSUIScrollBtnsDelegate.h"

@class BaseBizVc, CSUIScrollBtnsDesk, NSObject<CSOrderRtTablePanelDelegate>, NSString, UIActivityIndicatorView, UIButton, UILabel;

@interface CSOrderRtTablePanel : UIView <CSUIScrollBtnsDelegate>
{
    NSObject<CSOrderRtTablePanelDelegate> *_delegate;
    BaseBizVc *_nrVc;
    CSUIScrollBtnsDesk *_ctrlScrollView;
    UILabel *_ctrlPromptLabel;
    UIButton *_ctrlSubmitBtn;
    UIView *_ctrlWaitingPanel;
    UIActivityIndicatorView *_ctrlAi;
}

@property(retain, nonatomic) UIActivityIndicatorView *ctrlAi; // @synthesize ctrlAi=_ctrlAi;
@property(retain, nonatomic) UIView *ctrlWaitingPanel; // @synthesize ctrlWaitingPanel=_ctrlWaitingPanel;
@property(retain, nonatomic) UIButton *ctrlSubmitBtn; // @synthesize ctrlSubmitBtn=_ctrlSubmitBtn;
@property(retain, nonatomic) UILabel *ctrlPromptLabel; // @synthesize ctrlPromptLabel=_ctrlPromptLabel;
@property(retain, nonatomic) CSUIScrollBtnsDesk *ctrlScrollView; // @synthesize ctrlScrollView=_ctrlScrollView;
@property(nonatomic) __weak BaseBizVc *nrVc; // @synthesize nrVc=_nrVc;
@property(nonatomic) __weak NSObject<CSOrderRtTablePanelDelegate> *delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)submitBtnClicked;
- (void)onCSUIScrollBtns:(id)arg1 btnClickedAtIndex:(long long)arg2;
- (void)createWaitingView;
- (void)showSep;
- (void)enableSubmit;
- (void)hideWaiting;
- (void)showWaiting;
- (void)reset;
- (void)refresh:(id)arg1;
- (void)dealloc;
- (id)initWithVc:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

