//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "CSOpSlidePicPanelDelegate.h"

@class BaseBizVc, CSHtmLabel, CSOpSlidePicPanel, CSUIButton, NSObject<CSOsOpPanelDelegate>, NSString;

@interface CSOsOpPanel : UIView <CSOpSlidePicPanelDelegate>
{
    NSObject<CSOsOpPanelDelegate> *_delegate;
    BaseBizVc *_nrVc;
    CSHtmLabel *_ctrlText;
    CSOpSlidePicPanel *_ctrlPicPanel;
    CSUIButton *_ctrlShareBtn;
}

@property(retain, nonatomic) CSUIButton *ctrlShareBtn; // @synthesize ctrlShareBtn=_ctrlShareBtn;
@property(retain, nonatomic) CSOpSlidePicPanel *ctrlPicPanel; // @synthesize ctrlPicPanel=_ctrlPicPanel;
@property(retain, nonatomic) CSHtmLabel *ctrlText; // @synthesize ctrlText=_ctrlText;
@property BaseBizVc *nrVc; // @synthesize nrVc=_nrVc;
@property NSObject<CSOsOpPanelDelegate> *delegate; // @synthesize delegate=_delegate;
- (void)shareBtnClicked;
- (void)onOpSlidePicPanelPicClicked;
- (void)refresh:(id)arg1;
- (void)dealloc;
- (id)initWithVc:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

