//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class CSPickBtn, NSString;

@protocol CSPickBtnDelegate <NSObject>
- (void)pickBtn:(CSPickBtn *)arg1 leftSelectRow:(long long)arg2 leftSelectId:(NSString *)arg3 leftSelectName:(NSString *)arg4 rightSelectRow:(long long)arg5 rightSelectId:(NSString *)arg6 rightSelectName:(NSString *)arg7;

@optional
- (void)pickBtnBeforeShowPicker:(CSPickBtn *)arg1;
@end

