//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIButton.h"

#import "CSPickPanelDelegate.h"

@class BaseVc, CSPickPanel, CommonSelectListPack, NSObject<CSPickBtnDelegate>, NSString, UIImageView;

@interface CSPickBtn : UIButton <CSPickPanelDelegate>
{
    _Bool _twoColumnTag;
    _Bool _relateTabelTag;
    int _leftIdx;
    int _rightIdx;
    NSObject<CSPickBtnDelegate> *_delegate;
    BaseVc *_nrVc;
    CSPickPanel *_nrPickPanel;
    UIImageView *_ctrlArrow;
    CommonSelectListPack *_pack;
}

@property(nonatomic) _Bool relateTabelTag; // @synthesize relateTabelTag=_relateTabelTag;
@property(retain, nonatomic) CommonSelectListPack *pack; // @synthesize pack=_pack;
@property(nonatomic) int rightIdx; // @synthesize rightIdx=_rightIdx;
@property(nonatomic) int leftIdx; // @synthesize leftIdx=_leftIdx;
@property(nonatomic) _Bool twoColumnTag; // @synthesize twoColumnTag=_twoColumnTag;
@property(retain, nonatomic) UIImageView *ctrlArrow; // @synthesize ctrlArrow=_ctrlArrow;
@property CSPickPanel *nrPickPanel; // @synthesize nrPickPanel=_nrPickPanel;
@property BaseVc *nrVc; // @synthesize nrVc=_nrVc;
@property NSObject<CSPickBtnDelegate> *delegate; // @synthesize delegate=_delegate;
- (void)pickPanel:(id)arg1 leftSelectRow:(long long)arg2 leftSelectId:(id)arg3 leftSelectName:(id)arg4 rightSelectRow:(long long)arg5 rightSelectId:(id)arg6 rightSelectName:(id)arg7;
- (id)newFindSAt:(id)arg1 selectId:(id)arg2;
- (id)newFindPAt:(id)arg1 selectId:(id)arg2;
- (void)changeSelectionWithLeftSelectId:(id)arg1 rightSelectId:(id)arg2;
- (void)changePack:(id)arg1;
- (void)btnClicked;
- (void)changeWithPack:(id)arg1 leftId:(id)arg2 rightId:(id)arg3;
- (void)changeWithList:(id)arg1 selectId:(id)arg2;
- (void)changeTitle:(id)arg1;
- (void)dealloc;
- (id)initWithVc:(id)arg1 pickPanel:(id)arg2 frame:(struct CGRect)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

