//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "CSPickTbPanelDelegate.h"

@class BaseVc, CSPickTbPanel, NSObject<CSPickPanelDelegate>, NSString;

@interface CSPickPanel : UIView <CSPickTbPanelDelegate>
{
    NSObject<CSPickPanelDelegate> *_delegate;
    BaseVc *_nrVc;
    UIView *_ctrlTopMask;
    UIView *_ctrlBottomMask;
    CSPickTbPanel *_ctrlTbPanel;
}

@property(retain, nonatomic) CSPickTbPanel *ctrlTbPanel; // @synthesize ctrlTbPanel=_ctrlTbPanel;
@property(retain, nonatomic) UIView *ctrlBottomMask; // @synthesize ctrlBottomMask=_ctrlBottomMask;
@property(retain, nonatomic) UIView *ctrlTopMask; // @synthesize ctrlTopMask=_ctrlTopMask;
@property BaseVc *nrVc; // @synthesize nrVc=_nrVc;
@property NSObject<CSPickPanelDelegate> *delegate; // @synthesize delegate=_delegate;
- (void)pickTbPanel:(id)arg1 leftSelectRow:(long long)arg2 leftSelectId:(id)arg3 leftSelectName:(id)arg4 rightSelectRow:(long long)arg5 rightSelectId:(id)arg6 rightSelectName:(id)arg7;
- (void)handleTap;
- (void)openPanelWithTop:(int)arg1;
- (void)showWithPack:(id)arg1 leftIdx:(int)arg2 rightIdx:(int)arg3 twoColumnTag:(_Bool)arg4 top:(int)arg5 relateTabelTag:(_Bool)arg6;
- (void)dealloc;
- (id)initWithVc:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

