//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "AVAudioPlayerDelegate.h"
#import "AVAudioRecorderDelegate.h"
#import "AVAudioSessionDelegate.h"

@class AVAudioPlayer, AVAudioRecorder, BaseVc, NSObject<CSPlayerDelegate>, NSString;

@interface CSPlayer : NSObject <AVAudioRecorderDelegate, AVAudioPlayerDelegate, AVAudioSessionDelegate>
{
    NSObject<CSPlayerDelegate> *delegate;
    BaseVc *nrVc;
    AVAudioRecorder *ctrlAudioRecorder;
    AVAudioPlayer *ctrlAudioPlayer;
    _Bool isRecordingTag;
    double lastRecordBeginAt;
    _Bool isRecordingTooShortTag;
}

+ (void)deactivateSession;
@property(nonatomic) _Bool isRecordingTooShortTag; // @synthesize isRecordingTooShortTag;
@property(nonatomic) double lastRecordBeginAt; // @synthesize lastRecordBeginAt;
@property(nonatomic) _Bool isRecordingTag; // @synthesize isRecordingTag;
@property(retain, nonatomic) AVAudioPlayer *ctrlAudioPlayer; // @synthesize ctrlAudioPlayer;
@property(retain, nonatomic) AVAudioRecorder *ctrlAudioRecorder; // @synthesize ctrlAudioRecorder;
@property BaseVc *nrVc; // @synthesize nrVc;
@property NSObject<CSPlayerDelegate> *delegate; // @synthesize delegate;
- (void)receivingAVInterruptionListener:(id)arg1;
- (id)zipPathForRecordingFile:(id)arg1;
- (id)mp3FileLocFromCafFileLoc:(id)arg1;
- (id)audioFileNameWithKey:(id)arg1;
- (id)generateNewRecordFileName;
- (id)getKeyFromFileLoc:(id)arg1;
- (id)recordsStore;
- (id)dirWithRecordFilename:(id)arg1;
- (id)urlWithPreloadFilename:(id)arg1;
- (id)urlWithRecordFilename:(id)arg1;
- (void)invokeDelegateRecordError;
- (void)invokeDelegateRecordTooShort;
- (void)invokeDelegateRecordSuccess;
- (void)invalideAudioPlayer;
- (void)invalideAudioRecorder;
- (void)audioRecorderEndInterruption:(id)arg1 withOptions:(unsigned long long)arg2;
- (void)audioRecorderBeginInterruption:(id)arg1;
- (void)audioRecorderEncodeErrorDidOccur:(id)arg1 error:(id)arg2;
- (void)audioRecorderDidFinishRecording:(id)arg1 successfully:(_Bool)arg2;
- (void)audioPlayerDidFinishPlaying:(id)arg1 successfully:(_Bool)arg2;
- (void)audioPlayerEndInterruption:(id)arg1 withOptions:(unsigned long long)arg2;
- (void)audioPlayerBeginInterruption:(id)arg1;
- (void)play;
- (void)playByKey:(id)arg1;
- (void)playByFileName:(id)arg1;
- (void)recordStopWithoutFileOuput;
- (void)recordStop;
- (void)recordStart;
- (void)stop;
- (void)reset;
- (void)dealloc;
- (id)initWithVc:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

