//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIButton.h"

@class BaseBizVc, CSbubble, NSObject<CSPointButtonDelegate>, UILabel;

@interface CSPointButton : UIButton
{
    _Bool _isHidingTag;
    NSObject<CSPointButtonDelegate> *_delegate;
    BaseBizVc *_nrVc;
    UILabel *_ctrlNumLabel;
    CSbubble *_ctrlBubble;
}

@property(nonatomic) _Bool isHidingTag; // @synthesize isHidingTag=_isHidingTag;
@property(retain, nonatomic) CSbubble *ctrlBubble; // @synthesize ctrlBubble=_ctrlBubble;
@property(retain, nonatomic) UILabel *ctrlNumLabel; // @synthesize ctrlNumLabel=_ctrlNumLabel;
@property BaseBizVc *nrVc; // @synthesize nrVc=_nrVc;
@property NSObject<CSPointButtonDelegate> *delegate; // @synthesize delegate=_delegate;
- (void)finishHideAnimation;
- (void)handleHidePanel;
- (void)open;
- (void)reset;
- (void)showNum:(double)arg1 withBubble:(double)arg2;
- (void)dealloc;
- (id)initWithVc:(id)arg1 withText:(id)arg2;

@end

