//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class BaseBizVc, NSObject<CSPsMovePanelDelegate>, UIImageView;

@interface CSPsMovePanel : UIView
{
    _Bool _isChangingTag;
    _Bool _isHlTag;
    NSObject<CSPsMovePanelDelegate> *_delegate;
    BaseBizVc *_nrVc;
    UIImageView *_ctrlBg;
    long long _gestureTypeTag;
    struct CGPoint _currentPoint;
}

@property(nonatomic) _Bool isHlTag; // @synthesize isHlTag=_isHlTag;
@property(nonatomic) struct CGPoint currentPoint; // @synthesize currentPoint=_currentPoint;
@property(nonatomic) long long gestureTypeTag; // @synthesize gestureTypeTag=_gestureTypeTag;
@property(nonatomic) _Bool isChangingTag; // @synthesize isChangingTag=_isChangingTag;
@property(retain, nonatomic) UIImageView *ctrlBg; // @synthesize ctrlBg=_ctrlBg;
@property(nonatomic) __weak BaseBizVc *nrVc; // @synthesize nrVc=_nrVc;
@property(nonatomic) __weak NSObject<CSPsMovePanelDelegate> *delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)changePosWithW:(double)arg1 h:(double)arg2 l:(double)arg3 t:(double)arg4;
- (void)changeBgState:(_Bool)arg1;
- (double)screenHeight;
- (double)screenWidth;
- (void)handelPan:(id)arg1;
- (void)refreshPanel;
- (void)dealloc;
- (id)initWithVc:(id)arg1;

@end

