//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class BaseBizVc, NSObject<CSPsImageEditPanelDelegate>, NSString, NSTimer, UIButton, UIImage, UIImageView;

@interface CSPsImageEditPanel : UIView
{
    _Bool _isSubtitledHintOn;
    _Bool _hasEditedSubtitle;
    _Bool _isSubtitledTag;
    _Bool _isCroppedTag;
    NSObject<CSPsImageEditPanelDelegate> *_delegate;
    BaseBizVc *_nrVc;
    UIImage *_originalImage;
    UIImageView *_ctrlPhotoShown;
    UIButton *_ctrlSubtitleLabel;
    UIButton *_ctrlSubtitleTransLabel;
    UIButton *_ctrlSubtitleBtn;
    UIButton *_ctrlSubtitleInputHint;
    NSTimer *_ctrlSubtitleBlinkTimer;
    NSString *_subtitle;
    NSString *_subtitleTranslated;
}

+ (id)centerCropImageForWideScreen:(id)arg1;
@property(nonatomic) _Bool isCroppedTag; // @synthesize isCroppedTag=_isCroppedTag;
@property(nonatomic) _Bool isSubtitledTag; // @synthesize isSubtitledTag=_isSubtitledTag;
@property(nonatomic) _Bool hasEditedSubtitle; // @synthesize hasEditedSubtitle=_hasEditedSubtitle;
@property(retain, nonatomic) NSString *subtitleTranslated; // @synthesize subtitleTranslated=_subtitleTranslated;
@property(retain, nonatomic) NSString *subtitle; // @synthesize subtitle=_subtitle;
@property(nonatomic) _Bool isSubtitledHintOn; // @synthesize isSubtitledHintOn=_isSubtitledHintOn;
@property(retain, nonatomic) NSTimer *ctrlSubtitleBlinkTimer; // @synthesize ctrlSubtitleBlinkTimer=_ctrlSubtitleBlinkTimer;
@property(retain, nonatomic) UIButton *ctrlSubtitleInputHint; // @synthesize ctrlSubtitleInputHint=_ctrlSubtitleInputHint;
@property(retain, nonatomic) UIButton *ctrlSubtitleBtn; // @synthesize ctrlSubtitleBtn=_ctrlSubtitleBtn;
@property(retain, nonatomic) UIButton *ctrlSubtitleTransLabel; // @synthesize ctrlSubtitleTransLabel=_ctrlSubtitleTransLabel;
@property(retain, nonatomic) UIButton *ctrlSubtitleLabel; // @synthesize ctrlSubtitleLabel=_ctrlSubtitleLabel;
@property(retain, nonatomic) UIImageView *ctrlPhotoShown; // @synthesize ctrlPhotoShown=_ctrlPhotoShown;
@property(retain, nonatomic) UIImage *originalImage; // @synthesize originalImage=_originalImage;
@property(nonatomic) __weak BaseBizVc *nrVc; // @synthesize nrVc=_nrVc;
@property(nonatomic) __weak NSObject<CSPsImageEditPanelDelegate> *delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)saveImage:(id)arg1 toAlbum:(id)arg2 withCompletionBlock:(CDUnknownBlockType)arg3;
- (id)drawSubtitle:(id)arg1 translation:(id)arg2 inImage:(id)arg3;
- (id)fontBaseOnImage:(id)arg1;
- (struct CGSize)calcSubtitleSize:(id)arg1 basedOnImage:(id)arg2 maxLines:(int)arg3;
- (void)stopTimer;
- (void)turnOffSubtitleInputHint;
- (void)turnOnSubtitleInputHint;
- (void)handleBlink;
- (void)determineSubtitleLoc;
- (void)hideSubtitleWidgets;
- (void)showSubtitleWidgets;
- (void)navToSubtitle;
- (void)toggleSubtitle;
- (void)toggleWideScreen;
- (id)saveImage;
- (void)refreshSubtitle:(id)arg1 translation:(id)arg2;
- (void)loadImage:(id)arg1;
- (void)reset;
- (void)dealloc;
- (id)initWithVc:(id)arg1;

@end

