//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSMutableArray, NSObject<CSRdNearBtnPanelDelegate>;

@interface CSRdNearBtnPanel : UIView
{
    NSObject<CSRdNearBtnPanelDelegate> *_delegate;
    NSMutableArray *_btnList;
}

+ (long long)calRowWithCount:(long long)arg1;
+ (long long)calPanelHeight:(long long)arg1;
@property(retain, nonatomic) NSMutableArray *btnList; // @synthesize btnList=_btnList;
@property NSObject<CSRdNearBtnPanelDelegate> *delegate; // @synthesize delegate=_delegate;
- (void)btnClicked:(id)arg1;
- (void)refresh:(id)arg1;
- (void)dealloc;
- (id)initWithVc:(id)arg1;

@end

