//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class BaseLayoutSupportVc, NSObject<CSRdTopRightPanelDelegate>, UIButton;

@interface CSRdTopRightPanel : UIView
{
    NSObject<CSRdTopRightPanelDelegate> *_delegate;
    BaseLayoutSupportVc *_nrVc;
    UIButton *_ctrlShareBtn;
    UIButton *_ctrlFavBtn;
}

@property(retain, nonatomic) UIButton *ctrlFavBtn; // @synthesize ctrlFavBtn=_ctrlFavBtn;
@property(retain, nonatomic) UIButton *ctrlShareBtn; // @synthesize ctrlShareBtn=_ctrlShareBtn;
@property BaseLayoutSupportVc *nrVc; // @synthesize nrVc=_nrVc;
@property NSObject<CSRdTopRightPanelDelegate> *delegate; // @synthesize delegate=_delegate;
- (void)refreshWithFavTag:(_Bool)arg1 needAnime:(_Bool)arg2;
- (void)invoke:(int)arg1;
- (void)shareBtnClicked;
- (void)favBtnClicked;
- (void)refreshForMdbWithAnime:(id)arg1;
- (void)refreshForMdb:(id)arg1;
- (void)refreshForTkWithAnime:(id)arg1;
- (void)refreshForTk:(id)arg1;
- (void)refreshPanel:(id)arg1 typeTag:(int)arg2 anime:(_Bool)arg3;
- (void)refreshPanelWithAnime:(id)arg1 typeTag:(int)arg2;
- (void)refreshPanel:(id)arg1 typeTag:(int)arg2;
- (void)reset;
- (void)dealloc;
- (id)initWithVc:(id)arg1;

@end

