//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "CSRlCheckBoxDelegate.h"

@class BaseLayoutSupportVc, NSObject<CSRdLabelPanelDelegate>, NSString;

@interface CSRdLabelPanel : UIView <CSRlCheckBoxDelegate>
{
    int _styleTag;
    NSObject<CSRdLabelPanelDelegate> *_delegate;
    BaseLayoutSupportVc *_nrVc;
}

+ (long long)panelHeightWithListForCell:(id)arg1;
@property int styleTag; // @synthesize styleTag=_styleTag;
@property BaseLayoutSupportVc *nrVc; // @synthesize nrVc=_nrVc;
@property NSObject<CSRdLabelPanelDelegate> *delegate; // @synthesize delegate=_delegate;
- (void)onRlCheckBoxCheckedWithDataIndex:(int)arg1 select:(_Bool)arg2;
- (void)refreshWithList:(id)arg1 style:(int)arg2;
- (void)refreshWithListForEdit:(id)arg1;
- (void)refreshWithListForShow:(id)arg1;
- (void)refreshWithListForCell:(id)arg1;
- (void)dealloc;
- (id)initWithVc:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

