//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class BaseBizVc, NSObject<CSRdRrDotDelegate>, UIImageView;

@interface CSRdRrDot : UIView
{
    NSObject<CSRdRrDotDelegate> *_delegate;
    BaseBizVc *_nrVc;
    UIImageView *_ctrlIcon;
}

@property(retain, nonatomic) UIImageView *ctrlIcon; // @synthesize ctrlIcon=_ctrlIcon;
@property BaseBizVc *nrVc; // @synthesize nrVc=_nrVc;
@property NSObject<CSRdRrDotDelegate> *delegate; // @synthesize delegate=_delegate;
- (void)changeDotWithRecomTag:(_Bool)arg1;
- (void)reset;
- (void)dealloc;
- (id)initWithVc:(id)arg1;

@end

