//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class CSUIImageView, UILabel, UIScrollView;

@interface CSRestFoodCellView : UIView
{
    _Bool _hasDotted;
    id <CSRestFoodCellViewDelegate> _delegate;
    UILabel *_ctrlAddTime;
    UILabel *_ctrlDetail;
    CSUIImageView *_ctrlFaceImage;
    UILabel *_ctrlName;
    UIScrollView *_ctrlFoodImage;
}

+ (id)newButtonFrame:(struct CGRect)arg1 withScaleImageURL:(id)arg2 andOriginalImageURL:(id)arg3;
+ (double)heightForComment:(id)arg1;
+ (struct CGSize)sizeForComment:(id)arg1;
@property(retain, nonatomic) UIScrollView *ctrlFoodImage; // @synthesize ctrlFoodImage=_ctrlFoodImage;
@property(nonatomic) _Bool hasDotted; // @synthesize hasDotted=_hasDotted;
@property(retain, nonatomic) UILabel *ctrlName; // @synthesize ctrlName=_ctrlName;
@property(retain, nonatomic) CSUIImageView *ctrlFaceImage; // @synthesize ctrlFaceImage=_ctrlFaceImage;
@property(retain, nonatomic) UILabel *ctrlDetail; // @synthesize ctrlDetail=_ctrlDetail;
@property(retain, nonatomic) UILabel *ctrlAddTime; // @synthesize ctrlAddTime=_ctrlAddTime;
@property(nonatomic) id <CSRestFoodCellViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void)btnClick_foodImage:(id)arg1;
- (void)flushWith:(id)arg1 andDotted:(_Bool)arg2;
- (void)drawRect:(struct CGRect)arg1;
- (void)dealloc;
- (id)initWithWidth:(double)arg1;

@end

