//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSMutableArray;

@interface CSRestScoreView : UIView
{
    long long _score;
    NSMutableArray *btnList;
}

- (void)btnClick_ChangeScore:(id)arg1;
@property long long Score;
- (void)dealloc;
- (id)initWithTitle:(id)arg1 andScore:(long long)arg2;

@end

