//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class UIActivityIndicatorView, UIImageView, UILabel;

@interface CSRefreshView : UIView
{
    UIView *ctrlPanelHint;
    UIImageView *ctrlArrowImageView;
    UILabel *ctrlHintLabel;
    UIView *ctrlPanelLoading;
    UIActivityIndicatorView *ctrlIndicator;
    UILabel *ctrlLoadingLabel;
    _Bool needRefreshTag;
    _Bool isLoadingTag;
}

@property(nonatomic) _Bool isLoadingTag; // @synthesize isLoadingTag;
@property(nonatomic) _Bool needRefreshTag; // @synthesize needRefreshTag;
@property(retain, nonatomic) UILabel *ctrlLoadingLabel; // @synthesize ctrlLoadingLabel;
@property(retain, nonatomic) UIActivityIndicatorView *ctrlIndicator; // @synthesize ctrlIndicator;
@property(retain, nonatomic) UIView *ctrlPanelLoading; // @synthesize ctrlPanelLoading;
@property(retain, nonatomic) UILabel *ctrlHintLabel; // @synthesize ctrlHintLabel;
@property(retain, nonatomic) UIImageView *ctrlArrowImageView; // @synthesize ctrlArrowImageView;
@property(retain, nonatomic) UIView *ctrlPanelHint; // @synthesize ctrlPanelHint;
- (void)waitForNextRefresh:(id)arg1;
- (void)hideRefresh:(id)arg1;
- (void)refreshWhenScrollViewDidEndDragging:(id)arg1;
- (void)refreshWhenScrollViewDidScroll:(id)arg1;
- (void)dealloc;
- (id)initWithStyle:(int)arg1;

@end

