//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "UITextFieldDelegate.h"

@class BaseLayoutSupportVc, CSUIButton, CSZyInput, NSObject<CSRIAddLabelPanelDelegate>, NSString, UILabel;

@interface CSRIAddLabelPanel : UIView <UITextFieldDelegate>
{
    NSObject<CSRIAddLabelPanelDelegate> *_delegate;
    BaseLayoutSupportVc *_nrVc;
    UIView *_ctrlBg;
    UILabel *_ctrlHint;
    CSZyInput *_ctrlLabelTf;
    CSUIButton *_ctrlBtn;
}

@property(retain, nonatomic) CSUIButton *ctrlBtn; // @synthesize ctrlBtn=_ctrlBtn;
@property(retain, nonatomic) CSZyInput *ctrlLabelTf; // @synthesize ctrlLabelTf=_ctrlLabelTf;
@property(retain, nonatomic) UILabel *ctrlHint; // @synthesize ctrlHint=_ctrlHint;
@property(retain, nonatomic) UIView *ctrlBg; // @synthesize ctrlBg=_ctrlBg;
@property BaseLayoutSupportVc *nrVc; // @synthesize nrVc=_nrVc;
@property NSObject<CSRIAddLabelPanelDelegate> *delegate; // @synthesize delegate=_delegate;
- (void)hideKeyBoard;
- (void)reset;
- (_Bool)validate;
- (void)addBtnClick;
- (void)cancelBtnClick;
- (_Bool)textField:(id)arg1 shouldChangeCharactersInRange:(struct _NSRange)arg2 replacementString:(id)arg3;
- (void)open;
- (void)dealloc;
- (id)initWithVc:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

