//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "CSRrWaterfallCellDelegate.h"

@class BaseVc, NSMutableArray, NSObject<CSRrWaterfallPanelDelegate>, NSString, RestRecomListDTO;

@interface CSRrWaterfallPanel : UIView <CSRrWaterfallCellDelegate>
{
    NSObject<CSRrWaterfallPanelDelegate> *_delegate;
    BaseVc *_nrVc;
    RestRecomListDTO *_dto;
    NSMutableArray *_panelPoolList;
}

@property(retain, nonatomic) NSMutableArray *panelPoolList; // @synthesize panelPoolList=_panelPoolList;
@property(retain, nonatomic) RestRecomListDTO *dto; // @synthesize dto=_dto;
@property BaseVc *nrVc; // @synthesize nrVc=_nrVc;
@property NSObject<CSRrWaterfallPanelDelegate> *delegate; // @synthesize delegate=_delegate;
- (void)createPanelPool:(long long)arg1;
- (id)newNeedShowDataListWithTop:(int)arg1 height:(int)arg2;
- (void)onRrWaterfallCellClicked:(id)arg1;
- (void)clear;
- (void)arrangePanelWithTableView:(id)arg1;
- (void)show:(id)arg1 tableView:(id)arg2;
- (void)dealloc;
- (id)initWithVc:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

