//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, UIColor;

@interface CSStyleTextInfo : NSObject
{
    NSString *text;
    double textSize;
    UIColor *textColor;
    int textDecoration;
    int textWeight;
}

@property int textWeight; // @synthesize textWeight;
@property int textDecoration; // @synthesize textDecoration;
@property(retain, nonatomic) UIColor *textColor; // @synthesize textColor;
@property(nonatomic) double textSize; // @synthesize textSize;
@property(retain, nonatomic) NSString *text; // @synthesize text;
- (void)dealloc;
- (id)init;

@end

