//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@interface CSStyleLabel : UIView
{
    long long lineBreakMode;
    int horizontalAlignment;
    int verticalAlignment;
}

@property(nonatomic) int verticalAlignment; // @synthesize verticalAlignment;
@property(nonatomic) int horizontalAlignment; // @synthesize horizontalAlignment;
@property(nonatomic) long long lineBreakMode; // @synthesize lineBreakMode;
- (float)estimateTotalWidth;
- (void)resetLabelByTag:(int)arg1;
- (void)alignSubviewsToRight;
- (void)alignSubviewsToLeft;
- (void)refit;
- (void)refreshWithTexts:(id)arg1;
- (void)installTextStyleInfos:(id)arg1;
- (void)dealloc;
- (void)loadDefaultSetting;
- (id)initWithFrame:(struct CGRect)arg1;

@end

