//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class BaseVc, CSRfStar, CSTkColorLabel, CSUIImageView, NSObject<CSTkListCellDelegate>, UIImageView, UILabel;

@interface CSTkListCell : UIView
{
    NSObject<CSTkListCellDelegate> *_delegate;
    BaseVc *_nrVc;
    CSUIImageView *_ctrlImg;
    UILabel *_ctrlTitle;
    CSTkColorLabel *_ctrlDiscountIcon;
    CSTkColorLabel *_ctrlPayIcon;
    CSRfStar *_ctrlStar;
    CSTkColorLabel *_ctrlState;
    UILabel *_ctrlLimitPrice;
    UILabel *_ctrlReachMins;
    UIImageView *_ctrlDistanceIcon;
    UILabel *_ctrlDistanceMeter;
}

+ (int)cellHeight;
@property(retain, nonatomic) UILabel *ctrlDistanceMeter; // @synthesize ctrlDistanceMeter=_ctrlDistanceMeter;
@property(retain, nonatomic) UIImageView *ctrlDistanceIcon; // @synthesize ctrlDistanceIcon=_ctrlDistanceIcon;
@property(retain, nonatomic) UILabel *ctrlReachMins; // @synthesize ctrlReachMins=_ctrlReachMins;
@property(retain, nonatomic) UILabel *ctrlLimitPrice; // @synthesize ctrlLimitPrice=_ctrlLimitPrice;
@property(retain, nonatomic) CSTkColorLabel *ctrlState; // @synthesize ctrlState=_ctrlState;
@property(retain, nonatomic) CSRfStar *ctrlStar; // @synthesize ctrlStar=_ctrlStar;
@property(retain, nonatomic) CSTkColorLabel *ctrlPayIcon; // @synthesize ctrlPayIcon=_ctrlPayIcon;
@property(retain, nonatomic) CSTkColorLabel *ctrlDiscountIcon; // @synthesize ctrlDiscountIcon=_ctrlDiscountIcon;
@property(retain, nonatomic) UILabel *ctrlTitle; // @synthesize ctrlTitle=_ctrlTitle;
@property(retain, nonatomic) CSUIImageView *ctrlImg; // @synthesize ctrlImg=_ctrlImg;
@property BaseVc *nrVc; // @synthesize nrVc=_nrVc;
@property NSObject<CSTkListCellDelegate> *delegate; // @synthesize delegate=_delegate;
- (id)newGrayLabelWithFrame:(struct CGRect)arg1;
- (void)refreshWithData:(id)arg1;
- (void)dealloc;
- (id)initWithVc:(id)arg1;

@end

