//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BaseView.h"

#import "CSZyLocNameFindDelegate.h"

@class CSZyLocNameFind, NSObject<CSTkTopPanelDelegate>, TkListParams, UIActivityIndicatorView, UIButton;

@interface CSTkTopPanel : BaseView <CSZyLocNameFindDelegate>
{
    _Bool _needReceiveMsgTag;
    NSObject<CSTkTopPanelDelegate> *_delegate;
    TkListParams *_nrPm;
    UIActivityIndicatorView *_ctrlAi;
    UIButton *_ctrlBtn;
    CSZyLocNameFind *_ctrlLocNameFind;
}

@property(nonatomic) _Bool needReceiveMsgTag; // @synthesize needReceiveMsgTag=_needReceiveMsgTag;
@property(retain, nonatomic) CSZyLocNameFind *ctrlLocNameFind; // @synthesize ctrlLocNameFind=_ctrlLocNameFind;
@property(retain, nonatomic) UIButton *ctrlBtn; // @synthesize ctrlBtn=_ctrlBtn;
@property(retain, nonatomic) UIActivityIndicatorView *ctrlAi; // @synthesize ctrlAi=_ctrlAi;
@property TkListParams *nrPm; // @synthesize nrPm=_nrPm;
@property NSObject<CSTkTopPanelDelegate> *delegate; // @synthesize delegate=_delegate;
- (void)changeAddress:(id)arg1;
- (void)onPageShowAfterWaiting:(id)arg1;
- (void)receivingMsgTkTopPanelUpdateAddressListener:(id)arg1;
- (void)selectLocBtnClicked;
- (void)onLocNameFindUpdateAddr:(id)arg1 success:(_Bool)arg2;
- (void)openLocSelectPage;
- (void)waitGpsThenDoTimer:(id)arg1;
- (void)waitGpsThenDo;
- (void)refreshWithNeedFind:(_Bool)arg1 address:(id)arg2;
- (void)showIndicator;
- (void)reset;
- (void)dealloc;
- (id)initWithVc:(id)arg1 params:(id)arg2;

@end

