//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class BaseBizVc, NSObject<CSTkMdFavPanelDelegate>, UIButton;

@interface CSTkMdFavPanel : UIView
{
    NSObject<CSTkMdFavPanelDelegate> *_delegate;
    BaseBizVc *_nrVc;
    UIButton *_ctrlFavBtn;
}

@property(retain, nonatomic) UIButton *ctrlFavBtn; // @synthesize ctrlFavBtn=_ctrlFavBtn;
@property BaseBizVc *nrVc; // @synthesize nrVc=_nrVc;
@property NSObject<CSTkMdFavPanelDelegate> *delegate; // @synthesize delegate=_delegate;
- (void)refreshWithFavTag:(_Bool)arg1 needAnime:(_Bool)arg2;
- (void)favBtnClicked;
- (void)refreshWithAnime:(id)arg1;
- (void)refresh:(id)arg1;
- (void)reset;
- (void)dealloc;
- (id)initWithVc:(id)arg1;

@end

