//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class BaseBizVc, NSObject<CSTkRecvAddrListCellDelegate>, UIButton, UIImageView, UILabel, UserTkRaData;

@interface CSTkRecvAddrListCell : UIView
{
    NSObject<CSTkRecvAddrListCellDelegate> *_delegate;
    BaseBizVc *_nrVc;
    UIImageView *_ctrlIcon;
    UILabel *_ctrlAddr;
    UIView *_ctrlPanel;
    UILabel *_ctrlTel;
    UILabel *_ctrlName;
    UIButton *_ctrlEditBtn;
    UIButton *_ctrlDelBtn;
    UserTkRaData *_data;
}

+ (float)calDetailWidth;
+ (float)calAddrHeight:(id)arg1;
+ (float)cellHeightWithDataForOrderDetail:(id)arg1;
+ (float)cellHeightWithData:(id)arg1;
@property(retain, nonatomic) UserTkRaData *data; // @synthesize data=_data;
@property(retain, nonatomic) UIButton *ctrlDelBtn; // @synthesize ctrlDelBtn=_ctrlDelBtn;
@property(retain, nonatomic) UIButton *ctrlEditBtn; // @synthesize ctrlEditBtn=_ctrlEditBtn;
@property(retain, nonatomic) UILabel *ctrlName; // @synthesize ctrlName=_ctrlName;
@property(retain, nonatomic) UILabel *ctrlTel; // @synthesize ctrlTel=_ctrlTel;
@property(retain, nonatomic) UIView *ctrlPanel; // @synthesize ctrlPanel=_ctrlPanel;
@property(retain, nonatomic) UILabel *ctrlAddr; // @synthesize ctrlAddr=_ctrlAddr;
@property(retain, nonatomic) UIImageView *ctrlIcon; // @synthesize ctrlIcon=_ctrlIcon;
@property BaseBizVc *nrVc; // @synthesize nrVc=_nrVc;
@property NSObject<CSTkRecvAddrListCellDelegate> *delegate; // @synthesize delegate=_delegate;
- (id)newTextWithTop:(float)arg1;
- (id)newLabelWithTop:(float)arg1 title:(id)arg2;
- (void)delBtnClicked;
- (void)editBtnClicked;
- (void)refreshWithDataForOrderDetail:(id)arg1;
- (void)refreshWithData:(id)arg1 selId:(id)arg2;
- (void)dealloc;
- (id)initWithVc:(id)arg1;

@end

