//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@protocol CSTkAddrAddPanelDelegate <NSObject>
- (void)onTkAddrAddPanelEditWithUuid:(NSString *)arg1 address:(NSString *)arg2 tel:(NSString *)arg3 name:(NSString *)arg4;
- (void)onTkAddrAddPanelAddWithAddress:(NSString *)arg1 tel:(NSString *)arg2 name:(NSString *)arg3;
@end

