//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class BaseBizVc, NSObject<CSTmlBuyNumDelegate>, UILabel;

@interface CSTmlBuyNum : UIView
{
    NSObject<CSTmlBuyNumDelegate> *_delegate;
    BaseBizVc *_nrVc;
    UILabel *_ctrlNumLabel;
}

@property(retain, nonatomic) UILabel *ctrlNumLabel; // @synthesize ctrlNumLabel=_ctrlNumLabel;
@property BaseBizVc *nrVc; // @synthesize nrVc=_nrVc;
@property NSObject<CSTmlBuyNumDelegate> *delegate; // @synthesize delegate=_delegate;
- (void)refreshWithData:(id)arg1;
- (void)dealloc;
- (id)initWithVc:(id)arg1 pos:(struct CGPoint)arg2;

@end

