//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class BaseBizVc, NSObject<CSTmlHeaderDelegate>, NSString, UIButton, UILabel;

@interface CSTmlHeader : UIView
{
    NSObject<CSTmlHeaderDelegate> *_delegate;
    BaseBizVc *_nrVc;
    UILabel *_ctrlTitleLabel;
    UIButton *_ctrlBtn;
    NSString *_title;
}

+ (float)headerHeightWithTitle:(id)arg1;
@property(retain, nonatomic) NSString *title; // @synthesize title=_title;
@property(retain, nonatomic) UIButton *ctrlBtn; // @synthesize ctrlBtn=_ctrlBtn;
@property(retain, nonatomic) UILabel *ctrlTitleLabel; // @synthesize ctrlTitleLabel=_ctrlTitleLabel;
@property BaseBizVc *nrVc; // @synthesize nrVc=_nrVc;
@property NSObject<CSTmlHeaderDelegate> *delegate; // @synthesize delegate=_delegate;
- (void)btnClicked;
- (void)refreshWithTitle:(id)arg1;
- (void)dealloc;
- (id)initWithVc:(id)arg1 width:(float)arg2;

@end

