//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class BaseBizVc, CSHtmLabel, CSUIButton, NSObject<CSTmlBtnPanelDelegate>, UIImageView, UILabel;

@interface CSTmlBtnPanel : UIView
{
    NSObject<CSTmlBtnPanelDelegate> *_delegate;
    BaseBizVc *_nrVc;
    UIImageView *_ctrlCartIcon;
    CSHtmLabel *_ctrlLeftHintLabel;
    UILabel *_ctrlRightHintLabel;
    CSUIButton *_ctrlOrderBtn;
}

@property(retain, nonatomic) CSUIButton *ctrlOrderBtn; // @synthesize ctrlOrderBtn=_ctrlOrderBtn;
@property(retain, nonatomic) UILabel *ctrlRightHintLabel; // @synthesize ctrlRightHintLabel=_ctrlRightHintLabel;
@property(retain, nonatomic) CSHtmLabel *ctrlLeftHintLabel; // @synthesize ctrlLeftHintLabel=_ctrlLeftHintLabel;
@property(retain, nonatomic) UIImageView *ctrlCartIcon; // @synthesize ctrlCartIcon=_ctrlCartIcon;
@property BaseBizVc *nrVc; // @synthesize nrVc=_nrVc;
@property NSObject<CSTmlBtnPanelDelegate> *delegate; // @synthesize delegate=_delegate;
- (void)changeLeftHintWithNum:(long long)arg1 price:(double)arg2;
- (void)btnClick;
- (void)refreshPanel:(id)arg1;
- (void)reset;
- (void)dealloc;
- (id)initWithVc:(id)arg1 height:(float)arg2;

@end

