//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class BaseBizVc, CSHtmLabel, NSObject<CSTodNotePanelDelegate>;

@interface CSTodNotePanel : UIView
{
    NSObject<CSTodNotePanelDelegate> *_delegate;
    BaseBizVc *_nrVc;
    CSHtmLabel *_ctrlTitleLabel;
    UIView *_ctrlLine;
}

@property(retain, nonatomic) UIView *ctrlLine; // @synthesize ctrlLine=_ctrlLine;
@property(retain, nonatomic) CSHtmLabel *ctrlTitleLabel; // @synthesize ctrlTitleLabel=_ctrlTitleLabel;
@property BaseBizVc *nrVc; // @synthesize nrVc=_nrVc;
@property NSObject<CSTodNotePanelDelegate> *delegate; // @synthesize delegate=_delegate;
- (void)refreshWithText:(id)arg1;
- (void)dealloc;
- (id)initWithVc:(id)arg1;

@end

