//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class CSUIButton, NSString;

@protocol CSTopSwitchDelegate <NSObject>
- (void)onTopSwitchBtnClicked:(CSUIButton *)arg1 btnIdx:(int)arg2 selectId:(NSString *)arg3;
@end

