//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIAlertView.h"

@class NSMutableDictionary;

@interface CSUIAlertView : UIAlertView
{
    NSMutableDictionary *dic;
}

@property(retain, nonatomic) NSMutableDictionary *dic; // @synthesize dic;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)init;

@end

