//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "CSImageDownloaderDelegate.h"

@class CSImageDownloader, NSMutableArray, NSMutableDictionary, NSObject<CSUIImageViewDelegate>, NSString, NSTimer, UIActivityIndicatorView, UIImageView;

@interface CSUIImageView : UIView <CSImageDownloaderDelegate>
{
    UIImageView *imageView;
    UIActivityIndicatorView *activityView;
    NSObject<CSUIImageViewDelegate> *_delegate;
    int delegateIsa;
    CSImageDownloader *downloader;
    NSString *failImgName;
    NSMutableDictionary *dic;
    _Bool animationShowTag;
    _Bool needScrollSupportTag;
    NSMutableArray *scrollIvList;
    NSTimer *scrollTimer;
}

@property(retain, nonatomic) NSTimer *scrollTimer; // @synthesize scrollTimer;
@property(retain, nonatomic) NSMutableArray *scrollIvList; // @synthesize scrollIvList;
@property(nonatomic) _Bool needScrollSupportTag; // @synthesize needScrollSupportTag;
@property(nonatomic) _Bool animationShowTag; // @synthesize animationShowTag;
@property(retain, nonatomic) NSMutableDictionary *dic; // @synthesize dic;
@property(retain, nonatomic) NSString *failImgName; // @synthesize failImgName;
@property(retain, nonatomic) CSImageDownloader *downloader; // @synthesize downloader;
@property(nonatomic) int delegateIsa; // @synthesize delegateIsa;
@property(retain, nonatomic) UIActivityIndicatorView *activityView; // @synthesize activityView;
@property(retain, nonatomic) UIImageView *imageView; // @synthesize imageView;
- (_Bool)isReallyCanScroll:(id)arg1;
- (void)invalidateScrollTimer;
- (void)scrollImage:(id)arg1;
- (void)startScrollTimer;
- (void)beginScrollImage:(id)arg1;
- (struct CGRect)calActivityViewFrame;
- (void)imageDownLoader:(id)arg1 finishWithImage:(id)arg2;
- (void)setImageWithDir:(id)arg1 maxFileNum:(int)arg2 url:(id)arg3 failImageName:(id)arg4 useSecondCache:(_Bool)arg5;
- (void)setImageWithDir:(id)arg1 maxFileNum:(int)arg2 url:(id)arg3 failImageName:(id)arg4;
- (void)setImageWithDir:(id)arg1 maxFileNum:(int)arg2 url:(id)arg3 useSecondCache:(_Bool)arg4;
- (void)setImageWithDir:(id)arg1 maxFileNum:(int)arg2 url:(id)arg3;
- (void)setImageWithUrl:(id)arg1;
- (void)setActivityIndicatorViewStyle:(long long)arg1;
- (void)cleanAndReset;
- (void)adjustFrame:(struct CGRect)arg1;
- (void)setDelegate:(id)arg1;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

@end

