//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "UIScrollViewDelegate.h"

@class BaseBizVc, NSObject<CSUIScrollBtnsDelegate>, NSString, UIColor, UIImage, UIImageView, UIScrollView;

@interface CSUIScrollBtns : UIView <UIScrollViewDelegate>
{
    NSObject<CSUIScrollBtnsDelegate> *_clickDelegate;
    BaseBizVc *_nrVc;
    UIScrollView *_ctrlScrollView;
    double _btnWidth;
    UIImageView *_ctrlLeftIndicator;
    UIImageView *_ctrlRightIndicator;
    UIImage *_img;
    UIImage *_imgHl;
    UIColor *_textColor;
    UIColor *_textColorHl;
}

@property(retain, nonatomic) UIColor *textColorHl; // @synthesize textColorHl=_textColorHl;
@property(retain, nonatomic) UIColor *textColor; // @synthesize textColor=_textColor;
@property(retain, nonatomic) UIImage *imgHl; // @synthesize imgHl=_imgHl;
@property(retain, nonatomic) UIImage *img; // @synthesize img=_img;
@property(retain, nonatomic) UIImageView *ctrlRightIndicator; // @synthesize ctrlRightIndicator=_ctrlRightIndicator;
@property(retain, nonatomic) UIImageView *ctrlLeftIndicator; // @synthesize ctrlLeftIndicator=_ctrlLeftIndicator;
@property(nonatomic) double btnWidth; // @synthesize btnWidth=_btnWidth;
@property(retain, nonatomic) UIScrollView *ctrlScrollView; // @synthesize ctrlScrollView=_ctrlScrollView;
@property(nonatomic) __weak BaseBizVc *nrVc; // @synthesize nrVc=_nrVc;
@property(nonatomic) __weak NSObject<CSUIScrollBtnsDelegate> *clickDelegate; // @synthesize clickDelegate=_clickDelegate;
- (void).cxx_destruct;
- (void)scrollViewDidScroll:(id)arg1;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)showRightIndicatorIfNecessary;
- (void)removePreviousBtns;
- (void)btnClicked:(id)arg1;
- (void)makeSelection:(id)arg1;
- (void)turnOffDateBtn:(id)arg1;
- (void)turnOnDateBtn:(id)arg1;
- (id)newDateBtn;
- (void)dealloc;
- (void)reset;
- (void)configBtnTextColor:(id)arg1 highlightColor:(id)arg2;
- (void)configBtnBg:(id)arg1 highlightBg:(id)arg2;
- (void)configBtnWidth:(double)arg1;
- (id)initWithFrame:(struct CGRect)arg1 vc:(id)arg2 showIndicator:(_Bool)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

