//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class CSUIComboBox, NSString;

@protocol CSUIComboBoxDelegate
- (void)comboBox:(CSUIComboBox *)arg1 didSelected:(long long)arg2 selectId:(NSString *)arg3 selectName:(NSString *)arg4;

@optional
- (void)comboBoxDidCancel:(CSUIComboBox *)arg1;
- (void)comboBox:(CSUIComboBox *)arg1 didSelectedWithLeftRow:(long long)arg2 leftSelectId:(NSString *)arg3 leftSelectName:(NSString *)arg4 rightRow:(long long)arg5 rightSelectId:(NSString *)arg6 rightSelectName:(NSString *)arg7;
- (void)comboBoxBeforeShowPicker:(CSUIComboBox *)arg1;
@end

