//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "CSUpdImgPanelDelegate.h"

@class BaseBizVc, NSObject<CSUpdImgListPanelDelegate>, NSString, ResFoodPicDataDTO;

@interface CSUpdImgListPanel : UIView <CSUpdImgPanelDelegate>
{
    NSObject<CSUpdImgListPanelDelegate> *_delegate;
    BaseBizVc *_nrVc;
    ResFoodPicDataDTO *_foodData;
}

@property(retain, nonatomic) ResFoodPicDataDTO *foodData; // @synthesize foodData=_foodData;
@property BaseBizVc *nrVc; // @synthesize nrVc=_nrVc;
@property NSObject<CSUpdImgListPanelDelegate> *delegate; // @synthesize delegate=_delegate;
- (void)onUpdImgPanelClickedWithIdx:(long long)arg1;
- (void)refreshWithList:(id)arg1 foodData:(id)arg2;
- (void)reset;
- (int)maxImgNum;
- (void)dealloc;
- (id)initWithVc:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

