//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class BaseVc, NSMutableArray, NSObject<CSUserRankPanelDelegate>;

@interface CSUserRankPanel : UIView
{
    NSObject<CSUserRankPanelDelegate> *_delegate;
    BaseVc *_nrVc;
    NSMutableArray *_iconList;
}

@property(retain, nonatomic) NSMutableArray *iconList; // @synthesize iconList=_iconList;
@property BaseVc *nrVc; // @synthesize nrVc=_nrVc;
@property NSObject<CSUserRankPanelDelegate> *delegate; // @synthesize delegate=_delegate;
- (void)showWithRank:(int)arg1 level:(int)arg2;
- (void)reset;
- (void)dealloc;
- (id)initWithPos:(struct CGPoint)arg1;

@end

