//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CSUIButton.h"

@class BaseBizVc, CSbubble, UIImageView, UILabel;

@interface CSXsUcFunBtnView : CSUIButton
{
    BaseBizVc *_nrVc;
    UIImageView *_ctrlIcon;
    UILabel *_ctrlTitle;
    CSbubble *_ctrlBubble;
}

+ (int)panelHeight;
@property(retain, nonatomic) CSbubble *ctrlBubble; // @synthesize ctrlBubble=_ctrlBubble;
@property(retain, nonatomic) UILabel *ctrlTitle; // @synthesize ctrlTitle=_ctrlTitle;
@property(retain, nonatomic) UIImageView *ctrlIcon; // @synthesize ctrlIcon=_ctrlIcon;
@property BaseBizVc *nrVc; // @synthesize nrVc=_nrVc;
- (void)refreshWithIcon:(id)arg1 andTitle:(id)arg2;
- (void)refreshWithIcon:(id)arg1 andTitle:(id)arg2 andBubble:(int)arg3;
- (void)dealloc;
- (id)initWithVc:(id)arg1;

@end

