//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "CSPickBtnDelegate.h"

@class BaseBizVc, CSPickBtn, NSMutableArray, NSObject<CSXsRriSelBtnDelegate>, NSString;

@interface CSXsRriSelBtn : NSObject <CSPickBtnDelegate>
{
    NSObject<CSXsRriSelBtnDelegate> *_delegate;
    BaseBizVc *_nrVc;
    CSPickBtn *_ctrlBtn;
    NSString *_districtId;
    NSMutableArray *_list;
}

@property(retain, nonatomic) NSMutableArray *list; // @synthesize list=_list;
@property(retain, nonatomic) NSString *districtId; // @synthesize districtId=_districtId;
@property(retain, nonatomic) CSPickBtn *ctrlBtn; // @synthesize ctrlBtn=_ctrlBtn;
@property BaseBizVc *nrVc; // @synthesize nrVc=_nrVc;
@property NSObject<CSXsRriSelBtnDelegate> *delegate; // @synthesize delegate=_delegate;
- (void)pickBtn:(id)arg1 leftSelectRow:(long long)arg2 leftSelectId:(id)arg3 leftSelectName:(id)arg4 rightSelectRow:(long long)arg5 rightSelectId:(id)arg6 rightSelectName:(id)arg7;
- (void)pickBtnBeforeShowPicker:(id)arg1;
- (void)refreshWithList:(id)arg1;
- (void)reset;
- (void)dealloc;
- (id)initWithVc:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

