//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class UIImageView, UITextField;

@interface CSZyInput : UIView
{
    UIImageView *_ctrlBg;
    UITextField *_tf;
}

@property(retain, nonatomic) UITextField *tf; // @synthesize tf=_tf;
@property(retain, nonatomic) UIImageView *ctrlBg; // @synthesize ctrlBg=_ctrlBg;
- (void)adjustFrame:(struct CGRect)arg1;
- (_Bool)resignFirstResponder;
- (_Bool)becomeFirstResponder;
- (void)canEdit:(_Bool)arg1;
- (id)text;
- (void)setText:(id)arg1;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

@end

