//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "CSZyDishListCellViewDelegate.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class BaseVc, DishListPackDTO, NSObject<CSZyDishListDelegate>, NSString, UITableView;

@interface CSZyDishList : UIView <UITableViewDelegate, UITableViewDataSource, CSZyDishListCellViewDelegate>
{
    NSObject<CSZyDishListDelegate> *_delegate;
    BaseVc *_nrVc;
    UITableView *_ctrlDishesTable;
    DishListPackDTO *_dto;
    long long _categoryRow;
}

@property(nonatomic) long long categoryRow; // @synthesize categoryRow=_categoryRow;
@property(retain, nonatomic) DishListPackDTO *dto; // @synthesize dto=_dto;
@property(retain, nonatomic) UITableView *ctrlDishesTable; // @synthesize ctrlDishesTable=_ctrlDishesTable;
@property BaseVc *nrVc; // @synthesize nrVc=_nrVc;
@property NSObject<CSZyDishListDelegate> *delegate; // @synthesize delegate=_delegate;
- (void)onDishListCellView:(id)arg1 dishData:(id)arg2 valueChangedTo:(long long)arg3 fromValue:(long long)arg4;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(_Bool)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (void)open;
- (void)refresh:(id)arg1 forCategoryRow:(long long)arg2 toTop:(_Bool)arg3;
- (void)refreshNotToTop:(id)arg1 forCategoryRow:(long long)arg2;
- (void)refresh:(id)arg1 forCategoryRow:(long long)arg2;
- (void)reset;
- (void)dealloc;
- (id)initWithVc:(id)arg1 withHeight:(double)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

