//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class UILabel, UITextField;

@interface CSZyLabelInput : UIView
{
    UILabel *_lbl;
    UITextField *_tf;
}

@property(retain, nonatomic) UITextField *tf; // @synthesize tf=_tf;
@property(retain, nonatomic) UILabel *lbl; // @synthesize lbl=_lbl;
- (_Bool)resignFirstResponder;
- (_Bool)becomeFirstResponder;
- (id)text;
- (void)setText:(id)arg1;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1 labelText:(id)arg2 textPlaceholder:(id)arg3;

@end

