//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface FileUtil : NSObject
{
}

+ (_Bool)unZip:(id)arg1 pwd:(id)arg2;
+ (_Bool)unZip:(id)arg1;
+ (_Bool)chkZipIsEncrypted:(id)arg1;
+ (void)delFile:(id)arg1;
+ (id)parentPathByPath:(id)arg1;
+ (int)fileNumWithFolderPath:(id)arg1;
+ (id)completePathByPath:(id)arg1;
+ (id)filePathWithFolderPath:(id)arg1 fileName:(id)arg2;
+ (id)generateToPathWithFromFilePath:(id)arg1 toFolderPath:(id)arg2 fileName:(id)arg3;
+ (void)copyFileFromFilePath:(id)arg1 toFolderPath:(id)arg2 fileName:(id)arg3;
+ (void)copyFileFromFilePath:(id)arg1 toFolderPath:(id)arg2;
+ (void)moveFileFromFilePath:(id)arg1 toFolderPath:(id)arg2 fileName:(id)arg3;
+ (unsigned long long)folderSize:(id)arg1;
+ (id)fileSizeFmtStr:(int)arg1;
+ (_Bool)chkFileExist:(id)arg1;
+ (void)createPath:(id)arg1;
+ (id)documentSubPath:(id)arg1;
+ (_Bool)addSkipBackupAttributeToItemAtURL:(id)arg1;
+ (void)addSkipBackupAttributeWithPath:(id)arg1;
+ (id)tmpPathWithDir:(id)arg1;
+ (id)tmpPath;

@end

