//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface FoodRestListData : NSObject
{
    NSString *_foodId;
    NSString *_foodName;
    NSString *_foodHotNum;
    NSString *_nowPrice;
    NSString *_oldPrice;
    NSString *_restId;
    NSString *_restName;
    NSString *_restPicUrl;
    NSString *_districtName;
    NSString *_distance;
}

@property(retain, nonatomic) NSString *distance; // @synthesize distance=_distance;
@property(retain, nonatomic) NSString *districtName; // @synthesize districtName=_districtName;
@property(retain, nonatomic) NSString *restPicUrl; // @synthesize restPicUrl=_restPicUrl;
@property(retain, nonatomic) NSString *restName; // @synthesize restName=_restName;
@property(retain, nonatomic) NSString *restId; // @synthesize restId=_restId;
@property(retain, nonatomic) NSString *oldPrice; // @synthesize oldPrice=_oldPrice;
@property(retain, nonatomic) NSString *nowPrice; // @synthesize nowPrice=_nowPrice;
@property(retain, nonatomic) NSString *foodHotNum; // @synthesize foodHotNum=_foodHotNum;
@property(retain, nonatomic) NSString *foodName; // @synthesize foodName=_foodName;
@property(retain, nonatomic) NSString *foodId; // @synthesize foodId=_foodId;
- (void)dealloc;
- (id)initWithObj:(id)arg1;

@end

