//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface FuncStateData : NSObject
{
    _Bool btn1Tag;
    _Bool btn2Tag;
    _Bool btn3Tag;
    _Bool btn4Tag;
    _Bool btn5Tag;
    _Bool btn6Tag;
    _Bool btn7Tag;
    _Bool btn8Tag;
    _Bool btn9Tag;
    int orderNum;
    int mailNum;
    int sumNum;
}

@property(nonatomic) int sumNum; // @synthesize sumNum;
@property(nonatomic) int mailNum; // @synthesize mailNum;
@property(nonatomic) int orderNum; // @synthesize orderNum;
@property(nonatomic) _Bool btn9Tag; // @synthesize btn9Tag;
@property(nonatomic) _Bool btn8Tag; // @synthesize btn8Tag;
@property(nonatomic) _Bool btn7Tag; // @synthesize btn7Tag;
@property(nonatomic) _Bool btn6Tag; // @synthesize btn6Tag;
@property(nonatomic) _Bool btn5Tag; // @synthesize btn5Tag;
@property(nonatomic) _Bool btn4Tag; // @synthesize btn4Tag;
@property(nonatomic) _Bool btn3Tag; // @synthesize btn3Tag;
@property(nonatomic) _Bool btn2Tag; // @synthesize btn2Tag;
@property(nonatomic) _Bool btn1Tag; // @synthesize btn1Tag;
- (void)changeNumWithMailNum:(int)arg1;
- (void)changeNumWithOrderNum:(int)arg1;
- (void)changeNumWithOrderNum:(int)arg1 mailNum:(int)arg2;
- (void)dealloc;
- (id)init;

@end

