//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class AppCfgData, FuncStateData, NSDate, NSString, PushMsgDTO, UserInfoDto;

@interface Global : NSObject
{
    _Bool _mkHaveGpsTag;
    double mkLon;
    double mkLat;
    NSDate *mkGpsDate;
    _Bool _lmHaveGpsTag;
    double lmLon;
    double lmLat;
    NSDate *lmGpsDate;
    double _lastLonForCache;
    double _lastLatForCache;
    NSString *cityId;
    NSString *cityName;
    NSString *phone;
    double cityLon;
    double cityLat;
    NSString *lastGpsCityId;
    FuncStateData *funcState;
    UserInfoDto *userInfo;
    _Bool appFirstOpenTag;
    NSString *deviceNumberStr;
    NSString *deviceType;
    NSString *macAddress;
    float iosVersion;
    long long runCount;
    int screenTop;
    _Bool isIos7Tag;
    _Bool isShowRestAndFoodImagesTag;
    _Bool needProcessPushMsgTag;
    PushMsgDTO *pushMsg;
    _Bool needProcessAppSchemeUrlTag;
    NSString *xmsUrl;
    _Bool haveAppIconBadgeTag;
    int normalRequestTimeout;
    int uploadRequestTimeout;
    NSString *timeDiff;
    AppCfgData *cfgData;
    _Bool isIphone5Tag;
    _Bool onPageNavingTag;
    NSString *appSchemeUrl;
}

+ (id)instance;
@property(nonatomic) _Bool onPageNavingTag; // @synthesize onPageNavingTag;
@property(nonatomic) _Bool isIphone5Tag; // @synthesize isIphone5Tag;
@property(retain, nonatomic) AppCfgData *cfgData; // @synthesize cfgData;
@property(nonatomic) _Bool haveAppIconBadgeTag; // @synthesize haveAppIconBadgeTag;
@property(retain, nonatomic) NSString *appSchemeUrl; // @synthesize appSchemeUrl;
@property(nonatomic) _Bool needProcessAppSchemeUrlTag; // @synthesize needProcessAppSchemeUrlTag;
@property(retain, nonatomic) PushMsgDTO *pushMsg; // @synthesize pushMsg;
@property(nonatomic) _Bool needProcessPushMsgTag; // @synthesize needProcessPushMsgTag;
@property(nonatomic) _Bool isShowRestAndFoodImagesTag; // @synthesize isShowRestAndFoodImagesTag;
@property(nonatomic) _Bool isIos7Tag; // @synthesize isIos7Tag;
@property(nonatomic) int screenTop; // @synthesize screenTop;
@property(nonatomic) long long runCount; // @synthesize runCount;
@property float iosVersion; // @synthesize iosVersion;
@property(retain, nonatomic) NSString *macAddress; // @synthesize macAddress;
@property(retain, nonatomic) NSString *deviceType; // @synthesize deviceType;
@property(retain, nonatomic) NSString *deviceNumberStr; // @synthesize deviceNumberStr;
@property(nonatomic) _Bool appFirstOpenTag; // @synthesize appFirstOpenTag;
@property(retain, nonatomic) UserInfoDto *userInfo; // @synthesize userInfo;
@property(retain, nonatomic) FuncStateData *funcState; // @synthesize funcState;
@property(retain, nonatomic) NSString *lastGpsCityId; // @synthesize lastGpsCityId;
@property(nonatomic) double cityLat; // @synthesize cityLat;
@property(nonatomic) double cityLon; // @synthesize cityLon;
@property(retain, nonatomic) NSString *phone; // @synthesize phone;
@property(retain, nonatomic) NSString *cityName; // @synthesize cityName;
@property(retain, nonatomic) NSString *cityId; // @synthesize cityId;
@property(nonatomic) double _lastLatForCache; // @synthesize _lastLatForCache;
@property(nonatomic) double _lastLonForCache; // @synthesize _lastLonForCache;
@property(retain, nonatomic) NSDate *lmGpsDate; // @synthesize lmGpsDate;
@property(nonatomic) double lmLat; // @synthesize lmLat;
@property(nonatomic) double lmLon; // @synthesize lmLon;
@property(nonatomic) _Bool _lmHaveGpsTag; // @synthesize _lmHaveGpsTag;
@property(retain, nonatomic) NSDate *mkGpsDate; // @synthesize mkGpsDate;
@property(nonatomic) double mkLat; // @synthesize mkLat;
@property(nonatomic) double mkLon; // @synthesize mkLon;
@property(nonatomic) _Bool _mkHaveGpsTag; // @synthesize _mkHaveGpsTag;
- (void)_configFuncState;
- (void)_incrementRunCountOfCache;
- (void)_setFirstOpenByCache;
- (id)_deviceTypeName;
- (_Bool)is57Call;
- (void)_loadIsShowRestAndFoodImageFromCache;
- (void)setIsShowRestAndFoodImagesTagToCache:(_Bool)arg1;
- (void)_setGlobalLoginInfoFromCache;
- (void)logout;
- (void)completeSuccessLoginOrReg:(id)arg1;
- (void)_setDefaultCityInfo;
- (void)_loadCityInfoFromCache;
- (void)cleanCurrentGpsForCityQuery;
- (void)saveCurrentGpsForCityQuery:(id)arg1;
- (_Bool)chkIsNeedQueryCity;
- (void)setCityInfoWithCityId:(id)arg1 cityName:(id)arg2 phone:(id)arg3;
- (int)_formatLongLat:(double)arg1;
- (id)lonLatForCache;
- (double)lat;
- (double)lon;
- (_Bool)haveLmGpsTag;
- (_Bool)haveMkGpsTag;
- (_Bool)haveGpsTag;
- (void)setMkGpsInfoWithLon:(double)arg1 lat:(double)arg2;
- (void)setLmGpsInfoWithLon:(double)arg1 lat:(double)arg2;
- (void)_saveQqBindToUserInfo:(_Bool)arg1 secs:(int)arg2;
- (void)_saveSinaBindToUserInfo:(_Bool)arg1 secs:(int)arg2;
- (void)cleanQqBind;
- (void)cleanSinaBind;
- (void)saveQqBind:(int)arg1;
- (void)saveSinaBind:(int)arg1;
- (_Bool)chkQqBindIsExpired;
- (_Bool)chkSinaBindIsExpired;
- (_Bool)chkIsBindQq;
- (_Bool)chkIsBindSina;
- (void)dealloc;
- (id)init;

@end

