//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class IFlySpeechError, NSArray;

@protocol IFlySpeechRecognizerDelegate <NSObject>
- (void)onResults:(NSArray *)arg1;
- (void)onError:(IFlySpeechError *)arg1;

@optional
- (void)onCancel;
- (void)onEndOfSpeech;
- (void)onBeginOfSpeech;
- (void)onVolumeChanged:(int)arg1;
@end

