//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@protocol IFlyAudioPlayerDelegate
- (void)onBufferPrecent:(int)arg1;
- (void)onBuffer;
- (void)onPlay;
- (void)onResume;
- (void)onPaused;
- (void)onStop:(int)arg1;
@end

