//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "IFlySpeechRecognizerDelegate.h"

@class IFlyMscRecognizer;

@interface IFlySpeechRecognizer : NSObject <IFlySpeechRecognizerDelegate>
{
    IFlyMscRecognizer *_mscer;
    id <IFlySpeechRecognizerDelegate> _delegate;
}

+ (id)shareInstance;
+ (id)getRecognizer;
+ (id)createRecognizer:(id)arg1 delegate:(id)arg2;
@property id <IFlySpeechRecognizerDelegate> delegate; // @synthesize delegate=_delegate;
- (void)onCancel;
- (void)onError:(id)arg1;
- (void)onResults:(id)arg1;
- (void)onVolumeChanged:(int)arg1;
- (void)onEndOfSpeech;
- (void)onBeginOfSpeech;
- (void)end:(id)arg1;
- (void)isCancel;
- (void)results:(id)arg1;
- (void)endOfSpeech;
- (void)beginOfSpeech;
- (void)refreashVolume:(id)arg1;
- (_Bool)isAvaible;
- (id)initWithParams:(id)arg1 delegate:(id)arg2;
- (void)cancel;
- (void)stopListening;
- (_Bool)writeAudio:(id)arg1;
- (_Bool)recognizeAudioStream;
- (_Bool)recognizeStream;
- (_Bool)startListening:(id)arg1 grammar:(id)arg2;
- (_Bool)startListening;
- (_Bool)setParameter:(id)arg1 value:(id)arg2;
- (void)dealloc;

@end

