//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface IRecorder : NSObject
{
    id <IRecorderDelegate> delegate;
}

@property(nonatomic) id <IRecorderDelegate> delegate; // @synthesize delegate;
- (_Bool)isRecording;
- (void)reset;
- (int)stop;
- (int)startRecord:(id)arg1;

@end

