//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ResParams.h"

@class NSString;

@interface LocalGrammarParams : ResParams
{
    NSString *mOutputName;
}

- (void).cxx_destruct;
- (id)getOutputPath;
- (int)setOutputPath:(id)arg1;
- (id)getEbnf;
- (int)setEbnf:(id)arg1;
- (id)init;

@end

