//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "AiCommonConfig.h"

@class NSString;

@interface LocalBaseConfig : AiCommonConfig
{
    NSString *modName;
}

@property(retain, nonatomic) NSString *modName; // @synthesize modName;
- (void).cxx_destruct;
- (id)getResBinFilePath;
- (int)setResBinFilePath:(id)arg1;
- (id)getNetBinFilePath;
- (int)setNetBinFilePath:(id)arg1;

@end

