//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "LocalBaseConfig.h"

@interface LocalWakeupConfig : LocalBaseConfig
{
    _Bool _stopRecorderAudioOnWakeUp;
}

- (id)getUseWavCache;
- (int)setUseWavCache:(id)arg1;
- (id)getWakeupRetMode;
- (int)setWakeupRetMode:(id)arg1;
- (id)getSampleRate;
- (int)setSampleRate:(id)arg1;
- (_Bool)isStopRecorderOnWakeUpSuccess;
- (void)setStopRecorderOnWakeUpSuccess:(_Bool)arg1;
- (id)init;

@end

