//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface MainPageAdvData : NSObject
{
    NSString *uuid;
    int typeTag;
    NSString *title;
    NSString *advUrl;
    double endDate;
    NSString *picUrl;
    NSString *appName;
    NSString *appDownloadUrl;
}

@property(retain, nonatomic) NSString *appDownloadUrl; // @synthesize appDownloadUrl;
@property(retain, nonatomic) NSString *appName; // @synthesize appName;
@property(retain, nonatomic) NSString *picUrl; // @synthesize picUrl;
@property(nonatomic) double endDate; // @synthesize endDate;
@property(retain, nonatomic) NSString *advUrl; // @synthesize advUrl;
@property(retain, nonatomic) NSString *title; // @synthesize title;
@property(nonatomic) int typeTag; // @synthesize typeTag;
@property(retain, nonatomic) NSString *uuid; // @synthesize uuid;
- (id)newDic;
- (id)newOne;
- (void)dealloc;
- (id)initWithObj:(id)arg1;

@end

