//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class MainPageMsgListDTO, NSMutableArray;

@interface MainPageInfoPack5DTO : NSObject
{
    int _nextQueryInterval;
    MainPageMsgListDTO *_mainPageMsgListDTO;
    NSMutableArray *_mainFuncBtnList;
    NSMutableArray *_secFuncBtnList;
    NSMutableArray *_extFuncBtnList;
    NSMutableArray *_restList;
}

@property(nonatomic) int nextQueryInterval; // @synthesize nextQueryInterval=_nextQueryInterval;
@property(retain, nonatomic) NSMutableArray *restList; // @synthesize restList=_restList;
@property(retain, nonatomic) NSMutableArray *extFuncBtnList; // @synthesize extFuncBtnList=_extFuncBtnList;
@property(retain, nonatomic) NSMutableArray *secFuncBtnList; // @synthesize secFuncBtnList=_secFuncBtnList;
@property(retain, nonatomic) NSMutableArray *mainFuncBtnList; // @synthesize mainFuncBtnList=_mainFuncBtnList;
@property(retain, nonatomic) MainPageMsgListDTO *mainPageMsgListDTO; // @synthesize mainPageMsgListDTO=_mainPageMsgListDTO;
- (void)unitTest;
- (void)dealloc;
- (id)initWithObj:(id)arg1;

@end

