//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BaseFormVc.h"

#import "CSFodFlowerPanelDelegate.h"
#import "CSFodUploadPicPanelDelegate.h"
#import "CSOdOperatePanelDelegate.h"
#import "CSOdTopPanelDelegate.h"

@class CSFodDrawPanel, CSFodFlowerPanel, CSFodSharePanel, CSFodUploadPicPanel, CSFodValidPanel, CSOdHintPanel, CSOdMoreInfoPanel, CSOdOperatePanel, CSOdTopPanel, MdbFreeOrderInfoData, NSString;

@interface MdbFreeOrderDetailVc : BaseFormVc <CSOdTopPanelDelegate, CSOdOperatePanelDelegate, CSFodFlowerPanelDelegate, CSFodUploadPicPanelDelegate>
{
    _Bool _onUploadPicTag;
    int _flowerNum;
    CSOdTopPanel *_ctrlTopPanel;
    CSOdMoreInfoPanel *_ctrlMoreInfoPanel;
    CSOdHintPanel *_ctrlFuncHintPanel;
    CSFodValidPanel *_ctrlValidPanel;
    CSFodFlowerPanel *_ctrlFlowerPanel;
    CSFodDrawPanel *_ctrlDrawPanel;
    CSFodUploadPicPanel *_ctrlUploadPanel;
    CSFodSharePanel *_ctrlSharePanel;
    CSOdOperatePanel *_ctrlOpPanel;
    NSString *_orderId;
    MdbFreeOrderInfoData *_dto;
    NSString *_returnPageKey;
}

@property(nonatomic) _Bool onUploadPicTag; // @synthesize onUploadPicTag=_onUploadPicTag;
@property(nonatomic) int flowerNum; // @synthesize flowerNum=_flowerNum;
@property(retain, nonatomic) NSString *returnPageKey; // @synthesize returnPageKey=_returnPageKey;
@property(retain, nonatomic) MdbFreeOrderInfoData *dto; // @synthesize dto=_dto;
@property(retain, nonatomic) NSString *orderId; // @synthesize orderId=_orderId;
@property(retain, nonatomic) CSOdOperatePanel *ctrlOpPanel; // @synthesize ctrlOpPanel=_ctrlOpPanel;
@property(retain, nonatomic) CSFodSharePanel *ctrlSharePanel; // @synthesize ctrlSharePanel=_ctrlSharePanel;
@property(retain, nonatomic) CSFodUploadPicPanel *ctrlUploadPanel; // @synthesize ctrlUploadPanel=_ctrlUploadPanel;
@property(retain, nonatomic) CSFodDrawPanel *ctrlDrawPanel; // @synthesize ctrlDrawPanel=_ctrlDrawPanel;
@property(retain, nonatomic) CSFodFlowerPanel *ctrlFlowerPanel; // @synthesize ctrlFlowerPanel=_ctrlFlowerPanel;
@property(retain, nonatomic) CSFodValidPanel *ctrlValidPanel; // @synthesize ctrlValidPanel=_ctrlValidPanel;
@property(retain, nonatomic) CSOdHintPanel *ctrlFuncHintPanel; // @synthesize ctrlFuncHintPanel=_ctrlFuncHintPanel;
@property(retain, nonatomic) CSOdMoreInfoPanel *ctrlMoreInfoPanel; // @synthesize ctrlMoreInfoPanel=_ctrlMoreInfoPanel;
@property(retain, nonatomic) CSOdTopPanel *ctrlTopPanel; // @synthesize ctrlTopPanel=_ctrlTopPanel;
- (void)stopRefreshCountDownTimer;
- (void)handleRefreshCountDown;
- (void)startRefreshCountDownTimer;
- (void)onOdOperatePanelEditBtnClick;
- (void)onOdOperatePanelCancelBtnClick;
- (void)finishPickPhotoWithDataList:(id)arg1;
- (void)onFodUploadPicPanelBtnClicked;
- (void)onFodFlowerPanelSelFlower:(int)arg1;
- (void)odTopPanelExpCosBtnClick:(_Bool)arg1;
- (void)alertView:(id)arg1 hideWithBtnIdx:(long long)arg2;
- (void)completeQueryParamsWithTag:(long long)arg1;
- (void)onHttpRequestFail:(long long)arg1 errorMsg:(id)arg2;
- (void)arrangePanelsWithExpTag:(_Bool)arg1;
- (void)onHttpRequestSuccess:(id)arg1 tag:(long long)arg2;
- (void)postDataForUploadPic:(id)arg1;
- (void)postDataForOrderFlower;
- (void)postDataForCancelOrder;
- (void)loadData;
- (void)topViewRightBtnClicked:(id)arg1;
- (void)topViewBackBtnClicked:(id)arg1;
- (void)onPopFromNavStack;
- (void)onHide;
- (void)onParseNavBackPageParams:(id)arg1;
- (void)onShow;
- (void)onWillShow;
- (void)onParsePageParams:(id)arg1;
- (void)onClose;
- (void)onCleanData;
- (void)onCreate;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

