//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray, NSString;

@interface MdbFopTransData : NSObject
{
    int _typeTag;
    NSMutableArray *_payTypeList;
    NSString *_orderId;
    NSString *_returnPageKey;
}

@property(retain, nonatomic) NSString *returnPageKey; // @synthesize returnPageKey=_returnPageKey;
@property(retain, nonatomic) NSString *orderId; // @synthesize orderId=_orderId;
@property(nonatomic) int typeTag; // @synthesize typeTag=_typeTag;
@property(retain, nonatomic) NSMutableArray *payTypeList; // @synthesize payTypeList=_payTypeList;
- (void)dealloc;
- (id)init;

@end

