//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray, NSString;

@interface MdbFreeOrderFormData : NSObject
{
    _Bool _canUseRemainMoneyTag;
    _Bool _showFlowerPanelTag;
    int _flowerNum;
    NSString *_restName;
    double _payMoney;
    NSString *_userTel;
    double _userRemainMoney;
    NSMutableArray *_payTypeList;
    NSString *_freePct;
    NSString *_freeNum;
    NSString *_freeMoney;
    NSMutableArray *_freeRecordList;
}

@property(retain, nonatomic) NSMutableArray *freeRecordList; // @synthesize freeRecordList=_freeRecordList;
@property(nonatomic) int flowerNum; // @synthesize flowerNum=_flowerNum;
@property(retain, nonatomic) NSString *freeMoney; // @synthesize freeMoney=_freeMoney;
@property(retain, nonatomic) NSString *freeNum; // @synthesize freeNum=_freeNum;
@property(retain, nonatomic) NSString *freePct; // @synthesize freePct=_freePct;
@property(nonatomic) _Bool showFlowerPanelTag; // @synthesize showFlowerPanelTag=_showFlowerPanelTag;
@property(retain, nonatomic) NSMutableArray *payTypeList; // @synthesize payTypeList=_payTypeList;
@property(nonatomic) double userRemainMoney; // @synthesize userRemainMoney=_userRemainMoney;
@property(nonatomic) _Bool canUseRemainMoneyTag; // @synthesize canUseRemainMoneyTag=_canUseRemainMoneyTag;
@property(retain, nonatomic) NSString *userTel; // @synthesize userTel=_userTel;
@property(nonatomic) double payMoney; // @synthesize payMoney=_payMoney;
@property(retain, nonatomic) NSString *restName; // @synthesize restName=_restName;
- (void)unitTest;
- (void)dealloc;
- (id)initWithObj:(id)arg1;

@end

