//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class BaseSingleListVc, MdbRestListDTO, NSString;

@interface MdbRlQueryParams : NSObject
{
    int _fromTag;
    int _rfSelBtnTag;
    BaseSingleListVc *_nrVc;
    NSString *_distanceMeter;
    NSString *_regionId;
    NSString *_districtId;
    NSString *_mainMenuId;
    NSString *_subMenuId;
    NSString *_sortTypeTag;
    NSString *_avgTag;
    MdbRestListDTO *_dto;
}

@property int rfSelBtnTag; // @synthesize rfSelBtnTag=_rfSelBtnTag;
@property(retain, nonatomic) MdbRestListDTO *dto; // @synthesize dto=_dto;
@property(retain, nonatomic) NSString *avgTag; // @synthesize avgTag=_avgTag;
@property(retain, nonatomic) NSString *sortTypeTag; // @synthesize sortTypeTag=_sortTypeTag;
@property(retain, nonatomic) NSString *subMenuId; // @synthesize subMenuId=_subMenuId;
@property(retain, nonatomic) NSString *mainMenuId; // @synthesize mainMenuId=_mainMenuId;
@property(retain, nonatomic) NSString *districtId; // @synthesize districtId=_districtId;
@property(retain, nonatomic) NSString *regionId; // @synthesize regionId=_regionId;
@property(retain, nonatomic) NSString *distanceMeter; // @synthesize distanceMeter=_distanceMeter;
@property(nonatomic) int fromTag; // @synthesize fromTag=_fromTag;
@property BaseSingleListVc *nrVc; // @synthesize nrVc=_nrVc;
- (void)completeQueryParams;
- (void)resetParams;
- (void)resetDto;
- (void)reset;
- (void)dealloc;
- (id)initWithVc:(id)arg1;

@end

