//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface MdbRlUtil : NSObject
{
}

+ (void)addToNearListWithMeter:(int)arg1 list:(id)arg2;
+ (id)newNearSelectList;
+ (void)addDataWithSelectId:(id)arg1 selectName:(id)arg2 toList:(id)arg3;
+ (void)addListDataWithSelectId:(id)arg1 selectName:(id)arg2 subList:(id)arg3 toList:(id)arg4 groupTag:(_Bool)arg5;
+ (void)addListDataWithSelectId:(id)arg1 selectName:(id)arg2 subList:(id)arg3 toList:(id)arg4;
+ (id)newGroupListWithList:(id)arg1 allName:(id)arg2;
+ (id)newPackWithList:(id)arg1 allName:(id)arg2 haveNearTag:(_Bool)arg3;
+ (id)s0;

@end

