//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BaseDto.h"

@class NSMutableArray, NSMutableDictionary, NSString;

@interface MdbRestListDTO : BaseDto
{
    NSMutableArray *_advList;
    NSMutableArray *_list;
    NSMutableArray *_regionList;
    NSMutableArray *_menuTypeList;
    NSMutableArray *_sortList;
    NSMutableArray *_avgList;
    NSString *_selectRegionName;
    NSString *_selectDistrictName;
    NSString *_selectMainMenuTypeName;
    NSString *_selectSubMenuTypeName;
    NSString *_selectSortName;
    NSMutableDictionary *_soObj;
}

@property(retain, nonatomic) NSMutableDictionary *soObj; // @synthesize soObj=_soObj;
@property(retain, nonatomic) NSString *selectSortName; // @synthesize selectSortName=_selectSortName;
@property(retain, nonatomic) NSString *selectSubMenuTypeName; // @synthesize selectSubMenuTypeName=_selectSubMenuTypeName;
@property(retain, nonatomic) NSString *selectMainMenuTypeName; // @synthesize selectMainMenuTypeName=_selectMainMenuTypeName;
@property(retain, nonatomic) NSString *selectDistrictName; // @synthesize selectDistrictName=_selectDistrictName;
@property(retain, nonatomic) NSString *selectRegionName; // @synthesize selectRegionName=_selectRegionName;
@property(retain, nonatomic) NSMutableArray *avgList; // @synthesize avgList=_avgList;
@property(retain, nonatomic) NSMutableArray *sortList; // @synthesize sortList=_sortList;
@property(retain, nonatomic) NSMutableArray *menuTypeList; // @synthesize menuTypeList=_menuTypeList;
@property(retain, nonatomic) NSMutableArray *regionList; // @synthesize regionList=_regionList;
@property(retain, nonatomic) NSMutableArray *list; // @synthesize list=_list;
@property(retain, nonatomic) NSMutableArray *advList; // @synthesize advList=_advList;
- (void)unitTest;
- (id)transByKey:(id)arg1 forList:(id)arg2 forRfTypeList:(_Bool)arg3;
- (id)readAvgList;
- (id)readSortList;
- (id)readMenuTypeList;
- (id)readRegionList;
- (void)appendDataWithObj:(id)arg1 startIndex:(long long)arg2;
- (void)dealloc;
- (id)initWithObj:(id)arg1;

@end

