//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BaseSingleListVc.h"

#import "CSMdbRlSelectPanelDelegate.h"
#import "CSXsTryLocDelegate.h"
#import "CurrentLocationPanelDelegate.h"

@class CSCurrentLocationPanel, CSMdbRlSelectPanel, CSPicAdvPanel, CSXsTryLoc, MdbRlQueryParams, NSString;

@interface MdbRestListVc : BaseSingleListVc <CSMdbRlSelectPanelDelegate, CurrentLocationPanelDelegate, CSXsTryLocDelegate>
{
    CSMdbRlSelectPanel *_ctrlSelectPanel;
    CSCurrentLocationPanel *_ctrlLocPanel;
    CSXsTryLoc *_ctrlTryLoc;
    CSPicAdvPanel *_ctrlAdvPanel;
    MdbRlQueryParams *_rfParams;
}

@property(retain, nonatomic) MdbRlQueryParams *rfParams; // @synthesize rfParams=_rfParams;
@property(retain, nonatomic) CSPicAdvPanel *ctrlAdvPanel; // @synthesize ctrlAdvPanel=_ctrlAdvPanel;
@property(retain, nonatomic) CSXsTryLoc *ctrlTryLoc; // @synthesize ctrlTryLoc=_ctrlTryLoc;
@property(retain, nonatomic) CSCurrentLocationPanel *ctrlLocPanel; // @synthesize ctrlLocPanel=_ctrlLocPanel;
@property(retain, nonatomic) CSMdbRlSelectPanel *ctrlSelectPanel; // @synthesize ctrlSelectPanel=_ctrlSelectPanel;
- (void)alertHintViewOnClickTryAgainBtn;
- (void)onXsTryLocSuccessWithTag:(int)arg1;
- (void)onMdbRlSelectPanelChangeSelect;
- (void)adjustPage;
- (void)onTableViewEndDragging;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (void)makeCell:(id)arg1 indexPath:(id)arg2;
- (void)createCell:(id)arg1;
- (double)heightForRowAtIndexPath:(id)arg1;
- (void)completeQueryParams;
- (void)onHttpRequestFail:(long long)arg1 errorMsg:(id)arg2 tag:(long long)arg3;
- (void)completeLoadData;
- (void)onHttpRequestSuccess:(id)arg1 tag:(long long)arg2;
- (void)loadData;
- (void)topViewRightBtnClicked:(id)arg1;
- (void)topViewBackBtnClicked:(id)arg1;
- (void)onPopFromNavStack;
- (void)onHide;
- (void)onParseNavBackPageParams:(id)arg1;
- (void)onShow;
- (void)onWillShow;
- (void)onParsePageParams:(id)arg1;
- (void)onClose;
- (void)onCleanData;
- (void)onCreate;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

