//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BaseSingleListVc.h"

#import "UITextFieldDelegate.h"

@class MdbSearchRestListDTO, NSString, UITextField;

@interface MdbSearchRestListVc : BaseSingleListVc <UITextFieldDelegate>
{
    UITextField *_ctrlTf;
    MdbSearchRestListDTO *_dto;
    NSString *_keywords;
    NSString *_selRestId;
}

@property(retain, nonatomic) NSString *selRestId; // @synthesize selRestId=_selRestId;
@property(retain, nonatomic) NSString *keywords; // @synthesize keywords=_keywords;
@property(retain, nonatomic) MdbSearchRestListDTO *dto; // @synthesize dto=_dto;
@property(retain, nonatomic) UITextField *ctrlTf; // @synthesize ctrlTf=_ctrlTf;
- (void)alertView:(id)arg1 hideWithBtnIdx:(long long)arg2;
- (void)toMdbFreeOrderFormWithRestId:(id)arg1;
- (void)hideKeyboard;
- (void)stopQueryTimer;
- (void)handleQueryTimer;
- (void)queryKeywordsOnChange;
- (_Bool)textFieldShouldReturn:(id)arg1;
- (_Bool)textField:(id)arg1 shouldChangeCharactersInRange:(struct _NSRange)arg2 replacementString:(id)arg3;
- (void)textFieldDidChange:(id)arg1;
- (void)onTableViewEndDragging;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (void)makeCell:(id)arg1 indexPath:(id)arg2;
- (void)createCell:(id)arg1;
- (void)completeQueryParamsWithTag:(long long)arg1;
- (void)onHttpRequestFail:(long long)arg1 errorMsg:(id)arg2;
- (void)completeLoadData;
- (void)onHttpRequestSuccess:(id)arg1 tag:(long long)arg2;
- (void)loadDataForSearch;
- (void)loadData;
- (void)topViewRightBtnClicked:(id)arg1;
- (void)topViewBackBtnClicked:(id)arg1;
- (void)onPopFromNavStack;
- (void)onHide;
- (void)onParseNavBackPageParams:(id)arg1;
- (void)onShow;
- (void)onWillShow;
- (void)onParsePageParams:(id)arg1;
- (void)onClose;
- (void)onCleanData;
- (void)onCreate;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

