//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDate;

@interface MemCachePackData : NSObject
{
    int _expireMin;
    NSObject *_obj;
    NSDate *_date;
}

@property(nonatomic) int expireMin; // @synthesize expireMin=_expireMin;
@property(retain, nonatomic) NSDate *date; // @synthesize date=_date;
@property(retain, nonatomic) NSObject *obj; // @synthesize obj=_obj;
- (void)dealloc;
- (id)init;

@end

