//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MKMapView.h"

@interface MKMapView (ZoomLevel)
- (double)getZoomLevel;
- (void)setCenterCoordinate:(CDStruct_c3b9c2ee)arg1 zoomLevel:(double)arg2 animated:(_Bool)arg3;
- (CDStruct_c3b9c2ee)coordinateSpanWithMapView:(id)arg1 centerCoordinate:(CDStruct_c3b9c2ee)arg2 andZoomLevel:(double)arg3;
- (double)pixelSpaceYToLatitude:(double)arg1;
- (double)pixelSpaceXToLongitude:(double)arg1;
- (double)latitudeToPixelSpaceY:(double)arg1;
- (double)longitudeToPixelSpaceX:(double)arg1;
@end

