//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BaseSingleListVc.h"

@class NSConditionLock, NSMutableArray, NSString;

@interface MultiPhotoPickerVc : BaseSingleListVc
{
    _Bool _multiTag;
    int _multiMaxNum;
    NSMutableArray *_list;
    NSString *_groupName;
    NSString *_backPageKey;
    NSMutableArray *_selList;
    NSMutableArray *_tmpList;
    NSConditionLock *_lock;
}

@property(retain, nonatomic) NSConditionLock *lock; // @synthesize lock=_lock;
@property(retain, nonatomic) NSMutableArray *tmpList; // @synthesize tmpList=_tmpList;
@property(retain, nonatomic) NSMutableArray *selList; // @synthesize selList=_selList;
@property(retain, nonatomic) NSString *backPageKey; // @synthesize backPageKey=_backPageKey;
@property(retain, nonatomic) NSString *groupName; // @synthesize groupName=_groupName;
@property(nonatomic) int multiMaxNum; // @synthesize multiMaxNum=_multiMaxNum;
@property(nonatomic) _Bool multiTag; // @synthesize multiTag=_multiTag;
@property(retain, nonatomic) NSMutableArray *list; // @synthesize list=_list;
- (int)selIdxWithData:(id)arg1;
- (void)endDoProcessSelList;
- (void)doProcessSelList;
- (void)okBtnClicked;
- (void)changeBtnState:(id)arg1 selTag:(_Bool)arg2;
- (void)btnClicked:(id)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (void)makeOneCell:(id)arg1 imageViewTag:(long long)arg2 dataIdx:(long long)arg3;
- (void)makeCell:(id)arg1 indexPath:(id)arg2;
- (void)createOneCell:(id)arg1 tag:(int)arg2;
- (void)createCell:(id)arg1;
- (double)heightForRowAtIndexPath:(id)arg1;
- (void)topViewRightBtnClicked:(id)arg1;
- (void)topViewBackBtnClicked:(id)arg1;
- (void)onPopFromNavStack;
- (void)onHide;
- (void)onParseNavBackPageParams:(id)arg1;
- (void)onShow;
- (void)onWillShow;
- (void)onParsePageParams:(id)arg1;
- (void)onClose;
- (void)onCleanData;
- (void)onCreate;

@end

