//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class CityData;

@interface NeedHintCityChangeData : NSObject
{
    _Bool _needHintTag;
    CityData *_cityData;
}

@property(nonatomic) _Bool needHintTag; // @synthesize needHintTag=_needHintTag;
@property(retain, nonatomic) CityData *cityData; // @synthesize cityData=_cityData;
- (_Bool)chkIsNeedSwitchCity;
- (void)needHintWithCityData:(id)arg1 hintRightNow:(_Bool)arg2;
- (void)reset;
- (void)dealloc;
- (id)init;

@end

