//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSData.h"

@interface NSData (NSDataGZipAdditions)
+ (id)dataWithCompressedData:(id)arg1;
+ (id)dataWithCompressedBytes:(const void *)arg1 length:(unsigned int)arg2;
+ (id)compressedDataWithData:(id)arg1;
+ (id)compressDataWithBytes:(const void *)arg1 length:(unsigned long long)arg2;
@end

