//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSString.h"

@interface NSString (AIJSONKitDeserializing)
- (id)mutableObjectFromAIJSONStringWithParseOptions:(unsigned long long)arg1 error:(id *)arg2;
- (id)mutableObjectFromAIJSONStringWithParseOptions:(unsigned long long)arg1;
- (id)mutableObjectFromAIJSONString;
- (id)objectFromAIJSONStringWithParseOptions:(unsigned long long)arg1 error:(id *)arg2;
- (id)objectFromAIJSONStringWithParseOptions:(unsigned long long)arg1;
- (id)objectFromAIJSONString;
@end

