//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class MainPageData, NSMutableArray, NSString;

@interface OrderDetailData : NSObject
{
    _Bool _showOrderDescribePanelTag;
    _Bool _showCashCouponPanelTag;
    _Bool _showFoodCommentPanelTag;
    _Bool _canFoodCommentTag;
    _Bool _canSmsTag;
    _Bool _canEditTag;
    _Bool _canCancelTag;
    _Bool _showHintPanelTag;
    _Bool _isMustBuyCashCoupon;
    _Bool _showPanelCashCouponBtnTag;
    int _peopleNum;
    int _bookerSexTag;
    int _roomTypeTag;
    NSString *_orderId;
    NSString *_restId;
    NSString *_restName;
    NSString *_giftId;
    NSString *_foodId;
    NSString *_orderDescribe;
    NSString *_cashCouponDescribe;
    NSString *_cashCouponId;
    NSString *_foodName;
    NSMutableArray *_foodCommentList;
    NSString *_panelHint;
    NSString *_bookerTel;
    double _reserveTime;
    NSString *_bookerName;
    NSString *_memo;
    MainPageData *_mainPageData;
}

@property(retain, nonatomic) MainPageData *mainPageData; // @synthesize mainPageData=_mainPageData;
@property(retain, nonatomic) NSString *memo; // @synthesize memo=_memo;
@property(nonatomic) int roomTypeTag; // @synthesize roomTypeTag=_roomTypeTag;
@property(nonatomic) int bookerSexTag; // @synthesize bookerSexTag=_bookerSexTag;
@property(retain, nonatomic) NSString *bookerName; // @synthesize bookerName=_bookerName;
@property(nonatomic) int peopleNum; // @synthesize peopleNum=_peopleNum;
@property(nonatomic) double reserveTime; // @synthesize reserveTime=_reserveTime;
@property(retain, nonatomic) NSString *bookerTel; // @synthesize bookerTel=_bookerTel;
@property(nonatomic) _Bool showPanelCashCouponBtnTag; // @synthesize showPanelCashCouponBtnTag=_showPanelCashCouponBtnTag;
@property(nonatomic) _Bool isMustBuyCashCoupon; // @synthesize isMustBuyCashCoupon=_isMustBuyCashCoupon;
@property(retain, nonatomic) NSString *panelHint; // @synthesize panelHint=_panelHint;
@property(nonatomic) _Bool showHintPanelTag; // @synthesize showHintPanelTag=_showHintPanelTag;
@property(nonatomic) _Bool canCancelTag; // @synthesize canCancelTag=_canCancelTag;
@property(nonatomic) _Bool canEditTag; // @synthesize canEditTag=_canEditTag;
@property(nonatomic) _Bool canSmsTag; // @synthesize canSmsTag=_canSmsTag;
@property(nonatomic) _Bool canFoodCommentTag; // @synthesize canFoodCommentTag=_canFoodCommentTag;
@property(retain, nonatomic) NSMutableArray *foodCommentList; // @synthesize foodCommentList=_foodCommentList;
@property(retain, nonatomic) NSString *foodName; // @synthesize foodName=_foodName;
@property(nonatomic) _Bool showFoodCommentPanelTag; // @synthesize showFoodCommentPanelTag=_showFoodCommentPanelTag;
@property(retain, nonatomic) NSString *cashCouponId; // @synthesize cashCouponId=_cashCouponId;
@property(retain, nonatomic) NSString *cashCouponDescribe; // @synthesize cashCouponDescribe=_cashCouponDescribe;
@property(nonatomic) _Bool showCashCouponPanelTag; // @synthesize showCashCouponPanelTag=_showCashCouponPanelTag;
@property(retain, nonatomic) NSString *orderDescribe; // @synthesize orderDescribe=_orderDescribe;
@property(nonatomic) _Bool showOrderDescribePanelTag; // @synthesize showOrderDescribePanelTag=_showOrderDescribePanelTag;
@property(retain, nonatomic) NSString *foodId; // @synthesize foodId=_foodId;
@property(retain, nonatomic) NSString *giftId; // @synthesize giftId=_giftId;
@property(retain, nonatomic) NSString *restName; // @synthesize restName=_restName;
@property(retain, nonatomic) NSString *restId; // @synthesize restId=_restId;
@property(retain, nonatomic) NSString *orderId; // @synthesize orderId=_orderId;
- (void)unitTest;
- (void)dealloc;
- (id)initWithObj:(id)arg1;

@end

