//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BaseDto.h"

@class CouponPanelData, NSMutableArray, RestInfoData, RestRecomInfoData;

@interface PageResInfoDto : BaseDto
{
    _Bool _showCouponPanelTag;
    int _totalCommentNum;
    int _showTypeTag;
    RestInfoData *_restInfo;
    RestRecomInfoData *_recomInfo;
    NSMutableArray *_commentList;
    CouponPanelData *_couponPanelData;
}

@property(retain, nonatomic) CouponPanelData *couponPanelData; // @synthesize couponPanelData=_couponPanelData;
@property(nonatomic) _Bool showCouponPanelTag; // @synthesize showCouponPanelTag=_showCouponPanelTag;
@property(nonatomic) int showTypeTag; // @synthesize showTypeTag=_showTypeTag;
@property(nonatomic) int totalCommentNum; // @synthesize totalCommentNum=_totalCommentNum;
@property(retain, nonatomic) NSMutableArray *commentList; // @synthesize commentList=_commentList;
@property(retain, nonatomic) RestRecomInfoData *recomInfo; // @synthesize recomInfo=_recomInfo;
@property(retain, nonatomic) RestInfoData *restInfo; // @synthesize restInfo=_restInfo;
- (void)unitTest;
- (void)dealloc;
- (id)initWithObj:(id)arg1;

@end

