//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BaseDetailVc.h"

#import "CSPsCheckBtnDelegate.h"

@class CSPsCheckBtn, CSPsCutPanel, NSString, UIButton, UIImage;

@interface PsCutVc : BaseDetailVc <CSPsCheckBtnDelegate>
{
    CSPsCutPanel *_ctrlCutPanel;
    CSPsCheckBtn *_ctrlCheckBtn;
    UIButton *_ctrlOkBtn;
    UIImage *_img;
}

@property(retain, nonatomic) UIImage *img; // @synthesize img=_img;
@property(retain, nonatomic) UIButton *ctrlOkBtn; // @synthesize ctrlOkBtn=_ctrlOkBtn;
@property(retain, nonatomic) CSPsCheckBtn *ctrlCheckBtn; // @synthesize ctrlCheckBtn=_ctrlCheckBtn;
@property(retain, nonatomic) CSPsCutPanel *ctrlCutPanel; // @synthesize ctrlCutPanel=_ctrlCutPanel;
- (void).cxx_destruct;
- (void)changeOkBtnTitle:(_Bool)arg1;
- (void)onPsCheckBtnClicked;
- (void)refreshPanel;
- (void)btnClicked;
- (void)topViewBackBtnClicked:(id)arg1;
- (void)onPopFromNavStack;
- (void)onHide;
- (void)onParseNavBackPageParams:(id)arg1;
- (void)onShow;
- (void)onWillShow;
- (void)onParsePageParams:(id)arg1;
- (void)onClose;
- (void)onCleanData;
- (void)onCreate;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

