//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BaseDetailVc.h"

#import "CSPsImageFilterPanelDelegate.h"

@class CSPsCheckedButton, CSPsImageEditPanel, CSPsImageFilterPanel, NSString, NSTimer, UIView;

@interface PsEditVc : BaseDetailVc <CSPsImageFilterPanelDelegate>
{
    NSString *_rePageKey;
    CSPsImageEditPanel *_ctrlImagePanel;
    UIView *_ctrlBottomPanel;
    CSPsCheckedButton *_ctrlAutoRefineBtn;
    CSPsCheckedButton *_ctrlShowSubtitleBtn;
    CSPsCheckedButton *_ctrlShowFilterBtn;
    CSPsCheckedButton *_ctrlShowContrastBtn;
    UIView *_ctrlSubtitlePanel;
    CSPsCheckedButton *_ctrlToggleSubtitleBtn;
    CSPsCheckedButton *_ctrlToggleWideScreenBtn;
    CSPsImageFilterPanel *_ctrlFilterPanel;
    UIView *_ctrlContrastAdjustPanel;
    double _contrastValueInUse;
    NSTimer *_timerDelayedApplyContrast;
}

@property(retain, nonatomic) NSTimer *timerDelayedApplyContrast; // @synthesize timerDelayedApplyContrast=_timerDelayedApplyContrast;
@property(nonatomic) double contrastValueInUse; // @synthesize contrastValueInUse=_contrastValueInUse;
@property(retain, nonatomic) UIView *ctrlContrastAdjustPanel; // @synthesize ctrlContrastAdjustPanel=_ctrlContrastAdjustPanel;
@property(retain, nonatomic) CSPsImageFilterPanel *ctrlFilterPanel; // @synthesize ctrlFilterPanel=_ctrlFilterPanel;
@property(retain, nonatomic) CSPsCheckedButton *ctrlToggleWideScreenBtn; // @synthesize ctrlToggleWideScreenBtn=_ctrlToggleWideScreenBtn;
@property(retain, nonatomic) CSPsCheckedButton *ctrlToggleSubtitleBtn; // @synthesize ctrlToggleSubtitleBtn=_ctrlToggleSubtitleBtn;
@property(retain, nonatomic) UIView *ctrlSubtitlePanel; // @synthesize ctrlSubtitlePanel=_ctrlSubtitlePanel;
@property(retain, nonatomic) CSPsCheckedButton *ctrlShowContrastBtn; // @synthesize ctrlShowContrastBtn=_ctrlShowContrastBtn;
@property(retain, nonatomic) CSPsCheckedButton *ctrlShowFilterBtn; // @synthesize ctrlShowFilterBtn=_ctrlShowFilterBtn;
@property(retain, nonatomic) CSPsCheckedButton *ctrlShowSubtitleBtn; // @synthesize ctrlShowSubtitleBtn=_ctrlShowSubtitleBtn;
@property(retain, nonatomic) CSPsCheckedButton *ctrlAutoRefineBtn; // @synthesize ctrlAutoRefineBtn=_ctrlAutoRefineBtn;
@property(retain, nonatomic) UIView *ctrlBottomPanel; // @synthesize ctrlBottomPanel=_ctrlBottomPanel;
@property(retain, nonatomic) CSPsImageEditPanel *ctrlImagePanel; // @synthesize ctrlImagePanel=_ctrlImagePanel;
@property(retain, nonatomic) NSString *rePageKey; // @synthesize rePageKey=_rePageKey;
- (void).cxx_destruct;
- (void)generateSampleFromImage;
- (void)refreshFilterPanel;
- (void)stopTimer;
- (void)startTimer;
- (void)openSecondaryPanelForBtn:(id)arg1;
- (void)closeSecondaryPanels;
- (void)secondaryPanelBtnClicked:(id)arg1;
- (void)optionsPanelBtnClicked:(id)arg1;
- (void)createDemoBtn;
- (void)createContrastAdjustPanel;
- (void)createSubtitlePanel;
- (void)createOptionsPanel;
- (void)pipelineAllChanges;
- (void)sliderMoved:(id)arg1;
- (void)onCSPsImageFilterPanelSelectImage;
- (void)adjustContrast:(double)arg1;
- (void)toggleSubtitle;
- (void)toggleWideScreen;
- (void)completeQueryParamsWithTag:(long long)arg1;
- (void)onHttpRequestFail:(long long)arg1 errorMsg:(id)arg2;
- (void)completeLoadData;
- (void)onHttpRequestSuccess:(id)arg1 tag:(long long)arg2;
- (void)postData;
- (void)loadData;
- (void)topViewRightBtnClicked:(id)arg1;
- (void)topViewBackBtnClicked:(id)arg1;
- (void)onPopFromNavStack;
- (void)onHide;
- (void)onParseNavBackPageParams:(id)arg1;
- (void)onShow;
- (void)onWillShow;
- (void)onParsePageParams:(id)arg1;
- (void)onClose;
- (void)onCleanData;
- (void)onCreate;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

