//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface PushMsgDTO : NSObject
{
    int _typeTag;
    NSString *_title;
    NSString *_advId;
    NSString *_advUrl;
    NSString *_o;
    NSString *_c;
}

@property(retain, nonatomic) NSString *c; // @synthesize c=_c;
@property(retain, nonatomic) NSString *o; // @synthesize o=_o;
@property(retain, nonatomic) NSString *advUrl; // @synthesize advUrl=_advUrl;
@property(retain, nonatomic) NSString *advId; // @synthesize advId=_advId;
@property(retain, nonatomic) NSString *title; // @synthesize title=_title;
@property(nonatomic) int typeTag; // @synthesize typeTag=_typeTag;
- (void)dealloc;
- (id)initWithObj:(id)arg1;

@end

