//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "RestDetailPanelView.h"

#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class NSObject<RDPromoPanelViewDelegate>, NSString;

@interface RDPromoPanelView : RestDetailPanelView <UITableViewDelegate, UITableViewDataSource>
{
    NSObject<RDPromoPanelViewDelegate> *_delegate;
}

@property NSObject<RDPromoPanelViewDelegate> *delegate; // @synthesize delegate=_delegate;
- (void)pointsCellSelected;
- (void)promoCellSelected;
- (void)cashCouponCellSelected:(id)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (float)cellHeight:(long long)arg1;
- (float)calLabelWidth;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)doRefreshPanel;
- (void)doDealloc;
- (void)doIni;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

