//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface RecentRestListData : NSObject
{
    NSString *resId;
    NSString *resName;
    NSString *picUrl;
    NSString *menuTypeInfo;
    NSString *avgPrice;
    double overallNum;
}

@property(nonatomic) double overallNum; // @synthesize overallNum;
@property(retain, nonatomic) NSString *avgPrice; // @synthesize avgPrice;
@property(retain, nonatomic) NSString *menuTypeInfo; // @synthesize menuTypeInfo;
@property(retain, nonatomic) NSString *picUrl; // @synthesize picUrl;
@property(retain, nonatomic) NSString *resName; // @synthesize resName;
@property(retain, nonatomic) NSString *resId; // @synthesize resId;
- (id)newDicData;
- (void)dealloc;
- (id)initWithObj:(id)arg1;

@end

