//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BaseSingleListVc.h"

#import "CSCommentViewDelegate.h"

@class CommentData, CommentReplyListDto, NSString;

@interface ReplyListVc : BaseSingleListVc <CSCommentViewDelegate>
{
    NSString *_restId;
    NSString *_restName;
    CommentData *_comment;
    CommentReplyListDto *_dto;
}

@property(retain, nonatomic) CommentReplyListDto *dto; // @synthesize dto=_dto;
@property(retain, nonatomic) CommentData *comment; // @synthesize comment=_comment;
@property(retain, nonatomic) NSString *restName; // @synthesize restName=_restName;
@property(retain, nonatomic) NSString *restId; // @synthesize restId=_restId;
- (void)commentViewReply:(id)arg1;
- (id)newHeaderView;
- (void)btnClick_GotoReply:(id)arg1;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)topViewRightBtnClicked:(id)arg1;
- (void)topViewBackBtnClicked:(id)arg1;
- (void)completeQueryParams;
- (void)completeLoadData;
- (void)onHttpRequestFail:(long long)arg1 errorMsg:(id)arg2;
- (void)onHttpRequestSuccess:(id)arg1 tag:(long long)arg2;
- (void)loadData;
- (void)onParseNavBackPageParams:(id)arg1;
- (void)onParsePageParams:(id)arg1;
- (void)onClose;
- (void)onCleanData;
- (void)onWillShow;
- (void)onCreate;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

