//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BaseDetailVc.h"

#import "UIScrollViewDelegate.h"
#import "UITextFieldDelegate.h"

@class NSString, RestInfoData, UIButton, UIScrollView, UITextField, UITextView;

@interface ReportRestAddOrModifyPostVc : BaseDetailVc <UIScrollViewDelegate, UITextFieldDelegate>
{
    UIScrollView *scrollView;
    UITextField *tfRestName;
    UIButton *btnRegion;
    UITextField *tfRestAddress;
    UIButton *btnMainMenuName;
    UITextField *tfPhone;
    UITextField *tfEmail;
    UITextView *tvRewardMsg;
    RestInfoData *restInfoData;
    NSString *postTag;
    NSString *restId;
    NSString *restName;
    NSString *cityId;
    NSString *regionId;
    NSString *districtId;
    NSString *mainMenuId;
    NSString *restAddress;
    NSString *restTel;
    NSString *email;
    NSString *token;
    NSString *backBtnName;
    NSString *fromPage;
    NSString *timestamp;
    _Bool isFromImageUploading;
    NSString *uuidFromServer;
    _Bool forceRefreshTag;
    _Bool isForTakeOutTag;
    _Bool isForRestRecom;
}

@property(nonatomic) _Bool isForRestRecom; // @synthesize isForRestRecom;
@property _Bool isForTakeOutTag; // @synthesize isForTakeOutTag;
@property _Bool forceRefreshTag; // @synthesize forceRefreshTag;
@property(retain, nonatomic) NSString *uuidFromServer; // @synthesize uuidFromServer;
@property _Bool isFromImageUploading; // @synthesize isFromImageUploading;
@property(retain, nonatomic) NSString *timestamp; // @synthesize timestamp;
@property(retain, nonatomic) NSString *fromPage; // @synthesize fromPage;
@property(retain, nonatomic) NSString *backBtnName; // @synthesize backBtnName;
@property(retain, nonatomic) NSString *token; // @synthesize token;
@property(retain, nonatomic) NSString *email; // @synthesize email;
@property(retain, nonatomic) NSString *restTel; // @synthesize restTel;
@property(retain, nonatomic) NSString *restAddress; // @synthesize restAddress;
@property(retain, nonatomic) NSString *mainMenuId; // @synthesize mainMenuId;
@property(retain, nonatomic) NSString *districtId; // @synthesize districtId;
@property(retain, nonatomic) NSString *regionId; // @synthesize regionId;
@property(retain, nonatomic) NSString *cityId; // @synthesize cityId;
@property(retain, nonatomic) NSString *restName; // @synthesize restName;
@property(retain, nonatomic) NSString *restId; // @synthesize restId;
@property(retain, nonatomic) NSString *postTag; // @synthesize postTag;
@property(retain, nonatomic) RestInfoData *restInfoData; // @synthesize restInfoData;
@property(retain, nonatomic) UITextView *tvRewardMsg; // @synthesize tvRewardMsg;
@property(retain, nonatomic) UITextField *tfEmail; // @synthesize tfEmail;
@property(retain, nonatomic) UITextField *tfPhone; // @synthesize tfPhone;
@property(retain, nonatomic) UIButton *btnMainMenuName; // @synthesize btnMainMenuName;
@property(retain, nonatomic) UITextField *tfRestAddress; // @synthesize tfRestAddress;
@property(retain, nonatomic) UIButton *btnRegion; // @synthesize btnRegion;
@property(retain, nonatomic) UITextField *tfRestName; // @synthesize tfRestName;
@property(retain, nonatomic) UIScrollView *scrollView; // @synthesize scrollView;
- (void)finishPickPhotoWithDataList:(id)arg1;
- (void)resignFromAllInputTextFields;
- (void)openLoginPage;
- (void)alertView:(id)arg1 hideWithBtnIdx:(long long)arg2;
- (void)submitBtnClicked:(id)arg1;
- (void)selectMenuType:(id)arg1;
- (void)selectRegion:(id)arg1;
- (_Bool)textFieldShouldReturn:(id)arg1;
- (void)keyboardBarDidTapHideBtn:(id)arg1;
- (_Bool)textFieldShouldClear:(id)arg1;
- (void)textFieldDidEndEditing:(id)arg1;
- (void)textFieldDidBeginEditing:(id)arg1;
- (_Bool)textField:(id)arg1 shouldChangeCharactersInRange:(struct _NSRange)arg2 replacementString:(id)arg3;
- (void)topViewRightBtnClicked:(id)arg1;
- (void)topViewBackBtnClicked:(id)arg1;
- (void)completeQueryParams;
- (void)onHttpRequestFail:(long long)arg1 errorMsg:(id)arg2;
- (void)onHttpRequestSuccess:(id)arg1 msg:(id)arg2 tag:(long long)arg3;
- (void)postData;
- (id)validateEmailInput:(id)arg1;
- (_Bool)NSStringIsValidEmail:(id)arg1;
- (id)validateTextFieldInput:(id)arg1 withMinLength:(int)arg2 withMaxLength:(int)arg3 withHumanReadableLabel:(id)arg4 allowEmpty:(_Bool)arg5;
- (void)onCleanData;
- (void)onShow;
- (void)onHide;
- (void)onParseNavBackPageParams:(id)arg1;
- (void)onWillShow;
- (void)onParsePageParams:(id)arg1;
- (void)onClose;
- (void)onCreate;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

