//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BaseDto.h"

@class NSMutableArray, NSString;

@interface ResFoodPicDataDTO : BaseDto
{
    NSString *_uuid;
    NSString *_name;
    NSString *_restId;
    NSString *_restName;
    long long _goodNum;
    long long _normalNum;
    long long _badNum;
    NSString *_price;
    NSString *_unit;
    NSMutableArray *_picList;
    NSMutableArray *_commentList;
    double _priceNum;
    NSMutableArray *_unitList;
    NSString *_soName;
    double _soPrice;
    NSString *_soUnitId;
    NSString *_soUnitName;
}

@property(retain, nonatomic) NSString *soUnitName; // @synthesize soUnitName=_soUnitName;
@property(retain, nonatomic) NSString *soUnitId; // @synthesize soUnitId=_soUnitId;
@property(nonatomic) double soPrice; // @synthesize soPrice=_soPrice;
@property(retain, nonatomic) NSString *soName; // @synthesize soName=_soName;
@property(retain, nonatomic) NSMutableArray *unitList; // @synthesize unitList=_unitList;
@property(nonatomic) double priceNum; // @synthesize priceNum=_priceNum;
@property(retain, nonatomic) NSMutableArray *commentList; // @synthesize commentList=_commentList;
@property(retain, nonatomic) NSMutableArray *picList; // @synthesize picList=_picList;
@property(retain, nonatomic) NSString *unit; // @synthesize unit=_unit;
@property(retain, nonatomic) NSString *price; // @synthesize price=_price;
@property long long badNum; // @synthesize badNum=_badNum;
@property long long normalNum; // @synthesize normalNum=_normalNum;
@property long long goodNum; // @synthesize goodNum=_goodNum;
@property(retain, nonatomic) NSString *restName; // @synthesize restName=_restName;
@property(retain, nonatomic) NSString *restId; // @synthesize restId=_restId;
@property(retain, nonatomic) NSString *name; // @synthesize name=_name;
@property(retain, nonatomic) NSString *uuid; // @synthesize uuid=_uuid;
- (void)unitTest;
- (void)prepareForEdit;
- (void)appendData:(id)arg1;
- (void)dealloc;
- (id)initWithObj:(id)arg1;

@end

