//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface ResGroupPicData : NSObject
{
    NSString *uuid;
    NSString *picUrl;
    NSString *uploader;
    double uploadTime;
}

@property(nonatomic) double uploadTime; // @synthesize uploadTime;
@property(retain, nonatomic) NSString *uploader; // @synthesize uploader;
@property(retain, nonatomic) NSString *picUrl; // @synthesize picUrl;
@property(retain, nonatomic) NSString *uuid; // @synthesize uuid;
- (void)dealloc;
- (id)initWithObj:(id)arg1;

@end

