//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BaseSectionListVc.h"

@class RestInfoData;

@interface RestDiscountDetailVc : BaseSectionListVc
{
    RestInfoData *_info;
}

@property(retain, nonatomic) RestInfoData *info; // @synthesize info=_info;
- (float)calOtherLabelWidth;
- (float)calQunLabelWidth;
- (float)calLabelWidth;
- (void)buyBtnClick:(id)arg1;
- (_Bool)isCouponSection:(long long)arg1;
- (_Bool)isPromoSection:(long long)arg1;
- (_Bool)havePromoList;
- (long long)totalSection;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)topViewBackBtnClicked:(id)arg1;
- (void)onPopFromNavStack;
- (void)onHide;
- (void)onParseNavBackPageParams:(id)arg1;
- (void)onShow;
- (void)onWillShow;
- (void)onParsePageParams:(id)arg1;
- (void)onClose;
- (void)onCleanData;
- (void)onCreate;

@end

