//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BaseDetailVc.h"

#import "CSUpdImgListPanelDelegate.h"

@class CSUpdImgListPanel, CSZyShareButtonSet, NSMutableArray, NSString, ResFoodPicDataDTO;

@interface RestUploadImageVc : BaseDetailVc <CSUpdImgListPanelDelegate>
{
    CSUpdImgListPanel *_ctrlPanel;
    CSZyShareButtonSet *_ctrlShareSet;
    NSString *_restId;
    ResFoodPicDataDTO *_foodData;
    NSMutableArray *_list;
}

@property(retain, nonatomic) NSMutableArray *list; // @synthesize list=_list;
@property(retain, nonatomic) ResFoodPicDataDTO *foodData; // @synthesize foodData=_foodData;
@property(retain, nonatomic) NSString *restId; // @synthesize restId=_restId;
@property(retain, nonatomic) CSZyShareButtonSet *ctrlShareSet; // @synthesize ctrlShareSet=_ctrlShareSet;
@property(retain, nonatomic) CSUpdImgListPanel *ctrlPanel; // @synthesize ctrlPanel=_ctrlPanel;
- (id)listToJsonStr;
- (void)addNSDateListToList:(id)arg1;
- (void)refreshPanel;
- (void)alertView:(id)arg1 hideWithBtnIdx:(long long)arg2;
- (void)finishPickPhotoWithDataList:(id)arg1;
- (void)onUpdImgListPanelClickedWithIdx:(long long)arg1;
- (id)makePostUrlWithJsonStrSize:(long long)arg1;
- (void)completeQueryParams;
- (void)onHttpRequestFail:(long long)arg1 errorMsg:(id)arg2;
- (void)onHttpRequestSuccess:(id)arg1 tag:(long long)arg2;
- (void)postData;
- (void)topViewRightBtnClicked:(id)arg1;
- (void)topViewBackBtnClicked:(id)arg1;
- (void)onPopFromNavStack;
- (void)onHide;
- (void)onParseNavBackPageParams:(id)arg1;
- (void)handleOnShow;
- (void)onShow;
- (void)onWillShow;
- (void)onParsePageParams:(id)arg1;
- (void)onClose;
- (void)onCleanData;
- (void)onCreate;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

