//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BaseDetailVc.h"

@class NSMutableArray, RestUploadData, SimpleData, UploadData;

@interface RestUploadConfirmVc : BaseDetailVc
{
    RestUploadData *uploadData;
    UploadData *dto;
    SimpleData *rsltData;
    NSMutableArray *subViews;
}

@property(retain, nonatomic) NSMutableArray *subViews; // @synthesize subViews;
@property(retain, nonatomic) SimpleData *rsltData; // @synthesize rsltData;
@property(retain, nonatomic) UploadData *dto; // @synthesize dto;
@property(retain, nonatomic) RestUploadData *uploadData; // @synthesize uploadData;
- (id)newItemView:(_Bool)arg1 withType:(long long)arg2;
- (void)backToFromPageWithSucc:(_Bool)arg1;
- (void)btnClick_Submit;
- (void)postFinished;
- (void)cancelPickPhoto;
- (void)finishPickPhotoWithDataList:(id)arg1;
- (void)alertView:(id)arg1 hideWithBtnIdx:(long long)arg2;
- (void)completeQueryParamsWithTag:(long long)arg1;
- (void)onHttpRequestFail:(long long)arg1 errorMsg:(id)arg2 tag:(long long)arg3;
- (void)onHttpRequestSuccess:(id)arg1 tag:(long long)arg2;
- (void)postForType:(long long)arg1;
- (void)postData;
- (void)onWillShow;
- (void)onParseNavBackPageParams:(id)arg1;
- (void)onParsePageParams:(id)arg1;
- (void)onClose;
- (void)onCleanData;
- (void)onCreate;

@end

