//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BaseDto.h"

@class NSMutableArray;

@interface RestRecomListDTO : BaseDto
{
    NSMutableArray *_list;
    NSMutableArray *_soNextTopList;
}

@property(retain, nonatomic) NSMutableArray *soNextTopList; // @synthesize soNextTopList=_soNextTopList;
@property(retain, nonatomic) NSMutableArray *list; // @synthesize list=_list;
- (void)unitTest;
- (int)calPanelWidth;
- (id)newCalPanelFrameAndSetNextTop:(id)arg1 forMainPage:(_Bool)arg2;
- (double)calWaterfallPanelHeight;
- (void)appendData:(id)arg1;
- (void)appendList:(id)arg1;
- (void)dealloc;
- (id)initWithObj:(id)arg1;

@end

