//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BaseDetailVc.h"

#import "MKMapViewDelegate.h"
#import "UIAlertViewDelegate.h"

@class AddressAnnotation, MKMapView, NSString, UIView;

@interface RestMapV2Vc : BaseDetailVc <MKMapViewDelegate, UIAlertViewDelegate>
{
    _Bool _isShopOriginalLocationEmpty;
    _Bool _isCustomRestAnnoShown;
    _Bool _isCustomRestAnnoOn;
    MKMapView *_map;
    AddressAnnotation *_restAnnotation;
    NSString *_restName;
    NSString *_restAddress;
    double _longitude;
    double _latitude;
    double _longitudeGoogle;
    double _latitudeGoogle;
    AddressAnnotation *_userCurrentLocation;
    NSString *_restId;
    NSString *_typeTag;
    UIView *_ctrlDestInfoPanel;
}

@property(nonatomic) _Bool isCustomRestAnnoOn; // @synthesize isCustomRestAnnoOn=_isCustomRestAnnoOn;
@property(nonatomic) _Bool isCustomRestAnnoShown; // @synthesize isCustomRestAnnoShown=_isCustomRestAnnoShown;
@property(retain, nonatomic) UIView *ctrlDestInfoPanel; // @synthesize ctrlDestInfoPanel=_ctrlDestInfoPanel;
@property(retain, nonatomic) NSString *typeTag; // @synthesize typeTag=_typeTag;
@property(nonatomic) _Bool isShopOriginalLocationEmpty; // @synthesize isShopOriginalLocationEmpty=_isShopOriginalLocationEmpty;
@property(retain, nonatomic) NSString *restId; // @synthesize restId=_restId;
@property(retain, nonatomic) AddressAnnotation *userCurrentLocation; // @synthesize userCurrentLocation=_userCurrentLocation;
@property(nonatomic) double latitudeGoogle; // @synthesize latitudeGoogle=_latitudeGoogle;
@property(nonatomic) double longitudeGoogle; // @synthesize longitudeGoogle=_longitudeGoogle;
@property(nonatomic) double latitude; // @synthesize latitude=_latitude;
@property(nonatomic) double longitude; // @synthesize longitude=_longitude;
@property(retain, nonatomic) NSString *restAddress; // @synthesize restAddress=_restAddress;
@property(retain, nonatomic) NSString *restName; // @synthesize restName=_restName;
@property(retain, nonatomic) AddressAnnotation *restAnnotation; // @synthesize restAnnotation=_restAnnotation;
@property(retain, nonatomic) MKMapView *map; // @synthesize map=_map;
- (void)actionSheet:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)showRoute:(id)arg1;
- (void)showEstimateRoute;
- (void)alertView:(id)arg1 hideWithBtnIdx:(long long)arg2;
- (void)loadUserCurrentLocationAnnotation:(CDStruct_c3b9c2ee)arg1;
- (void)loadShopOriginAnnotations;
- (void)cleanAndNavBack;
- (void)onGetPermissionState:(int)arg1;
- (void)onGetNetworkState:(int)arg1;
- (void)centerMapToRest;
- (void)centerMapToUserLoc;
- (void)navBtnClicked;
- (void)navNow;
- (void)refreshPopoutViewDistance:(id)arg1;
- (void)hidePopoutForRestAnno;
- (void)showPopoutForRestAnno:(id)arg1;
- (void)refreshCustomPopoutAnno;
- (void)createCustomedPopoutView;
- (id)mapView:(id)arg1 rendererForOverlay:(id)arg2;
- (id)mapView:(id)arg1 viewForOverlay:(id)arg2;
- (void)mapView:(id)arg1 didAddAnnotationViews:(id)arg2;
- (void)mapView:(id)arg1 didDeselectAnnotationView:(id)arg2;
- (void)mapView:(id)arg1 didSelectAnnotationView:(id)arg2;
- (id)mapView:(id)arg1 viewForAnnotation:(id)arg2;
- (void)mapView:(id)arg1 regionWillChangeAnimated:(_Bool)arg2;
- (void)mapView:(id)arg1 regionDidChangeAnimated:(_Bool)arg2;
- (void)mapView:(id)arg1 didFailToLocateUserWithError:(id)arg2;
- (void)mapView:(id)arg1 didUpdateUserLocation:(id)arg2;
- (void)toGoogleMapWithLat:(double)arg1 lon:(double)arg2;
- (void)promptForChoosingNavApp;
- (void)topViewRightBtnClicked:(id)arg1;
- (void)topViewBackBtnClicked:(id)arg1;
- (void)completeQueryParamsWithTag:(long long)arg1;
- (void)onHttpRequestFail:(long long)arg1 errorMsg:(id)arg2 tag:(long long)arg3;
- (void)onHttpRequestSuccess:(id)arg1 msg:(id)arg2 tag:(long long)arg3;
- (void)reloadLocationData;
- (void)loadData;
- (void)postData;
- (void)onPopFromNavStack;
- (void)onParseNavBackPageParams:(id)arg1;
- (void)_onShowEnd;
- (void)onShow;
- (void)_onWillShowEnd;
- (void)onWillShow;
- (void)onParsePageParams:(id)arg1;
- (void)onClose;
- (void)onCleanData;
- (void)onCreate;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

