//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BaseDetailVc.h"

#import "CSUpdEditPanelDelegate.h"
#import "CSUpdFoodEditPanelDelegate.h"
#import "CSUpdSvPanelDelegate.h"

@class CSUpdEditPanel, CSUpdFoodEditPanel, CSUpdSvPanel, NSMutableArray, NSString, ResFoodPicDataDTO;

@interface RestUploadImageEditVc : BaseDetailVc <CSUpdSvPanelDelegate, CSUpdEditPanelDelegate, CSUpdFoodEditPanelDelegate>
{
    _Bool _needAlertSaveTag;
    CSUpdSvPanel *_ctrlSvPanel;
    CSUpdEditPanel *_ctrlEditPanel;
    CSUpdFoodEditPanel *_ctrlFoodEditPanel;
    NSMutableArray *_list;
    long long _idx;
    ResFoodPicDataDTO *_foodData;
}

@property(retain, nonatomic) ResFoodPicDataDTO *foodData; // @synthesize foodData=_foodData;
@property(nonatomic) _Bool needAlertSaveTag; // @synthesize needAlertSaveTag=_needAlertSaveTag;
@property(nonatomic) long long idx; // @synthesize idx=_idx;
@property(retain, nonatomic) NSMutableArray *list; // @synthesize list=_list;
@property(retain, nonatomic) CSUpdFoodEditPanel *ctrlFoodEditPanel; // @synthesize ctrlFoodEditPanel=_ctrlFoodEditPanel;
@property(retain, nonatomic) CSUpdEditPanel *ctrlEditPanel; // @synthesize ctrlEditPanel=_ctrlEditPanel;
@property(retain, nonatomic) CSUpdSvPanel *ctrlSvPanel; // @synthesize ctrlSvPanel=_ctrlSvPanel;
- (void)saveAndReturn;
- (void)refreshHintPanel;
- (void)refreshEditPanel;
- (void)refreshPanel;
- (void)saveIdxWithIdx:(long long)arg1;
- (void)delOnePanel;
- (void)onUpdFoodEditPanelNeedDel;
- (void)onUpdEditPanelNeedDel;
- (void)onUpdEditPanelEdited;
- (void)onUpdSvPanelChangeIdx:(int)arg1;
- (void)topViewRightBtnClicked:(id)arg1;
- (void)alertView:(id)arg1 hideWithBtnIdx:(long long)arg2;
- (void)topViewBackBtnClicked:(id)arg1;
- (void)onPopFromNavStack;
- (void)onHide;
- (void)onParseNavBackPageParams:(id)arg1;
- (void)onShow;
- (void)onWillShow;
- (void)onParsePageParams:(id)arg1;
- (void)onClose;
- (void)onCleanData;
- (void)onCreate;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

