//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class BaseBizVc, NSString, PageResInfoDto, UITableView;

@interface RestDetailPanelView : UIView <UITableViewDelegate, UITableViewDataSource>
{
    BaseBizVc *nrVc;
    UIView *ctrlContentView;
    UITableView *ctrlTbView;
    PageResInfoDto *dto;
}

@property(retain, nonatomic) PageResInfoDto *dto; // @synthesize dto;
@property(retain, nonatomic) UITableView *ctrlTbView; // @synthesize ctrlTbView;
@property(retain, nonatomic) UIView *ctrlContentView; // @synthesize ctrlContentView;
@property BaseBizVc *nrVc; // @synthesize nrVc;
- (id)newHeadLabelWithTitle:(id)arg1;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (int)defaultRowHeight;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)tableView:(id)arg1 willDisplayCell:(id)arg2 forRowAtIndexPath:(id)arg3;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (void)reCalPos;
- (void)doRefreshPanel;
- (void)refreshPanel:(id)arg1;
- (void)refreshPanelWithNoData;
- (void)doDealloc;
- (void)dealloc;
- (void)doIni;
- (id)initWithVc:(id)arg1 frame:(struct CGRect)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

