//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BaseDetailVc.h"

#import "MKMapViewDelegate.h"

@class AddressAnnotation, CrossHairView, ErrorReportTypeData, MKMapView, MKPointAnnotation, NSString, UIBarButtonItem, UILabel, UIToolbar;

@interface RestMapVc : BaseDetailVc <MKMapViewDelegate>
{
    MKMapView *map;
    AddressAnnotation *aa;
    MKPointAnnotation *anno;
    NSString *restName;
    NSString *restAddress;
    double longitude;
    double latitude;
    double longitudeGoogle;
    double latitudeGoogle;
    CrossHairView *crosshair;
    AddressAnnotation *reportLocation;
    AddressAnnotation *userCurrentLocation;
    _Bool isForErrorReport;
    UIToolbar *hints;
    UILabel *textLbl;
    UIBarButtonItem *submitGeoBtn;
    _Bool canSubmitLocation;
    NSString *restId;
    NSString *email;
    ErrorReportTypeData *errorReportTypeData;
    _Bool isStillLocatingGPSviaBaidu;
    _Bool isShopOriginalLocationEmpty;
    NSString *typeTag;
}

@property(retain, nonatomic) NSString *typeTag; // @synthesize typeTag;
@property(nonatomic) _Bool isShopOriginalLocationEmpty; // @synthesize isShopOriginalLocationEmpty;
@property(nonatomic) _Bool isStillLocatingGPSviaBaidu; // @synthesize isStillLocatingGPSviaBaidu;
@property(retain, nonatomic) ErrorReportTypeData *errorReportTypeData; // @synthesize errorReportTypeData;
@property(retain, nonatomic) NSString *email; // @synthesize email;
@property(retain, nonatomic) NSString *restId; // @synthesize restId;
@property _Bool canSubmitLocation; // @synthesize canSubmitLocation;
@property(retain, nonatomic) UIBarButtonItem *submitGeoBtn; // @synthesize submitGeoBtn;
@property(retain, nonatomic) UILabel *textLbl; // @synthesize textLbl;
@property(retain, nonatomic) UIToolbar *hints; // @synthesize hints;
@property _Bool isForErrorReport; // @synthesize isForErrorReport;
@property(retain, nonatomic) AddressAnnotation *userCurrentLocation; // @synthesize userCurrentLocation;
@property(retain, nonatomic) AddressAnnotation *reportLocation; // @synthesize reportLocation;
@property(retain, nonatomic) CrossHairView *crosshair; // @synthesize crosshair;
@property(nonatomic) double latitudeGoogle; // @synthesize latitudeGoogle;
@property(nonatomic) double longitudeGoogle; // @synthesize longitudeGoogle;
@property(nonatomic) double latitude; // @synthesize latitude;
@property(nonatomic) double longitude; // @synthesize longitude;
@property(retain, nonatomic) NSString *restAddress; // @synthesize restAddress;
@property(retain, nonatomic) NSString *restName; // @synthesize restName;
@property(retain, nonatomic) MKPointAnnotation *anno; // @synthesize anno;
@property(retain, nonatomic) AddressAnnotation *aa; // @synthesize aa;
@property(retain, nonatomic) MKMapView *map; // @synthesize map;
- (void)reloadErrorReportSettingsAfterUserLocation;
- (void)hideReportTools;
- (void)displayReportTools;
- (void)loadUserCurrentLocationAnnotation:(CDStruct_c3b9c2ee)arg1;
- (void)loadReportAnnotations;
- (void)loadShopOriginAnnotations;
- (void)findCityInfoFromBaiduGeo;
- (void)cleanAndNavBack;
- (void)onGetPermissionState:(int)arg1;
- (void)onGetNetworkState:(int)arg1;
- (void)submitGeoChange:(id)arg1;
- (void)alertView:(id)arg1 hideWithBtnIdx:(long long)arg2;
- (id)mapView:(id)arg1 viewForOverlay:(id)arg2;
- (id)mapView:(id)arg1 viewForAnnotation:(id)arg2;
- (void)mapView:(id)arg1 regionDidChangeAnimated:(_Bool)arg2;
- (void)mapView:(id)arg1 didFailToLocateUserWithError:(id)arg2;
- (void)mapView:(id)arg1 didUpdateUserLocation:(id)arg2;
- (void)toGoogleMapWithLat:(double)arg1 lon:(double)arg2;
- (void)topViewRightBtnClicked:(id)arg1;
- (void)topViewBackBtnClicked:(id)arg1;
- (void)completeQueryParamsWithTag:(long long)arg1;
- (void)onHttpRequestFail:(long long)arg1 errorMsg:(id)arg2 tag:(long long)arg3;
- (void)onHttpRequestSuccess:(id)arg1 msg:(id)arg2 tag:(long long)arg3;
- (void)reloadLocationData;
- (void)loadData;
- (void)postData;
- (void)createSubmitPanel;
- (void)onPopFromNavStack;
- (void)onParseNavBackPageParams:(id)arg1;
- (void)_onShowEnd;
- (void)onShow;
- (void)_onWillShowEnd;
- (void)onWillShow;
- (void)onParsePageParams:(id)arg1;
- (void)onClose;
- (void)onCleanData;
- (void)onCreate;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

