//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BaseDto.h"

@class NSMutableArray;

@interface RestPicListDto : BaseDto
{
    _Bool _soIsFoodPicTag;
    int _picViewTag;
    int _soColumnNum;
    NSMutableArray *_list;
    NSMutableArray *_soNextTopList;
}

@property(nonatomic) int soColumnNum; // @synthesize soColumnNum=_soColumnNum;
@property(nonatomic) _Bool soIsFoodPicTag; // @synthesize soIsFoodPicTag=_soIsFoodPicTag;
@property(retain, nonatomic) NSMutableArray *soNextTopList; // @synthesize soNextTopList=_soNextTopList;
@property(nonatomic) int picViewTag; // @synthesize picViewTag=_picViewTag;
@property(retain, nonatomic) NSMutableArray *list; // @synthesize list=_list;
- (int)calPanelWidth;
- (struct CGRect)calPanelFrameAndSetNextTop:(id)arg1;
- (double)calScrollViewContentHeight;
- (void)appendData:(id)arg1;
- (void)appendDataWithStr:(id)arg1;
- (void)setIsForFoodList:(_Bool)arg1;
- (void)dealloc;
- (id)initWithObj:(id)arg1;

@end

