//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BaseSingleListVc.h"

#import "CSRfListCellDelegate.h"
#import "CSRfListKwPanelDelegate.h"
#import "CSRfListSelectPanelDelegate.h"
#import "CSXsMainTopPanelDelegate.h"
#import "CSXsTryLocDelegate.h"
#import "CurrentLocationPanelDelegate.h"

@class CSCurrentLocationPanel, CSRfListKwPanel, CSRfListSelectPanel, CSXsMainTopPanel, CSXsTryLoc, NSString, RfListQueryParams;

@interface RestListVc : BaseSingleListVc <CSRfListSelectPanelDelegate, CSRfListKwPanelDelegate, CSRfListCellDelegate, CurrentLocationPanelDelegate, CSXsTryLocDelegate, CSXsMainTopPanelDelegate>
{
    CSRfListSelectPanel *_ctrlSelectPanel;
    CSRfListKwPanel *_ctrlKwPanel;
    CSCurrentLocationPanel *_ctrlLocPanel;
    CSXsTryLoc *_ctrlTryLoc;
    CSXsMainTopPanel *_ctrlTopPanel;
    RfListQueryParams *_rfParams;
}

@property(retain, nonatomic) RfListQueryParams *rfParams; // @synthesize rfParams=_rfParams;
@property(retain, nonatomic) CSXsMainTopPanel *ctrlTopPanel; // @synthesize ctrlTopPanel=_ctrlTopPanel;
@property(retain, nonatomic) CSXsTryLoc *ctrlTryLoc; // @synthesize ctrlTryLoc=_ctrlTryLoc;
@property(retain, nonatomic) CSCurrentLocationPanel *ctrlLocPanel; // @synthesize ctrlLocPanel=_ctrlLocPanel;
@property(retain, nonatomic) CSRfListKwPanel *ctrlKwPanel; // @synthesize ctrlKwPanel=_ctrlKwPanel;
@property(retain, nonatomic) CSRfListSelectPanel *ctrlSelectPanel; // @synthesize ctrlSelectPanel=_ctrlSelectPanel;
- (void)onMainTopPanelKwClicked:(id)arg1;
- (void)alertHintViewOnClickTryAgainBtn;
- (void)onXsTryLocSuccessWithTag:(int)arg1;
- (void)onRfListKwPanelNeedOpenSearchPanelWithNeedYy:(_Bool)arg1;
- (void)onRfListSelectPanelChangeSelect;
- (void)onRfListCellAddRestBtnClicked;
- (void)adjustPage;
- (void)onTableViewEndDragging;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (void)makeCell:(id)arg1 indexPath:(id)arg2;
- (void)createCell:(id)arg1;
- (void)topViewBackBtnClicked:(id)arg1;
- (void)completeQueryParams;
- (void)onHttpRequestFail:(long long)arg1 errorMsg:(id)arg2 tag:(long long)arg3;
- (void)completeLoadData;
- (void)onGetObj:(id)arg1 fromMemCache:(_Bool)arg2;
- (void)onHttpRequestSuccess:(id)arg1 tag:(long long)arg2;
- (void)loadData;
- (void)onParseNavBackPageParams:(id)arg1;
- (void)onWillShow;
- (void)onParsePageParams:(id)arg1;
- (void)onClose;
- (void)onCleanData;
- (void)onCreate;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

