//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BaseFormVc.h"

#import "CSKeyboardBarDelegate.h"
#import "CSUIComboBoxDelegate.h"
#import "UIActionSheetDelegate.h"
#import "UITextFieldDelegate.h"
#import "UITextViewDelegate.h"

@class CSKeyboardBar, CSUIButton, CSUIComboBox, CSUIPlaceHolderTextView, CSZyInput, CSZyShareButtonSet, NSString, RestUploadData, UIImageView, UITextField, UIView, UploadData;

@interface RestUploadPhotoVc : BaseFormVc <UITextFieldDelegate, UITextViewDelegate, CSUIComboBoxDelegate, CSKeyboardBarDelegate, UIActionSheetDelegate>
{
    _Bool _directShowYyTag;
    UIView *_ctrlImageView;
    UIImageView *_ctrlImage;
    CSUIButton *_ctrlBtnTypeRest;
    CSUIButton *_ctrlBtnTypeFood;
    UIView *_ctrlPriceView;
    CSUIButton *_ctrlBtnSelecteFood;
    CSZyInput *_ctrlFoodName;
    UITextField *_ctrlPriceTextField;
    CSUIComboBox *_ctrlUnitBox;
    UIView *_ctrlMemoView;
    CSUIPlaceHolderTextView *_ctrlMemoTextView;
    CSUIComboBox *_ctrlTalkBox;
    CSZyShareButtonSet *_ctrlSharePanel;
    CSKeyboardBar *_ctrlKeyboardBar;
    RestUploadData *_uploadData;
    UploadData *_dto;
}

@property(retain, nonatomic) UploadData *dto; // @synthesize dto=_dto;
@property(retain, nonatomic) RestUploadData *uploadData; // @synthesize uploadData=_uploadData;
@property(nonatomic) _Bool directShowYyTag; // @synthesize directShowYyTag=_directShowYyTag;
@property(retain, nonatomic) CSKeyboardBar *ctrlKeyboardBar; // @synthesize ctrlKeyboardBar=_ctrlKeyboardBar;
@property(retain, nonatomic) CSZyShareButtonSet *ctrlSharePanel; // @synthesize ctrlSharePanel=_ctrlSharePanel;
@property(retain, nonatomic) CSUIComboBox *ctrlTalkBox; // @synthesize ctrlTalkBox=_ctrlTalkBox;
@property(retain, nonatomic) CSUIPlaceHolderTextView *ctrlMemoTextView; // @synthesize ctrlMemoTextView=_ctrlMemoTextView;
@property(retain, nonatomic) UIView *ctrlMemoView; // @synthesize ctrlMemoView=_ctrlMemoView;
@property(retain, nonatomic) CSUIComboBox *ctrlUnitBox; // @synthesize ctrlUnitBox=_ctrlUnitBox;
@property(retain, nonatomic) UITextField *ctrlPriceTextField; // @synthesize ctrlPriceTextField=_ctrlPriceTextField;
@property(retain, nonatomic) CSZyInput *ctrlFoodName; // @synthesize ctrlFoodName=_ctrlFoodName;
@property(retain, nonatomic) CSUIButton *ctrlBtnSelecteFood; // @synthesize ctrlBtnSelecteFood=_ctrlBtnSelecteFood;
@property(retain, nonatomic) UIView *ctrlPriceView; // @synthesize ctrlPriceView=_ctrlPriceView;
@property(retain, nonatomic) CSUIButton *ctrlBtnTypeFood; // @synthesize ctrlBtnTypeFood=_ctrlBtnTypeFood;
@property(retain, nonatomic) CSUIButton *ctrlBtnTypeRest; // @synthesize ctrlBtnTypeRest=_ctrlBtnTypeRest;
@property(retain, nonatomic) UIImageView *ctrlImage; // @synthesize ctrlImage=_ctrlImage;
@property(retain, nonatomic) UIView *ctrlImageView; // @synthesize ctrlImageView=_ctrlImageView;
- (void)backToPrevPage:(id)arg1;
- (void)hideKeyboard;
- (void)fillUnitArray;
- (id)newComboButton:(struct CGRect)arg1;
- (void)btnClick_UploadType:(id)arg1;
- (void)btnClick_SelectFood:(id)arg1;
- (void)btnClick_Submit;
- (void)loadUploadData;
- (void)changePageTitleAndLayout;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (void)alertView:(id)arg1 hideWithBtnIdx:(long long)arg2;
- (void)keyboard:(id)arg1;
- (void)keyboardBarDidTapHideBtn:(id)arg1;
- (void)yyBtnClicked:(id)arg1;
- (void)textViewDidEndEditing:(id)arg1;
- (void)textViewDidBeginEditing:(id)arg1;
- (_Bool)textView:(id)arg1 shouldChangeTextInRange:(struct _NSRange)arg2 replacementText:(id)arg3;
- (_Bool)textFieldShouldReturn:(id)arg1;
- (void)textFieldDidEndEditing:(id)arg1;
- (void)textFieldDidBeginEditing:(id)arg1;
- (_Bool)textField:(id)arg1 shouldChangeCharactersInRange:(struct _NSRange)arg2 replacementString:(id)arg3;
- (void)comboBoxBeforeShowPicker:(id)arg1;
- (void)comboBox:(id)arg1 didSelected:(long long)arg2 selectId:(id)arg3 selectName:(id)arg4;
- (void)topViewRightBtnClicked:(id)arg1;
- (void)topViewBackBtnClicked:(id)arg1;
- (void)completeQueryParams;
- (void)onHttpRequestFail:(long long)arg1 errorMsg:(id)arg2 tag:(long long)arg3;
- (void)onHttpRequestSuccess:(id)arg1 tag:(long long)arg2;
- (void)onPopFromNavStack;
- (void)onParseNavBackPageParams:(id)arg1;
- (void)onParsePageParams:(id)arg1;
- (void)onWillShow;
- (void)onClose;
- (void)onCleanData;
- (void)onCreate;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

