//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray, NSString;

@interface RfTypeListDto : NSObject
{
    _Bool _s;
    NSString *_u;
    NSString *_n;
    NSMutableArray *_list;
}

@property(retain, nonatomic) NSMutableArray *list; // @synthesize list=_list;
@property(nonatomic) _Bool s; // @synthesize s=_s;
@property(retain, nonatomic) NSString *n; // @synthesize n=_n;
@property(retain, nonatomic) NSString *u; // @synthesize u=_u;
- (void)transToList:(id)arg1;
- (void)dealloc;
- (id)initWithObj:(id)arg1;

@end

