//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface SelDrData : NSObject
{
    int _typeTag;
    NSString *_regionId;
    NSString *_regionName;
    NSString *_districtId;
    NSString *_districtName;
    NSString *_lon;
    NSString *_lat;
}

@property(retain, nonatomic) NSString *lat; // @synthesize lat=_lat;
@property(retain, nonatomic) NSString *lon; // @synthesize lon=_lon;
@property(retain, nonatomic) NSString *districtName; // @synthesize districtName=_districtName;
@property(retain, nonatomic) NSString *districtId; // @synthesize districtId=_districtId;
@property(retain, nonatomic) NSString *regionName; // @synthesize regionName=_regionName;
@property(retain, nonatomic) NSString *regionId; // @synthesize regionId=_regionId;
@property(nonatomic) int typeTag; // @synthesize typeTag=_typeTag;
- (void)restAll;
- (void)dealloc;
- (id)initWithDefault;
- (id)initWithLon:(float)arg1 lat:(float)arg2;
- (id)initWithRid:(id)arg1 rname:(id)arg2 did:(id)arg3 dname:(id)arg4;

@end

