//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BaseSelectCityVc.h"

@class CityData, NSTimer;

@interface SelectCityVc : BaseSelectCityVc
{
    NSTimer *ctrlLocTimer;
    CityData *cd;
    int locTag;
    int locTryNum;
}

@property(nonatomic) int locTryNum; // @synthesize locTryNum;
@property(nonatomic) int locTag; // @synthesize locTag;
@property(retain, nonatomic) CityData *cd; // @synthesize cd;
@property(retain, nonatomic) NSTimer *ctrlLocTimer; // @synthesize ctrlLocTimer;
- (void)toMoreCityPage;
- (void)refeshTableByCityId:(id)arg1;
- (void)handleLocTimer:(id)arg1;
- (void)subTableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (void)makeCell:(id)arg1 indexPath:(id)arg2;
- (long long)subTableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (id)subTableView:(id)arg1 titleForHeaderInSection:(long long)arg2;
- (long long)subNumberOfSectionsInTableView:(id)arg1;
- (void)topViewRightBtnClicked:(id)arg1;
- (void)topViewBackBtnClicked:(id)arg1;
- (void)completeQueryParams;
- (void)onHttpRequestFail:(long long)arg1 errorMsg:(id)arg2;
- (void)onHttpRequestSuccess:(id)arg1;
- (void)loadData;
- (void)onPopFromNavStack;
- (void)onHide;
- (void)onParseNavBackPageParams:(id)arg1;
- (void)onShow;
- (void)onWillShow;
- (void)onParsePageParams:(id)arg1;
- (void)onClose;
- (void)onCleanData;
- (void)onCreate;

@end

