//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class GiftInfoData, MainPageData, NSString;

@interface ShakeGiftData : NSObject
{
    _Bool _haveGiftTag;
    int _noGiftTypeTag;
    GiftInfoData *_giftInfo;
    NSString *_noGiftHint;
    MainPageData *_mainPageData;
}

@property(retain, nonatomic) MainPageData *mainPageData; // @synthesize mainPageData=_mainPageData;
@property(retain, nonatomic) NSString *noGiftHint; // @synthesize noGiftHint=_noGiftHint;
@property(nonatomic) int noGiftTypeTag; // @synthesize noGiftTypeTag=_noGiftTypeTag;
@property(retain, nonatomic) GiftInfoData *giftInfo; // @synthesize giftInfo=_giftInfo;
@property(nonatomic) _Bool haveGiftTag; // @synthesize haveGiftTag=_haveGiftTag;
- (void)unitTest;
- (void)dealloc;
- (id)initWithObj:(id)arg1;

@end

