//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface ShareInfoData : NSObject
{
    NSString *_shareSmsDetail;
    NSString *_shareEmailDetail;
    NSString *_shareWeiboUuid;
    NSString *_shareWeiboDetail;
    NSString *_shareWeixinIconUrl;
    NSString *_shareWeixinDetailUrl;
    NSString *_shareWeixinName;
    NSString *_shareWeixinDetail;
}

@property(retain, nonatomic) NSString *shareWeixinDetail; // @synthesize shareWeixinDetail=_shareWeixinDetail;
@property(retain, nonatomic) NSString *shareWeixinName; // @synthesize shareWeixinName=_shareWeixinName;
@property(retain, nonatomic) NSString *shareWeixinDetailUrl; // @synthesize shareWeixinDetailUrl=_shareWeixinDetailUrl;
@property(retain, nonatomic) NSString *shareWeixinIconUrl; // @synthesize shareWeixinIconUrl=_shareWeixinIconUrl;
@property(retain, nonatomic) NSString *shareWeiboDetail; // @synthesize shareWeiboDetail=_shareWeiboDetail;
@property(retain, nonatomic) NSString *shareWeiboUuid; // @synthesize shareWeiboUuid=_shareWeiboUuid;
@property(retain, nonatomic) NSString *shareEmailDetail; // @synthesize shareEmailDetail=_shareEmailDetail;
@property(retain, nonatomic) NSString *shareSmsDetail; // @synthesize shareSmsDetail=_shareSmsDetail;
- (void)unitTest;
- (void)dealloc;
- (id)initWithObj:(id)arg1;

@end

