//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray, NSString;

@interface SortedFoodListData : NSObject
{
    NSString *firstLetter;
    NSMutableArray *list;
}

@property(retain, nonatomic) NSMutableArray *list; // @synthesize list;
@property(retain, nonatomic) NSString *firstLetter; // @synthesize firstLetter;
- (void)dealloc;
- (id)initWithObj:(id)arg1;

@end

