//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TAGPBGeneratedMessage.h"

@class NSString, TAGPResource;

@interface TAGPContainer : TAGPBGeneratedMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(retain, nonatomic) NSString *containerId; // @dynamic containerId;
@property(nonatomic) _Bool hasContainerId; // @dynamic hasContainerId;
@property(nonatomic) _Bool hasJsResource; // @dynamic hasJsResource;
@property(nonatomic) _Bool hasState; // @dynamic hasState;
@property(nonatomic) _Bool hasVersion; // @dynamic hasVersion;
@property(retain, nonatomic) TAGPResource *jsResource; // @dynamic jsResource;
@property(nonatomic) int state; // @dynamic state;
@property(retain, nonatomic) NSString *version; // @dynamic version;

@end

