//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray, TakeoutMenuTypeData;

@interface TakeoutMenuList2DTO : NSObject
{
    TakeoutMenuTypeData *_typeData;
    NSMutableArray *_list;
}

@property(retain, nonatomic) NSMutableArray *list; // @synthesize list=_list;
@property(retain, nonatomic) TakeoutMenuTypeData *typeData; // @synthesize typeData=_typeData;
- (void)unitTest;
- (void)dealloc;
- (id)initWithObj:(id)arg1;

@end

