//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface TakeoutOnlinePayStateData : NSObject
{
    _Bool _succTag;
    NSString *_msg;
    NSString *_btnName;
}

@property(retain, nonatomic) NSString *btnName; // @synthesize btnName=_btnName;
@property(retain, nonatomic) NSString *msg; // @synthesize msg=_msg;
@property(nonatomic) _Bool succTag; // @synthesize succTag=_succTag;
- (void)unitTest;
- (void)dealloc;
- (id)initWithObj:(id)arg1;

@end

