//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BaseFormVc.h"

#import "UITextViewDelegate.h"

@class CSTkStarPanel, CSUIButton, CSZyMemo, CSZyShareButtonSet, NSString, TakeoutMenuSelPackDTO, UILabel;

@interface TakeoutCommentOrderPostVc : BaseFormVc <UITextViewDelegate>
{
    UILabel *_ctrlTitleLabel;
    CSTkStarPanel *_ctrlStarPanel;
    CSZyMemo *_ctrlComment;
    CSZyShareButtonSet *_ctrlShare;
    CSUIButton *_ctrlBtn;
    TakeoutMenuSelPackDTO *_dto;
    NSString *_orderId;
}

@property(retain, nonatomic) NSString *orderId; // @synthesize orderId=_orderId;
@property(retain, nonatomic) TakeoutMenuSelPackDTO *dto; // @synthesize dto=_dto;
@property(retain, nonatomic) CSUIButton *ctrlBtn; // @synthesize ctrlBtn=_ctrlBtn;
@property(retain, nonatomic) CSZyShareButtonSet *ctrlShare; // @synthesize ctrlShare=_ctrlShare;
@property(retain, nonatomic) CSZyMemo *ctrlComment; // @synthesize ctrlComment=_ctrlComment;
@property(retain, nonatomic) CSTkStarPanel *ctrlStarPanel; // @synthesize ctrlStarPanel=_ctrlStarPanel;
@property(retain, nonatomic) UILabel *ctrlTitleLabel; // @synthesize ctrlTitleLabel=_ctrlTitleLabel;
- (void)unitTest;
- (void)hideKeyboard;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (void)submitBtnClicked;
- (void)alertView:(id)arg1 hideWithBtnIdx:(long long)arg2;
- (void)textViewDidBeginEditing:(id)arg1;
- (_Bool)textView:(id)arg1 shouldChangeTextInRange:(struct _NSRange)arg2 replacementText:(id)arg3;
- (void)completeQueryParamsWithTag:(long long)arg1;
- (void)onHttpRequestFail:(long long)arg1 errorMsg:(id)arg2;
- (void)completeLoadData;
- (void)onHttpRequestSuccess:(id)arg1 tag:(long long)arg2;
- (void)postData;
- (void)loadData;
- (void)topViewBackBtnClicked:(id)arg1;
- (void)onPopFromNavStack;
- (void)onHide;
- (void)onParseNavBackPageParams:(id)arg1;
- (void)onShow;
- (void)onWillShow;
- (void)onParsePageParams:(id)arg1;
- (void)onClose;
- (void)onCleanData;
- (void)onCreate;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

