//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray, NSString;

@interface TakeoutMenuListPack2DTO : NSObject
{
    _Bool _canOrderTag;
    NSString *_takeoutId;
    NSString *_takeoutName;
    NSMutableArray *_advList;
    NSMutableArray *_list;
    double _sendLimitPrice;
    NSString *_hintForCanNotOrder;
}

@property(retain, nonatomic) NSString *hintForCanNotOrder; // @synthesize hintForCanNotOrder=_hintForCanNotOrder;
@property(nonatomic) _Bool canOrderTag; // @synthesize canOrderTag=_canOrderTag;
@property(nonatomic) double sendLimitPrice; // @synthesize sendLimitPrice=_sendLimitPrice;
@property(retain, nonatomic) NSMutableArray *list; // @synthesize list=_list;
@property(retain, nonatomic) NSMutableArray *advList; // @synthesize advList=_advList;
@property(retain, nonatomic) NSString *takeoutName; // @synthesize takeoutName=_takeoutName;
@property(retain, nonatomic) NSString *takeoutId; // @synthesize takeoutId=_takeoutId;
- (void)unitTest;
- (void)dealloc;
- (id)initWithObj:(id)arg1;

@end

