//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray;

@interface TakeoutIndexPageData : NSObject
{
    NSMutableArray *_advList;
    NSMutableArray *_typeList;
}

@property(retain, nonatomic) NSMutableArray *typeList; // @synthesize typeList=_typeList;
@property(retain, nonatomic) NSMutableArray *advList; // @synthesize advList=_advList;
- (void)unitTest;
- (id)newDic;
- (void)dealloc;
- (id)initWithObj:(id)arg1;

@end

