//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class BaseSingleListVc, NSString, TakeoutListDTO;

@interface TkListParams : NSObject
{
    _Bool _forMapTag;
    _Bool _isCurrentUserGpsTag;
    _Bool _queryOnMapMoveTag;
    int _gpsTypeTag;
    BaseSingleListVc *_nrVc;
    TakeoutListDTO *_dto;
    NSString *_gpsRect;
    double _lonForOnMapMove;
    double _latForOnMapMove;
    double _longitude;
    double _latitude;
    NSString *_positionName;
    NSString *_keywords;
    NSString *_typeId;
    NSString *_sendLimitId;
    double _mapZoomLevel;
}

@property(nonatomic) double mapZoomLevel; // @synthesize mapZoomLevel=_mapZoomLevel;
@property(retain, nonatomic) NSString *sendLimitId; // @synthesize sendLimitId=_sendLimitId;
@property(retain, nonatomic) NSString *typeId; // @synthesize typeId=_typeId;
@property(retain, nonatomic) NSString *keywords; // @synthesize keywords=_keywords;
@property(retain, nonatomic) NSString *positionName; // @synthesize positionName=_positionName;
@property(nonatomic) double latitude; // @synthesize latitude=_latitude;
@property(nonatomic) double longitude; // @synthesize longitude=_longitude;
@property(nonatomic) double latForOnMapMove; // @synthesize latForOnMapMove=_latForOnMapMove;
@property(nonatomic) double lonForOnMapMove; // @synthesize lonForOnMapMove=_lonForOnMapMove;
@property(nonatomic) _Bool queryOnMapMoveTag; // @synthesize queryOnMapMoveTag=_queryOnMapMoveTag;
@property(retain, nonatomic) NSString *gpsRect; // @synthesize gpsRect=_gpsRect;
@property int gpsTypeTag; // @synthesize gpsTypeTag=_gpsTypeTag;
@property(nonatomic) _Bool isCurrentUserGpsTag; // @synthesize isCurrentUserGpsTag=_isCurrentUserGpsTag;
@property(nonatomic) _Bool forMapTag; // @synthesize forMapTag=_forMapTag;
@property(retain, nonatomic) TakeoutListDTO *dto; // @synthesize dto=_dto;
@property BaseSingleListVc *nrVc; // @synthesize nrVc=_nrVc;
- (double)defaultZoomLevel;
- (void)completeQueryParams;
- (void)resetParams;
- (void)resetDto;
- (void)reset;
- (void)dealloc;
- (id)initWithVc:(id)arg1;

@end

