//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TOChatService.h"

@interface TOChatService (InfoCriteria)
- (_Bool)onlyCriteriaOfName;
- (void)cleanNewslyAddedCriteria;
- (void)rejectNewslyAddedCriteria;
- (void)registerNewlyAddedCriteria:(id)arg1 forCriteria:(id)arg2;
- (void)rollbackNewlyAddedCriterionVals:(id)arg1 forCriterion:(id)arg2;
- (void)registerNewlyAddedCriterion:(id)arg1 forCriteria:(id)arg2;
- (_Bool)hasNewlyAddedCriteria;
- (_Bool)hasNewlyAddedCriterionForKey:(id)arg1;
- (void)appendValue:(id)arg1 forCriteria:(id)arg2;
- (void)cleanValueForCriteria:(id)arg1 elemsInArray:(id)arg2 cleanRecentAdded:(_Bool)arg3;
- (void)cleanValueForCriteria:(id)arg1 elemsInArray:(id)arg2;
- (void)cleanValueForCriteria:(id)arg1;
- (id)valueFromCriteriaOutOfArray:(id)arg1;
- (id)valueFromCriteria:(id)arg1;
- (void)cleanRestFilteringCriteria;
- (_Bool)hasRestFilteringCriteria;
- (void)installRestCriteria;
- (id)humanizeReadTime:(id)arg1;
- (id)humanizeReadDate:(id)arg1;
- (id)reconfirmStringForBookingKey:(id)arg1;
- (_Bool)hasFinalConfirmUpdated;
- (void)cleanPreorderAccuInfoForConfirm;
- (_Bool)ifAccumulatedAnyBookingInfo;
- (void)updatePreorderAccuInfoForKey:(id)arg1 withNewValue:(id)arg2;
- (void)installPreorderAccuInfo;
- (void)updateCurrentCriteria:(_Bool)arg1;
- (void)confirmCurrentCriteria;
- (_Bool)isSingleValCriterion:(id)arg1;
- (_Bool)isMultiValsCriterion:(id)arg1;
- (void)confirmOverridingCriteria;
- (_Bool)ifOverridingPreviousCriteria;
- (void)addRestFilteringCriteriaVia:(id)arg1 forCriterion:(id)arg2 allowMultiVals:(_Bool)arg3;
- (void)addRestFilteringCriteriaVia:(id)arg1 forCriterion:(id)arg2;
- (_Bool)sameWordInOtherSlots:(id)arg1;
- (id)restAttributesAvailable:(id)arg1;
- (_Bool)hasRestAttributeForInquery:(id)arg1;
- (_Bool)hasEnoughtRestFilteringInfo;
- (id)assembleCriteriaForInformingUser;
- (id)collectAllValidRestFilterCriteria;
@end

