//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BaseHttpView.h"

@class NSMutableArray, NSMutableDictionary, NSObject<TOChatServiceRestCriteriaUIAugmentedDelegate>, NSObject<TOChatServiceRestDataRefreshWithFirstBatchUIAugmentedDelegate>, NSObject<TOChatServiceSoundAugmentedDelegate>, NSObject<TOChatServiceUIAugmentedDelegate>, NSObject<TOChatServiceVoiceBtnUIAugmentedDelegate>, NSString, OrderViaVoiceData, RestListDataForVoice, RestListDtoForVoice, RestListDtoForVoiceLiveSupport;

@interface TOChatService : BaseHttpView
{
    _Bool _alreadyReachThreshold;
    _Bool _isOnFirstPage;
    _Bool _isInterruptedByUserTag;
    _Bool _showVoiceControlBtn;
    _Bool _isBookingIntended;
    _Bool _alreadyDetermineTheRest;
    _Bool _isRotatableTypeInProgressTag;
    _Bool _isRotatableTypeInFirstLoop;
    _Bool _hasSuggestShakeForTopRestList;
    _Bool _hasMetTopRestListWithData;
    _Bool _loadingRowHideTag;
    _Bool _shouldCleanAndReload;
    int _interactMethod;
    int _currentChatFocus;
    int _queryTag;
    int _cntTimesForDetermineTheRest;
    int _cntTimesOfUserVoiceSynForLiveSupport;
    int _currentBatchRestStartIndex;
    int _idxCurrentRotatableType;
    NSObject<TOChatServiceSoundAugmentedDelegate> *_soundExtDelegate;
    NSObject<TOChatServiceUIAugmentedDelegate> *_uiExtDelegate;
    NSObject<TOChatServiceRestCriteriaUIAugmentedDelegate> *_uiRestCriteriaDelegate;
    NSObject<TOChatServiceVoiceBtnUIAugmentedDelegate> *_uiVoiceBtnDelegate;
    NSObject<TOChatServiceRestDataRefreshWithFirstBatchUIAugmentedDelegate> *_uiFirstBatchRestDataDelegate;
    NSString *_rawText;
    NSMutableArray *_arrAllMsg;
    NSMutableArray *_arrXmsJustSaid;
    NSMutableArray *_arrQueuedMsgs;
    NSMutableArray *_arrConversations;
    RestListDtoForVoice *_queryConstDto;
    OrderViaVoiceData *_preorderKnowledge;
    OrderViaVoiceData *_preorderLastUpdate;
    RestListDtoForVoice *_currentRestQueryDto;
    RestListDtoForVoice *_previousRestQueryDto;
    NSMutableArray *_arrKnownCusines;
    RestListDataForVoice *_lastMentionedRest;
    RestListDtoForVoiceLiveSupport *_restListOfLiveSupport;
    NSMutableDictionary *_preorderAccuInfo;
    NSMutableDictionary *_dictRestFilteringCriteria;
    NSString *_criterionToBeConfirmed;
    NSMutableDictionary *_dictLastAddedCriteria;
    NSMutableArray *_dataShownOnScreen;
    NSMutableArray *_arrSearchHistory;
    NSMutableArray *_arrRotatableTypeList;
    long long _startIndex;
    long long _rowCount;
}

+ (id)instance;
@property _Bool shouldCleanAndReload; // @synthesize shouldCleanAndReload=_shouldCleanAndReload;
@property _Bool loadingRowHideTag; // @synthesize loadingRowHideTag=_loadingRowHideTag;
@property long long rowCount; // @synthesize rowCount=_rowCount;
@property long long startIndex; // @synthesize startIndex=_startIndex;
@property(nonatomic) _Bool hasMetTopRestListWithData; // @synthesize hasMetTopRestListWithData=_hasMetTopRestListWithData;
@property(nonatomic) _Bool hasSuggestShakeForTopRestList; // @synthesize hasSuggestShakeForTopRestList=_hasSuggestShakeForTopRestList;
@property(nonatomic) _Bool isRotatableTypeInFirstLoop; // @synthesize isRotatableTypeInFirstLoop=_isRotatableTypeInFirstLoop;
@property(nonatomic) _Bool isRotatableTypeInProgressTag; // @synthesize isRotatableTypeInProgressTag=_isRotatableTypeInProgressTag;
@property(nonatomic) int idxCurrentRotatableType; // @synthesize idxCurrentRotatableType=_idxCurrentRotatableType;
@property(retain, nonatomic) NSMutableArray *arrRotatableTypeList; // @synthesize arrRotatableTypeList=_arrRotatableTypeList;
@property(retain, nonatomic) NSMutableArray *arrSearchHistory; // @synthesize arrSearchHistory=_arrSearchHistory;
@property(retain, nonatomic) NSMutableArray *dataShownOnScreen; // @synthesize dataShownOnScreen=_dataShownOnScreen;
@property(retain, nonatomic) NSMutableDictionary *dictLastAddedCriteria; // @synthesize dictLastAddedCriteria=_dictLastAddedCriteria;
@property int currentBatchRestStartIndex; // @synthesize currentBatchRestStartIndex=_currentBatchRestStartIndex;
@property(retain, nonatomic) NSString *criterionToBeConfirmed; // @synthesize criterionToBeConfirmed=_criterionToBeConfirmed;
@property(retain, nonatomic) NSMutableDictionary *dictRestFilteringCriteria; // @synthesize dictRestFilteringCriteria=_dictRestFilteringCriteria;
@property(retain, nonatomic) NSMutableDictionary *preorderAccuInfo; // @synthesize preorderAccuInfo=_preorderAccuInfo;
@property(retain, nonatomic) RestListDtoForVoiceLiveSupport *restListOfLiveSupport; // @synthesize restListOfLiveSupport=_restListOfLiveSupport;
@property int cntTimesOfUserVoiceSynForLiveSupport; // @synthesize cntTimesOfUserVoiceSynForLiveSupport=_cntTimesOfUserVoiceSynForLiveSupport;
@property int cntTimesForDetermineTheRest; // @synthesize cntTimesForDetermineTheRest=_cntTimesForDetermineTheRest;
@property _Bool alreadyDetermineTheRest; // @synthesize alreadyDetermineTheRest=_alreadyDetermineTheRest;
@property _Bool isBookingIntended; // @synthesize isBookingIntended=_isBookingIntended;
@property(retain, nonatomic) RestListDataForVoice *lastMentionedRest; // @synthesize lastMentionedRest=_lastMentionedRest;
@property(retain, nonatomic) NSMutableArray *arrKnownCusines; // @synthesize arrKnownCusines=_arrKnownCusines;
@property(retain, nonatomic) RestListDtoForVoice *previousRestQueryDto; // @synthesize previousRestQueryDto=_previousRestQueryDto;
@property(retain, nonatomic) RestListDtoForVoice *currentRestQueryDto; // @synthesize currentRestQueryDto=_currentRestQueryDto;
@property(retain, nonatomic) OrderViaVoiceData *preorderLastUpdate; // @synthesize preorderLastUpdate=_preorderLastUpdate;
@property(retain, nonatomic) OrderViaVoiceData *preorderKnowledge; // @synthesize preorderKnowledge=_preorderKnowledge;
@property(retain, nonatomic) RestListDtoForVoice *queryConstDto; // @synthesize queryConstDto=_queryConstDto;
@property(retain, nonatomic) NSMutableArray *arrConversations; // @synthesize arrConversations=_arrConversations;
@property(retain, nonatomic) NSMutableArray *arrQueuedMsgs; // @synthesize arrQueuedMsgs=_arrQueuedMsgs;
@property(retain, nonatomic) NSMutableArray *arrXmsJustSaid; // @synthesize arrXmsJustSaid=_arrXmsJustSaid;
@property(retain, nonatomic) NSMutableArray *arrAllMsg; // @synthesize arrAllMsg=_arrAllMsg;
@property(retain, nonatomic) NSString *rawText; // @synthesize rawText=_rawText;
@property _Bool showVoiceControlBtn; // @synthesize showVoiceControlBtn=_showVoiceControlBtn;
@property int queryTag; // @synthesize queryTag=_queryTag;
@property _Bool isInterruptedByUserTag; // @synthesize isInterruptedByUserTag=_isInterruptedByUserTag;
@property(nonatomic) _Bool isOnFirstPage; // @synthesize isOnFirstPage=_isOnFirstPage;
@property _Bool alreadyReachThreshold; // @synthesize alreadyReachThreshold=_alreadyReachThreshold;
@property int currentChatFocus; // @synthesize currentChatFocus=_currentChatFocus;
@property int interactMethod; // @synthesize interactMethod=_interactMethod;
@property NSObject<TOChatServiceRestDataRefreshWithFirstBatchUIAugmentedDelegate> *uiFirstBatchRestDataDelegate; // @synthesize uiFirstBatchRestDataDelegate=_uiFirstBatchRestDataDelegate;
@property NSObject<TOChatServiceVoiceBtnUIAugmentedDelegate> *uiVoiceBtnDelegate; // @synthesize uiVoiceBtnDelegate=_uiVoiceBtnDelegate;
@property NSObject<TOChatServiceRestCriteriaUIAugmentedDelegate> *uiRestCriteriaDelegate; // @synthesize uiRestCriteriaDelegate=_uiRestCriteriaDelegate;
@property NSObject<TOChatServiceUIAugmentedDelegate> *uiExtDelegate; // @synthesize uiExtDelegate=_uiExtDelegate;
@property NSObject<TOChatServiceSoundAugmentedDelegate> *soundExtDelegate; // @synthesize soundExtDelegate=_soundExtDelegate;
- (id)findTopRestTypeNameByValue:(id)arg1;
- (void)markAlreadyDetermineTheRestAndChangeFocus;
- (_Bool)accumulateKnowledgeForRestFiltering:(id)arg1;
- (void)askQuestionWithPrecidency;
- (void)noRestNameGuessing;
- (_Bool)hasRestCriteria:(id)arg1;
- (void)continueAskForPitchOrSuggest;
- (void)userDidSelectTheRest:(id)arg1;
- (id)latestMentionedRest_BoolSelect_Rest;
- (void)focusOnRestBoolSelection;
- (void)focusReassureTargetOneRestInFiltering;
- (void)focusOnBookingDetail:(id)arg1 ifAccuBookingInfo:(_Bool)arg2;
- (void)focusOnConfirmFinalBooking;
- (_Bool)accumulateKnowledgeForBooking:(id)arg1;
- (_Bool)processEntityInquery:(id)arg1;
- (void)keepFilteringRest;
- (void)chatAndAskForMore:(id)arg1;
- (id)processAndCleanRawSemanticDict:(id)arg1;
- (void)processSemanticText:(id)arg1;
- (void)testInstallTestData;
- (void)processSynthesizedVoice;
- (_Bool)isLiveSupportReady;
- (void)closeSession;
- (void)reset;
- (void)setup;
- (void)dealloc;
- (id)init;

@end

