//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TOChatService.h"

@interface TOChatService (QueryInfrastructure)
- (void)loadLiveSupportRestSuggestion;
- (void)loadNextTypeOfTopRest;
- (void)loadDataForRestList;
- (void)loadDataAccordingly;
- (void)cancelRequest;
- (id)cusineNamesClean:(id)arg1;
- (void)installKnownCusine;
- (void)setPageSizeParams:(int)arg1;
- (void)setStartIndexParams;
- (void)changeStartIndex:(id)arg1;
- (void)prepQueryParamsForCriterionKeyOutOfArray:(id)arg1;
- (void)prepQueryParamsForCriterionKey:(id)arg1;
- (void)processWhenRequestError:(id)arg1 code:(int)arg2 tag:(long long)arg3;
- (void)completeQueryParams;
- (void)onHttpRequestFail:(long long)arg1 errorMsg:(id)arg2;
- (void)completeLoadData;
- (void)onHttpRequestSuccess:(id)arg1 tag:(long long)arg2;
- (void)loadDataByCleanExisting;
- (void)loadLiveSupportRestList;
- (void)loadQueryParamData;
- (void)loadData;
@end

