//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "TOChatServiceRestCriteriaUIAugmentedDelegate.h"

@class BaseLayoutSupportVc, NSMutableArray, NSObject<TORestFilteringsViewDelegate>, NSString;

@interface TORestFilteringsView : UIView <TOChatServiceRestCriteriaUIAugmentedDelegate>
{
    _Bool _isHidingTag;
    NSObject<TORestFilteringsViewDelegate> *_delegate;
    BaseLayoutSupportVc *_nrVc;
    NSMutableArray *_arrAllCriteriaBtns;
}

+ (struct CGSize)calcKwBtnSizeFor:(id)arg1;
@property _Bool isHidingTag; // @synthesize isHidingTag=_isHidingTag;
@property(retain, nonatomic) NSMutableArray *arrAllCriteriaBtns; // @synthesize arrAllCriteriaBtns=_arrAllCriteriaBtns;
@property BaseLayoutSupportVc *nrVc; // @synthesize nrVc=_nrVc;
@property NSObject<TORestFilteringsViewDelegate> *delegate; // @synthesize delegate=_delegate;
- (void)finishHideAnimation;
- (void)handleHidePanel;
- (id)humanize:(id)arg1 forKey:(id)arg2;
- (void)reloadUI:(id)arg1;
- (void)reloadUI;
- (void)configBtnStyle:(id)arg1;
- (void)clickedToRemove:(id)arg1;
- (void)onTOChatServiceUIforRestCriteriaReload:(id)arg1;
- (void)open;
- (void)addNewCriterionBtn:(id)arg1;
- (void)reset;
- (void)dealloc;
- (id)initWithVc:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

