//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface TOSettingDataUtil : NSObject
{
    _Bool _isUsingVoiceControlBtn;
    _Bool _isConversationVerbose;
    _Bool _isShowingConversationView;
    _Bool _isShowingParenthesisText;
    _Bool _isLinVoice;
    _Bool _isRecSoundHint;
    _Bool _isRecVisualHint;
    _Bool _isAutoRecordInP2;
    _Bool _isCriteriaHinted;
    _Bool _isShakeBeginSoundOn;
    int _voiceUsed;
}

+ (id)instance;
@property(nonatomic) int voiceUsed; // @synthesize voiceUsed=_voiceUsed;
@property(nonatomic) _Bool isShakeBeginSoundOn; // @synthesize isShakeBeginSoundOn=_isShakeBeginSoundOn;
@property(nonatomic) _Bool isCriteriaHinted; // @synthesize isCriteriaHinted=_isCriteriaHinted;
@property(nonatomic) _Bool isAutoRecordInP2; // @synthesize isAutoRecordInP2=_isAutoRecordInP2;
@property(nonatomic) _Bool isRecVisualHint; // @synthesize isRecVisualHint=_isRecVisualHint;
@property(nonatomic) _Bool isRecSoundHint; // @synthesize isRecSoundHint=_isRecSoundHint;
@property(nonatomic) _Bool isLinVoice; // @synthesize isLinVoice=_isLinVoice;
@property(nonatomic) _Bool isShowingParenthesisText; // @synthesize isShowingParenthesisText=_isShowingParenthesisText;
@property(nonatomic) _Bool isShowingConversationView; // @synthesize isShowingConversationView=_isShowingConversationView;
@property(nonatomic) _Bool isConversationVerbose; // @synthesize isConversationVerbose=_isConversationVerbose;
@property(nonatomic) _Bool isUsingVoiceControlBtn; // @synthesize isUsingVoiceControlBtn=_isUsingVoiceControlBtn;
- (void)save;
- (void)saveSetting:(id)arg1 value:(_Bool)arg2;
- (_Bool)readSetting:(id)arg1 OrSaveDefault:(_Bool)arg2;
- (void)reset;
- (void)setup;
- (void)dealloc;
- (id)init;

@end

