//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UPOMP_ViewController.h"

#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"
#import "UPOMP_KaNetDelegate.h"

@class NSMutableArray, NSString, UIButton, UIImageView, UILabel, UITableView, UITableViewCell, UPOMP_CheckPhoneCellViewController, UPOMP_KaNet, UPOMP_PasswordCellViewController, UPOMP_PhoneNumCellViewController;

@interface UPOMP_ChangePhoneViewController : UPOMP_ViewController <UITableViewDataSource, UITableViewDelegate, UPOMP_KaNetDelegate>
{
    UITableView *myTabelView;
    NSMutableArray *cellArray;
    UITableViewCell *infoTopCell;
    UIImageView *infoTopBG;
    UITableViewCell *phoneCell;
    UIImageView *phoneBG;
    UIImageView *phoneLeftBG;
    UILabel *phoneText;
    UILabel *phoneValue;
    UIImageView *phoneIcon;
    UITableViewCell *infoBottomCell;
    UIImageView *infoBottomBG;
    UITableViewCell *infoTopCell2;
    UIImageView *infoTopBG2;
    UITableViewCell *userNameCell;
    UIImageView *userNameBG;
    UIImageView *userNameLeftBG;
    UILabel *userNameText;
    UILabel *userNameValue;
    UIImageView *userNameIcon;
    UITableViewCell *infoBottomCell2;
    UIImageView *infoBottomBG2;
    UITableViewCell *finishCell;
    UIButton *finishButton;
    UIButton *backButton;
    UPOMP_PasswordCellViewController *password;
    UPOMP_PhoneNumCellViewController *phoneNum;
    UPOMP_CheckPhoneCellViewController *checkPhone;
    UPOMP_KaNet *net;
}

- (void)netCancel;
- (void)prevCell;
- (void)nextCell;
- (void)checkCellArray:(int)arg1;
- (void)back:(id)arg1;
- (void)finish:(id)arg1;
- (void)netFinish:(id)arg1;
- (_Bool)checkXML:(id)arg1;
- (void)netError:(id)arg1;
- (void)netWork;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)viewDidLoad;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

