//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

@class NSDictionary, NSMutableArray, UIButton, UIImageView, UILabel, UITableViewCell, UIView, UPOMP_CardMainViewController, UPOMP_Value;

@interface UPOMP_CardListCellViewController : UIViewController
{
    UIImageView *leftBG;
    UIImageView *icon;
    UIImageView *defauletIcon;
    UIImageView *topBG;
    UILabel *text;
    UIButton *selectButton;
    UIView *line;
    UITableViewCell *bottomCell;
    UIImageView *bottomBG;
    UITableViewCell *deleteCell;
    UIImageView *deleteLeftBG;
    UIImageView *deleteArrow;
    UIImageView *deleteIcon;
    UILabel *deleteText;
    UIButton *deleteSelectButton;
    UITableViewCell *setDefauletCell;
    UIImageView *setDefauletLeftBG;
    UIImageView *setDefauletArrow;
    UIImageView *setDefauletIcon;
    UILabel *setDefauletText;
    UIButton *setDefauletSelectButton;
    UIView *setDefauletline;
    UPOMP_Value *upompValue;
    NSDictionary *cardInfo;
    UPOMP_CardMainViewController *cardMain;
    _Bool isdefault;
    _Bool isSelect;
    int cardIndex;
    NSMutableArray *cellArray;
}

- (id)getCardInfo;
- (_Bool)getIsDefault;
- (int)getCardIndex;
- (void)setSelect;
- (void)setNOSelcet;
- (void)setDefaulet:(id)arg1;
- (void)deleteCard:(id)arg1;
- (void)selectAct:(id)arg1;
- (id)cellForRowAtIndexPath:(id)arg1;
- (double)heightForRowAtIndexPath:(id)arg1;
- (long long)numberOfRowsInSection;
- (void)viewDidLoad;
- (void)setArray;
- (void)setTextColor;
- (void)setCardInfo:(id)arg1 cardMain:(id)arg2 cardIndex:(int)arg3;
- (void)dealloc;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2 upompValue:(id)arg3;

@end

