//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface UPOMP_KaMD5 : NSObject
{
}

- (id)getMD5StringWithString:(id)arg1;
- (id)getMD5DataWithString:(id)arg1;
- (id)getMD5DataWithMD5String:(id)arg1;
- (id)getMD5StringWithMD5Data:(id)arg1;

@end

