//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "UIAlertViewDelegate.h"
#import "UPOMP_KaNetDelegate.h"

@class NSString, NSTimer, UIAlertView, UIImageView, UILabel, UPOMP, UPOMP_KaNet, UPOMP_MainViewController, UPOMP_Value;

@interface UPOMP_BootViewController : UIViewController <UIAlertViewDelegate, UPOMP_KaNetDelegate>
{
    UIImageView *bg;
    UILabel *loadingText1;
    UILabel *infoText;
    UILabel *loadingText2;
    UIImageView *loadingLogo;
    UIImageView *loadingLine;
    UIImageView *loadingMove;
    UILabel *logoLabel;
    UPOMP_Value *upompValue;
    UPOMP *upomp;
    UIAlertView *alert;
    UPOMP_KaNet *net;
    _Bool needReconnect;
    int netMode;
    NSTimer *timer;
    UPOMP_MainViewController *mainView;
}

- (void)loadingOver;
- (void)netError:(id)arg1;
- (void)netFinish:(id)arg1;
- (void)deleteXML;
- (_Bool)checkXML:(id)arg1;
- (_Bool)xmlDetailedOrder:(id)arg1 root:(struct _UPOMP_TBXMLElement *)arg2;
- (_Bool)xmlDetailed:(id)arg1 root:(struct _UPOMP_TBXMLElement *)arg2;
- (_Bool)checkConfigFile:(id)arg1 root:(struct _UPOMP_TBXMLElement *)arg2;
- (_Bool)checkOK:(id)arg1;
- (void)netWorkStart:(id)arg1;
- (void)netRun;
- (_Bool)shouldAutorotateToInterfaceOrientation:(long long)arg1;
- (void)setUPOMP:(id)arg1;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)setAlertTitel:(id)arg1 info:(id)arg2;
- (void)stopLoad;
- (void)move;
- (void)startLoad;
- (void)viewDidLoad;
- (void)dealloc;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2 upomp:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

