//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UPOMP_CellViewController.h"

#import "UIPickerViewDataSource.h"
#import "UIPickerViewDelegate.h"
#import "UITextFieldDelegate.h"

@class NSMutableArray, NSString, UIButton, UILabel, UIPickerView, UITextField, UIView;

@interface UPOMP_SecureQuestionCellViewController : UPOMP_CellViewController <UITextFieldDelegate, UIPickerViewDataSource, UIPickerViewDelegate>
{
    UITextField *myField;
    UILabel *label;
    UIButton *bg;
    UIButton *listButton;
    UIPickerView *picker;
    UIView *pickerBG;
    NSMutableArray *secureQuestionArray;
    int secureQuestionSelectIndex;
    _Bool isPicker;
}

- (void)selectList:(id)arg1;
- (id)getKey;
- (void)select;
- (void)noSelect;
- (_Bool)textFieldShouldReturn:(id)arg1;
- (void)selectBG:(id)arg1;
- (void)textFieldDidEndEditing:(id)arg1;
- (void)textFieldDidBeginEditing:(id)arg1;
- (_Bool)textField:(id)arg1 shouldChangeCharactersInRange:(struct _NSRange)arg2 replacementString:(id)arg3;
- (void)restText;
- (id)getValue;
- (long long)numberOfComponentsInPickerView:(id)arg1;
- (long long)pickerView:(id)arg1 numberOfRowsInComponent:(long long)arg2;
- (void)animationDidStop:(id)arg1 finished:(_Bool)arg2;
- (void)pickerView:(id)arg1 didSelectRow:(long long)arg2 inComponent:(long long)arg3;
- (id)pickerView:(id)arg1 viewForRow:(long long)arg2 forComponent:(long long)arg3 reusingView:(id)arg4;
- (id)checkFinish;
- (void)viewDidLoad;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

