//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface UPOMP_KaPinBlock : NSObject
{
}

- (id)pin2PinBlockWithCardNOWithPin:(id)arg1 pan:(id)arg2;
- (char *)formatPan:(id)arg1;
- (char *)pin2PinBlock:(id)arg1;

@end

