//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSData, NSError;

@protocol UPOMP_KaNetDelegate <NSObject>
- (void)netFinish:(NSData *)arg1;
- (void)netError:(NSError *)arg1;
@end

