//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UPOMP_CellViewController.h"

#import "UITextFieldDelegate.h"
#import "UPOMP_KeyBoardViewDelegate.h"

@class NSString, UIButton, UILabel, UITextField, UIView, UPOMP_KaTextFieldToolBarViewController, UPOMP_KeyBoardView;

@interface UPOMP_CVN2CellViewController : UPOMP_CellViewController <UITextFieldDelegate, UPOMP_KeyBoardViewDelegate>
{
    UITextField *myField;
    UILabel *label;
    UIButton *bg;
    UIButton *infoButton;
    UPOMP_KeyBoardView *keyBoard;
    _Bool noTitel;
    UIView *keyBG;
    UPOMP_KaTextFieldToolBarViewController *myTextFieldToolBar;
}

@property _Bool noTitel; // @synthesize noTitel;
- (void)infoAct:(id)arg1;
- (id)getKey;
- (void)setKeyReturnType:(_Bool)arg1;
- (void)keyAction:(id)arg1;
- (void)okbuttonAction;
- (void)select;
- (void)noSelect;
- (void)selectBG:(id)arg1;
- (void)restText;
- (void)textFieldDidEndEditing:(id)arg1;
- (void)textFieldDidBeginEditing:(id)arg1;
- (id)checkFinish;
- (id)getValue;
- (void)addToolBar;
- (void)viewDidLoad;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

