//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UPOMP_ViewController.h"

@class UIButton, UIImageView, UILabel;

@interface UPOMP_AboutViewController : UPOMP_ViewController
{
    UILabel *textLabel;
    UIImageView *logoView;
    UIButton *backButton;
}

- (void)back:(id)arg1;
- (void)viewDidLoad;
- (void)dealloc;

@end

