//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

@class UIImageView, UIView;

@interface UPOMP_CardInfoViewController : UIViewController
{
    UIImageView *imageView;
    UIView *bgView;
}

- (void)showView;
- (void)closeAct;
- (void)oneFingerOneTaps;
- (void)viewDidLoad;
- (void)dealloc;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

@end

