//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UPOMP_CellViewController.h"

#import "UITextFieldDelegate.h"
#import "UPOMP_KaNetDelegate.h"

@class NSString, UIActivityIndicatorView, UIButton, UILabel, UITextField, UPOMP_KaNet;

@interface UPOMP_CheckImageCellViewController : UPOMP_CellViewController <UITextFieldDelegate, UPOMP_KaNetDelegate>
{
    UITextField *myField;
    UILabel *label;
    UIButton *bg;
    UIButton *imageButton;
    UIActivityIndicatorView *actview;
    _Bool isLoading;
    _Bool isLoadWhenLoad;
    _Bool noTitel;
    int netIndex;
    UPOMP_KaNet *net;
    NSString *validateCodeUrl;
}

@property _Bool noTitel; // @synthesize noTitel;
@property _Bool isLoadWhenLoad; // @synthesize isLoadWhenLoad;
@property _Bool isLoading; // @synthesize isLoading;
- (id)getKey;
- (void)select;
- (void)noSelect;
- (void)reloadImage:(id)arg1;
- (void)selectBG:(id)arg1;
- (_Bool)textFieldShouldReturn:(id)arg1;
- (void)textFieldDidEndEditing:(id)arg1;
- (void)textFieldDidBeginEditing:(id)arg1;
- (_Bool)textField:(id)arg1 shouldChangeCharactersInRange:(struct _NSRange)arg2 replacementString:(id)arg3;
- (id)getValue;
- (void)restText;
- (id)checkFinish;
- (void)netFinish:(id)arg1;
- (_Bool)checkXML:(id)arg1;
- (void)viewDidLoad;
- (_Bool)xmlDetailed:(id)arg1 root:(struct _UPOMP_TBXMLElement *)arg2;
- (void)netError:(id)arg1;
- (void)showImageButton;
- (void)showRestButton;
- (void)network;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

