//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UPOMP_ViewController.h"

#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class NSMutableArray, NSString, UIButton, UIImageView, UILabel, UITableView, UITableViewCell, UIView;

@interface UPOMP_RegistFinishViewController : UPOMP_ViewController <UITableViewDataSource, UITableViewDelegate>
{
    UITableView *myTabelView;
    NSMutableArray *cellArray;
    UITableViewCell *infoTopCell;
    UIImageView *infoTopBG;
    UITableViewCell *infoCell;
    UIImageView *infoBG;
    UIImageView *infoLeftBG;
    UILabel *infoText;
    UIView *infoLine;
    UIImageView *infoIcon;
    UITableViewCell *info2Cell;
    UIImageView *info2BG;
    UIImageView *info2LeftBG;
    UILabel *info2Text;
    UITableViewCell *infoBottomCell;
    UIImageView *infoBottomBG;
    UITableViewCell *topCell;
    UIImageView *topBG;
    UITableViewCell *userNameCell;
    UIImageView *userNameBG;
    UIImageView *userNameLeftBG;
    UILabel *userNameText;
    UILabel *userNameValue;
    UIView *userNameLine;
    UITableViewCell *welComeCell;
    UIImageView *welComeBG;
    UIImageView *welComeLeftBG;
    UILabel *welComeText;
    UILabel *welComeValue;
    UITableViewCell *bottomCell;
    UIImageView *bottomBG;
    UITableViewCell *finishCell;
    UIButton *finishButton;
    UIButton *addButton;
    UIImageView *icon;
}

- (void)addCard:(id)arg1;
- (void)finish:(id)arg1;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)viewDidLoad;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

