//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

@class UITableView, UPOMP_CellViewController, UPOMP_Value;

@interface UPOMP_ViewController : UIViewController
{
    UITableView *tabelView;
    UPOMP_Value *upompValue;
    UPOMP_CellViewController *myCell;
    int netIndex;
    _Bool isKeyBarUP;
    _Bool isScoll;
    _Bool tabelViewScoll;
}

@property _Bool isKeyBarUP; // @synthesize isKeyBarUP;
- (void)scrollViewDidEndScrollingAnimation:(id)arg1;
- (void)netCancel;
- (_Bool)checkCellRule:(id)arg1;
- (void)setSelectAlertTitel:(id)arg1 info:(id)arg2;
- (void)setAlertTitel:(id)arg1 info:(id)arg2;
- (void)getKeysAndValues:(id)arg1 key:(id)arg2 value:(id)arg3;
- (void)hiddenCell;
- (void)upData:(int)arg1;
- (void)prevCell;
- (void)nextCell;
- (void)checkCellArray:(int)arg1;
- (void)selectACT:(int)arg1;
- (void)restScoll;
- (void)noSelectMyCell;
- (void)setMyCell:(id)arg1;
- (void)keyboardWasShown:(id)arg1;
- (void)viewDown;
- (void)viewUP;
- (void)scrollToRow;
- (void)rowToSelectedCell;
- (_Bool)shouldAutorotateToInterfaceOrientation:(long long)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2 upompValue:(id)arg3;
- (void)dealloc;

@end

