//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

@class UIBarButtonItem, UIToolbar, UPOMP_MainViewController;

@interface UPOMP_KaTextFieldToolBarViewController : UIViewController
{
    UIBarButtonItem *nextItem;
    UIBarButtonItem *prevItem;
    UIBarButtonItem *hiddenItem;
    UIBarButtonItem *spaceItem;
    UIBarButtonItem *spaceItem2;
    UIToolbar *toolbar;
    UPOMP_MainViewController *mainView;
}

- (void)setnextEnabled:(_Bool)arg1;
- (void)setprevEnabled:(_Bool)arg1;
- (void)hidden:(id)arg1;
- (void)prev:(id)arg1;
- (void)next:(id)arg1;
- (void)viewDidLoad;
- (void)didReceiveMemoryWarning;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2 mainview:(id)arg3;
- (void)dealloc;

@end

