//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UPOMP_CellViewController.h"

#import "UIPickerViewDataSource.h"
#import "UIPickerViewDelegate.h"
#import "UITextFieldDelegate.h"

@class NSMutableArray, NSString, UIButton, UILabel, UIPickerView, UITextField, UIView;

@interface UPOMP_PanDateCellViewController : UPOMP_CellViewController <UITextFieldDelegate, UIPickerViewDataSource, UIPickerViewDelegate>
{
    UITextField *myField;
    UILabel *label;
    UIButton *bg;
    UIButton *infoButton;
    UIPickerView *picker;
    UILabel *yLabel;
    UILabel *mLabel;
    UIView *pickerBG;
    NSMutableArray *_monthArray;
    NSMutableArray *_dateArray;
    int year;
    int yyRow;
    int mmRow;
    _Bool noTitel;
}

@property _Bool noTitel; // @synthesize noTitel;
- (void)infoAct:(id)arg1;
- (id)getKey;
- (void)select;
- (void)noSelect;
- (void)selectBG:(id)arg1;
- (void)restText;
- (void)textFieldDidEndEditing:(id)arg1;
- (void)textFieldDidBeginEditing:(id)arg1;
- (id)checkFinish;
- (id)getValue;
- (long long)numberOfComponentsInPickerView:(id)arg1;
- (long long)pickerView:(id)arg1 numberOfRowsInComponent:(long long)arg2;
- (id)pickerView:(id)arg1 titleForRow:(long long)arg2 forComponent:(long long)arg3;
- (void)pickerView:(id)arg1 didSelectRow:(long long)arg2 inComponent:(long long)arg3;
- (void)getDate;
- (void)viewDidLoad;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

