//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface UserFriendActionData : NSObject
{
    int _typeTag;
    int _rank;
    int _level;
    NSString *_uuid;
    NSString *_userId;
    NSString *_name;
    NSString *_picUrl;
    NSString *_detail;
}

@property(nonatomic) int level; // @synthesize level=_level;
@property(nonatomic) int rank; // @synthesize rank=_rank;
@property(retain, nonatomic) NSString *detail; // @synthesize detail=_detail;
@property(retain, nonatomic) NSString *picUrl; // @synthesize picUrl=_picUrl;
@property(nonatomic) int typeTag; // @synthesize typeTag=_typeTag;
@property(retain, nonatomic) NSString *name; // @synthesize name=_name;
@property(retain, nonatomic) NSString *userId; // @synthesize userId=_userId;
@property(retain, nonatomic) NSString *uuid; // @synthesize uuid=_uuid;
- (void)dealloc;
- (id)initWithObj:(id)arg1;

@end

