//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface WaCfgData : NSObject
{
    NSString *_appName;
    NSString *_version;
    NSString *_checksum;
    NSString *_downUrl;
}

@property(retain, nonatomic) NSString *downUrl; // @synthesize downUrl=_downUrl;
@property(retain, nonatomic) NSString *checksum; // @synthesize checksum=_checksum;
@property(retain, nonatomic) NSString *version; // @synthesize version=_version;
@property(retain, nonatomic) NSString *appName; // @synthesize appName=_appName;
- (void).cxx_destruct;
- (void)unitTest;
- (void)replaceData:(id)arg1;
- (id)newDic;
- (id)initWithObj:(id)arg1;

@end

