//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface WaViewPicData : NSObject
{
    NSString *_picUrl;
    NSString *_picHint;
}

@property(retain, nonatomic) NSString *picHint; // @synthesize picHint=_picHint;
@property(retain, nonatomic) NSString *picUrl; // @synthesize picUrl=_picUrl;
- (void).cxx_destruct;
- (void)unitTest;
- (id)initWithObj:(id)arg1;

@end

