//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BaseFormVc.h"

#import "CSCaBtnPanelDelegate.h"

@class CSCaBtnPanel, CSCaInputPanel, CouponApplyFormData, NSString;

@interface XsCouponApplyVc : BaseFormVc <CSCaBtnPanelDelegate>
{
    CSCaInputPanel *_ctrlInputPanel;
    CSCaBtnPanel *_ctrlBtnPanel;
    CouponApplyFormData *_dto;
    NSString *_uuid;
    NSString *_returnPageKey;
}

@property(retain, nonatomic) NSString *returnPageKey; // @synthesize returnPageKey=_returnPageKey;
@property(retain, nonatomic) NSString *uuid; // @synthesize uuid=_uuid;
@property(retain, nonatomic) CouponApplyFormData *dto; // @synthesize dto=_dto;
@property(retain, nonatomic) CSCaBtnPanel *ctrlBtnPanel; // @synthesize ctrlBtnPanel=_ctrlBtnPanel;
@property(retain, nonatomic) CSCaInputPanel *ctrlInputPanel; // @synthesize ctrlInputPanel=_ctrlInputPanel;
- (void)onCaBtnPanelBtnClicked;
- (void)onScrollViewEndDragging;
- (void)completeQueryParamsWithTag:(long long)arg1;
- (void)onHttpRequestFail:(long long)arg1 errorMsg:(id)arg2;
- (void)completeLoadData;
- (void)onHttpRequestSuccess:(id)arg1 tag:(long long)arg2;
- (void)postData;
- (void)loadData;
- (void)topViewBackBtnClicked:(id)arg1;
- (void)onPopFromNavStack;
- (void)onHide;
- (void)onParseNavBackPageParams:(id)arg1;
- (void)onShow;
- (void)onWillShow;
- (void)onParsePageParams:(id)arg1;
- (void)onClose;
- (void)onCleanData;
- (void)onCreate;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

