//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BaseDetailVc.h"

#import "CSNumStepperDelegate.h"
#import "CSUIRadioBoxDelegate.h"
#import "UIScrollViewDelegate.h"
#import "UITextFieldDelegate.h"

@class CSCDCouponReceiverPanel, CSHtmLabel, CSNumStepper, CSUIRadioBox, CSZyInput, CouponOrderFormData, NSString, UILabel, UIScrollView, UITextField, UIView;

@interface XsCouponOrderFormVc : BaseDetailVc <UIScrollViewDelegate, UITextFieldDelegate, CSUIRadioBoxDelegate, CSNumStepperDelegate>
{
    _Bool _shouldResetByBalanceInput;
    int _requestTag;
    UIView *_ctrlBgSect1;
    UIView *_ctrlBgSect2;
    UIScrollView *_ctrlScrollView;
    UILabel *_ctrlCouponTitle;
    UILabel *_ctrlCouponFaceValue;
    UITextField *_ctrlPhoneTextField;
    CSNumStepper *_ctrlSpinnerCouponsToBuy;
    UILabel *_ctrlTotalPay;
    UILabel *_ctrlAccountBalance;
    CSZyInput *_ctrlBalaceToUseInput;
    CSUIRadioBox *_ctrlGiftCardRadioBox;
    CSZyInput *_ctrlBWCoinInput;
    UILabel *_ctrlDeductableDescription;
    UILabel *_ctrlDeductableCalculatedLabel;
    UILabel *_ctrlActualPayFormula;
    CSHtmLabel *_ctrlActualPay;
    CSCDCouponReceiverPanel *_ctrlReceiverPanel;
    NSString *_uuid;
    NSString *_restId;
    NSString *_orderId;
    CouponOrderFormData *_dto;
    NSString *_giftCardId;
    NSString *_rePageKey;
    long long _selectedGiftcardIndex;
    id _currentTfInEditing;
}

+ (id)makeLabelForTheRightWithLabelText:(id)arg1 height:(double)arg2;
+ (id)makeLabelForTheLeftWithLabelText:(id)arg1 height:(double)arg2;
@property(nonatomic) id currentTfInEditing; // @synthesize currentTfInEditing=_currentTfInEditing;
@property(nonatomic) _Bool shouldResetByBalanceInput; // @synthesize shouldResetByBalanceInput=_shouldResetByBalanceInput;
@property(nonatomic) int requestTag; // @synthesize requestTag=_requestTag;
@property(nonatomic) long long selectedGiftcardIndex; // @synthesize selectedGiftcardIndex=_selectedGiftcardIndex;
@property(retain, nonatomic) NSString *rePageKey; // @synthesize rePageKey=_rePageKey;
@property(retain, nonatomic) NSString *giftCardId; // @synthesize giftCardId=_giftCardId;
@property(retain, nonatomic) CouponOrderFormData *dto; // @synthesize dto=_dto;
@property(retain, nonatomic) NSString *orderId; // @synthesize orderId=_orderId;
@property(retain, nonatomic) NSString *restId; // @synthesize restId=_restId;
@property(retain, nonatomic) NSString *uuid; // @synthesize uuid=_uuid;
@property(retain, nonatomic) CSCDCouponReceiverPanel *ctrlReceiverPanel; // @synthesize ctrlReceiverPanel=_ctrlReceiverPanel;
@property(retain, nonatomic) CSHtmLabel *ctrlActualPay; // @synthesize ctrlActualPay=_ctrlActualPay;
@property(retain, nonatomic) UILabel *ctrlActualPayFormula; // @synthesize ctrlActualPayFormula=_ctrlActualPayFormula;
@property(retain, nonatomic) UILabel *ctrlDeductableCalculatedLabel; // @synthesize ctrlDeductableCalculatedLabel=_ctrlDeductableCalculatedLabel;
@property(retain, nonatomic) UILabel *ctrlDeductableDescription; // @synthesize ctrlDeductableDescription=_ctrlDeductableDescription;
@property(retain, nonatomic) CSZyInput *ctrlBWCoinInput; // @synthesize ctrlBWCoinInput=_ctrlBWCoinInput;
@property(retain, nonatomic) CSUIRadioBox *ctrlGiftCardRadioBox; // @synthesize ctrlGiftCardRadioBox=_ctrlGiftCardRadioBox;
@property(retain, nonatomic) CSZyInput *ctrlBalaceToUseInput; // @synthesize ctrlBalaceToUseInput=_ctrlBalaceToUseInput;
@property(retain, nonatomic) UILabel *ctrlAccountBalance; // @synthesize ctrlAccountBalance=_ctrlAccountBalance;
@property(retain, nonatomic) UILabel *ctrlTotalPay; // @synthesize ctrlTotalPay=_ctrlTotalPay;
@property(retain, nonatomic) CSNumStepper *ctrlSpinnerCouponsToBuy; // @synthesize ctrlSpinnerCouponsToBuy=_ctrlSpinnerCouponsToBuy;
@property(retain, nonatomic) UITextField *ctrlPhoneTextField; // @synthesize ctrlPhoneTextField=_ctrlPhoneTextField;
@property(retain, nonatomic) UILabel *ctrlCouponFaceValue; // @synthesize ctrlCouponFaceValue=_ctrlCouponFaceValue;
@property(retain, nonatomic) UILabel *ctrlCouponTitle; // @synthesize ctrlCouponTitle=_ctrlCouponTitle;
@property(retain, nonatomic) UIScrollView *ctrlScrollView; // @synthesize ctrlScrollView=_ctrlScrollView;
@property(retain, nonatomic) UIView *ctrlBgSect2; // @synthesize ctrlBgSect2=_ctrlBgSect2;
@property(retain, nonatomic) UIView *ctrlBgSect1; // @synthesize ctrlBgSect1=_ctrlBgSect1;
- (void)debugTransactionInfo;
- (void)changeBWCoinEnableStyle:(_Bool)arg1;
- (void)changeBalanceEnableStyle:(_Bool)arg1;
- (void)determineBWCoinInputEnable;
- (void)determineBalanceInputEnable;
- (_Bool)validateReceiverInfo;
- (id)sanitizedDoubleValue:(double)arg1;
- (_Bool)isEditingBalanceInput;
- (void)updateGiftcardEditingStatus;
- (void)reconfigGiftcardDisplayByTypeTag;
- (void)resetGiftcardSelection;
- (void)testDataInput;
- (_Bool)isStringValidForMoneyInput:(id)arg1 alreadyInput:(id)arg2;
- (_Bool)isLessThanTwoDigits:(id)arg1;
- (_Bool)hasAlreadyInputTheDot:(id)arg1;
- (void)resetBWCoin;
- (void)autoFillMaxUsableBWCoin;
- (void)autoFillBWCoin;
- (void)autoFillAccountBalanceIfNecessary;
- (void)autoFillAccountBalanceAfterUsingCoin;
- (void)autoFillAccountBalanceMaxUsable;
- (void)safeSetCoinInputText:(id)arg1;
- (void)safeSetBalanceInputText:(id)arg1;
- (id)textForBWCoinHintWithValue:(double)arg1;
- (id)textForCurrentBalanceHintWithValue:(double)arg1;
- (void)addCellSeparatorAlikeBottomLineForView:(id)arg1;
- (void)createTestDataInput;
- (void)createSubmitBtns;
- (void)createCouponUsage;
- (void)createReceiverPanel;
- (void)createActualPay;
- (void)createPayFromBWCoin;
- (void)createGiftCard;
- (void)createPayFromCurrentBalance;
- (void)createTeleInput;
- (void)createCouponNumChange;
- (void)createCouponFaceValue;
- (void)createCouponTitle;
- (void)updateUsageTextWithPhoneNumber:(id)arg1;
- (void)updateActualPayText;
- (void)updateUIWithNewData;
- (double)bwCoinCanBeUsedToPay;
- (double)calcCardPriceInUse;
- (double)calcBWCoinUsed;
- (double)calcActualPay;
- (double)calcAccountBalanceToUse;
- (double)calcAccountBalanceMaxUsable;
- (double)calculateMinimumXmsCoinToUseInCash;
- (int)calculateMinimumXmsCoinToUse;
- (double)calcTotalPay;
- (double)valueFromBalanceInput;
- (double)valueFromBWCoinInput;
- (void)alertView:(id)arg1 hideWithBtnIdx:(long long)arg2;
- (void)forwardToPaymentSelection;
- (void)buyOnlineSubmit;
- (void)submitBtnClicked:(id)arg1;
- (void)onNumStepperChange:(id)arg1 num:(long long)arg2;
- (void)radioBox:(id)arg1 didSelectAtRow:(long long)arg2;
- (void)hideKeyboard;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (void)keyboardBarDidTapHideBtn:(id)arg1;
- (void)inputTextFieldDidChange:(id)arg1;
- (_Bool)textFieldShouldReturn:(id)arg1;
- (void)textFieldDidEndEditing:(id)arg1;
- (void)textFieldDidBeginEditing:(id)arg1;
- (_Bool)textField:(id)arg1 shouldChangeCharactersInRange:(struct _NSRange)arg2 replacementString:(id)arg3;
- (void)topViewRightBtnClicked:(id)arg1;
- (void)topViewBackBtnClicked:(id)arg1;
- (void)completeQueryParams;
- (void)onHttpRequestFail:(long long)arg1 errorMsg:(id)arg2;
- (void)completeLoadData;
- (void)onHttpRequestSuccess:(id)arg1 msg:(id)arg2 tag:(long long)arg3;
- (void)loadData;
- (void)onPopFromNavStack;
- (void)onHide;
- (void)onParseNavBackPageParams:(id)arg1;
- (void)onWillShow;
- (void)onParsePageParams:(id)arg1;
- (void)onClose;
- (void)onCleanData;
- (void)onCreate;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

