//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BaseSectionListVc.h"

#import "CSXsQuickIconsPanelDelegate.h"
#import "CsXsAvatarPanelDelegate.h"

@class CSAddDebugUserPanel, CSPicAdvPanel, CSXsQuickIconsPanel, CSbubble, CsXsAvatarPanel, NSString, UIButton, UIView, UserCenterBtnData, UserCenterInfoDTO;

@interface XsMyProfileVc : BaseSectionListVc <CsXsAvatarPanelDelegate, CSXsQuickIconsPanelDelegate>
{
    _Bool _firstLoadTag;
    _Bool _selfRowTag;
    UIButton *_ctrlBubbleBtn;
    CSbubble *_ctrlBubble;
    UIButton *_ctrlSettingBtn;
    UIView *_ctrlTbHeader;
    CsXsAvatarPanel *_ctrlAvatarPanel;
    CSXsQuickIconsPanel *_ctrlQuickIconsPanel;
    CSPicAdvPanel *_ctrlAdvPanel;
    CSAddDebugUserPanel *_ctrlDebugUserPanel;
    NSString *_actionName;
    UserCenterInfoDTO *_dto;
    UserCenterBtnData *_selBtnData;
}

@property(retain, nonatomic) UserCenterBtnData *selBtnData; // @synthesize selBtnData=_selBtnData;
@property(nonatomic) _Bool selfRowTag; // @synthesize selfRowTag=_selfRowTag;
@property(retain, nonatomic) UserCenterInfoDTO *dto; // @synthesize dto=_dto;
@property(nonatomic) _Bool firstLoadTag; // @synthesize firstLoadTag=_firstLoadTag;
@property(retain, nonatomic) NSString *actionName; // @synthesize actionName=_actionName;
@property(retain, nonatomic) CSAddDebugUserPanel *ctrlDebugUserPanel; // @synthesize ctrlDebugUserPanel=_ctrlDebugUserPanel;
@property(retain, nonatomic) CSPicAdvPanel *ctrlAdvPanel; // @synthesize ctrlAdvPanel=_ctrlAdvPanel;
@property(retain, nonatomic) CSXsQuickIconsPanel *ctrlQuickIconsPanel; // @synthesize ctrlQuickIconsPanel=_ctrlQuickIconsPanel;
@property(retain, nonatomic) CsXsAvatarPanel *ctrlAvatarPanel; // @synthesize ctrlAvatarPanel=_ctrlAvatarPanel;
@property(retain, nonatomic) UIView *ctrlTbHeader; // @synthesize ctrlTbHeader=_ctrlTbHeader;
@property(retain, nonatomic) UIButton *ctrlSettingBtn; // @synthesize ctrlSettingBtn=_ctrlSettingBtn;
@property(retain, nonatomic) CSbubble *ctrlBubble; // @synthesize ctrlBubble=_ctrlBubble;
@property(retain, nonatomic) UIButton *ctrlBubbleBtn; // @synthesize ctrlBubbleBtn=_ctrlBubbleBtn;
- (void)topViewBubbleClicked:(id)arg1;
- (void)handleDebugTap;
- (void)doBtnWithData:(id)arg1;
- (void)onCSXsQuickIconsPanelBtnClicked:(int)arg1;
- (void)avatarPanelPointBtnClicked:(id)arg1;
- (void)avatarPanelEditProfileBtnClicked:(id)arg1;
- (void)avatarPanelLoginClicked:(id)arg1;
- (void)finishPickPhotoWithDataList:(id)arg1;
- (void)avatarPanelPicClicked:(id)arg1;
- (void)executeFuncByBtnText:(id)arg1;
- (_Bool)chkIfNeedLogin:(id)arg1;
- (void)loginOrExecute:(id)arg1;
- (void)layoutPage;
- (void)refreshPage;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 willDisplayCell:(id)arg2 forRowAtIndexPath:(id)arg3;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForFooterInSection:(long long)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)topViewRightBtnClicked:(id)arg1;
- (void)topViewBackBtnClicked:(id)arg1;
- (void)completeQueryParams;
- (void)onHttpRequestFail:(long long)arg1 errorMsg:(id)arg2;
- (void)onHttpRequestSuccess:(id)arg1 tag:(long long)arg2;
- (void)uploadUserPic:(id)arg1;
- (void)loadData;
- (void)onPopFromNavStack;
- (void)onHide;
- (void)onParseNavBackPageParams:(id)arg1;
- (void)onChannelTabFocus;
- (void)onShow;
- (void)onWillShow;
- (void)onParsePageParams:(id)arg1;
- (void)onClose;
- (void)onCleanData;
- (void)onCreate;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

