//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BaseFormVc.h"

#import "CSOpBtnPanelDelegate.h"
#import "CSOpEditPanelDelegate.h"
#import "CSOpReserveInfoPanelDelegate.h"
#import "CSOpRtInfoPanelDelegate.h"
#import "CSOpSelDlgPanelDelegate.h"
#import "CSOpSelPeopleDlgPanelDelegate.h"

@class CSOdHintPanel, CSOpAdvPanel, CSOpBtnPanel, CSOpEditPanel, CSOpNamePanel, CSOpReserveInfoPanel, CSOpRtInfoPanel, CSOpSelDlgPanel, CSOpSelPeopleDlgPanel, NSString, OpTransData;

@interface XsOrderPostVc : BaseFormVc <CSOpReserveInfoPanelDelegate, CSOpSelDlgPanelDelegate, CSOpEditPanelDelegate, CSOpBtnPanelDelegate, CSOpSelPeopleDlgPanelDelegate, CSOpRtInfoPanelDelegate>
{
    CSOpAdvPanel *_ctrlAdvPanel;
    CSOpNamePanel *_ctrlNamePanel;
    CSOpReserveInfoPanel *_ctrlReserveInfoPanel;
    CSOpRtInfoPanel *_ctrlRtInfoPanel;
    CSOpSelDlgPanel *_ctrlSelDlgPanel;
    CSOpSelPeopleDlgPanel *_ctrlSelPeopleDlgPanel;
    CSOpEditPanel *_ctrlEditPanel;
    CSOdHintPanel *_ctrlHintPanel;
    CSOpBtnPanel *_ctrlBtnPanel;
    OpTransData *_transData;
}

@property(retain, nonatomic) OpTransData *transData; // @synthesize transData=_transData;
@property(retain, nonatomic) CSOpBtnPanel *ctrlBtnPanel; // @synthesize ctrlBtnPanel=_ctrlBtnPanel;
@property(retain, nonatomic) CSOdHintPanel *ctrlHintPanel; // @synthesize ctrlHintPanel=_ctrlHintPanel;
@property(retain, nonatomic) CSOpEditPanel *ctrlEditPanel; // @synthesize ctrlEditPanel=_ctrlEditPanel;
@property(retain, nonatomic) CSOpSelPeopleDlgPanel *ctrlSelPeopleDlgPanel; // @synthesize ctrlSelPeopleDlgPanel=_ctrlSelPeopleDlgPanel;
@property(retain, nonatomic) CSOpSelDlgPanel *ctrlSelDlgPanel; // @synthesize ctrlSelDlgPanel=_ctrlSelDlgPanel;
@property(retain, nonatomic) CSOpRtInfoPanel *ctrlRtInfoPanel; // @synthesize ctrlRtInfoPanel=_ctrlRtInfoPanel;
@property(retain, nonatomic) CSOpReserveInfoPanel *ctrlReserveInfoPanel; // @synthesize ctrlReserveInfoPanel=_ctrlReserveInfoPanel;
@property(retain, nonatomic) CSOpNamePanel *ctrlNamePanel; // @synthesize ctrlNamePanel=_ctrlNamePanel;
@property(retain, nonatomic) CSOpAdvPanel *ctrlAdvPanel; // @synthesize ctrlAdvPanel=_ctrlAdvPanel;
- (void)reArrangePanels;
- (void)onOpBtnPanelBtnClicked;
- (void)onOpEditPanelEaterSexSwitchChanged:(int)arg1;
- (void)onOpEditPanelBookerSexSwitchChanged:(int)arg1;
- (void)onOpEditPanelForOtherSwitchChanged:(_Bool)arg1;
- (void)onOpSelDlgPanelOkWithPeopleNum:(int)arg1;
- (void)onOpSelDlgPanelOkWithReserveTime:(double)arg1 peopleNum:(int)arg2 roomType:(int)arg3;
- (void)onOpRtInfoPanelNeedOpenDlgWithFromRect:(struct CGRect)arg1;
- (void)onOpReserveInfoPanelNeedOpenDlgWithFromRect:(struct CGRect)arg1;
- (void)onScrollViewEndDragging;
- (void)completeQueryParamsWithTag:(long long)arg1;
- (void)onHttpRequestFail:(long long)arg1 errorMsg:(id)arg2;
- (void)completeLoadData;
- (void)onHttpRequestSuccess:(id)arg1 tag:(long long)arg2;
- (void)postData;
- (void)loadData;
- (void)topViewRightBtnClicked:(id)arg1;
- (void)topViewBackBtnClicked:(id)arg1;
- (void)onPopFromNavStack;
- (void)onHide;
- (void)onParseNavBackPageParams:(id)arg1;
- (void)onShow;
- (void)onWillShow;
- (void)onParsePageParams:(id)arg1;
- (void)onClose;
- (void)onCleanData;
- (void)onCreate;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

