//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BaseSectionListVc.h"

#import "CSTkAddrAddPanelDelegate.h"
#import "CSTkRecvAddrListCellDelegate.h"

@class CSTkAddrAddPanel, NSString, UserTkRaListPack2DTO;

@interface XsTkRecvAddrListVc : BaseSectionListVc <CSTkRecvAddrListCellDelegate, CSTkAddrAddPanelDelegate>
{
    _Bool _haveDelCurrentSelRaTag;
    CSTkAddrAddPanel *_ctrlAddAddrPanel;
    UserTkRaListPack2DTO *_dto;
    NSString *_uuid;
    NSString *_uuidForPost;
    NSString *_address;
    NSString *_tel;
    NSString *_name;
}

@property(nonatomic) _Bool haveDelCurrentSelRaTag; // @synthesize haveDelCurrentSelRaTag=_haveDelCurrentSelRaTag;
@property(retain, nonatomic) NSString *name; // @synthesize name=_name;
@property(retain, nonatomic) NSString *tel; // @synthesize tel=_tel;
@property(retain, nonatomic) NSString *address; // @synthesize address=_address;
@property(retain, nonatomic) NSString *uuidForPost; // @synthesize uuidForPost=_uuidForPost;
@property(retain, nonatomic) NSString *uuid; // @synthesize uuid=_uuid;
@property(retain, nonatomic) UserTkRaListPack2DTO *dto; // @synthesize dto=_dto;
@property(retain, nonatomic) CSTkAddrAddPanel *ctrlAddAddrPanel; // @synthesize ctrlAddAddrPanel=_ctrlAddAddrPanel;
- (void)alertView:(id)arg1 hideWithBtnIdx:(long long)arg2;
- (void)onTkAddrAddPanelEditWithUuid:(id)arg1 address:(id)arg2 tel:(id)arg3 name:(id)arg4;
- (void)onTkAddrAddPanelAddWithAddress:(id)arg1 tel:(id)arg2 name:(id)arg3;
- (void)onTkRecvAddrListCellDelAddr:(id)arg1;
- (void)onTkRecvAddrListCellEditAddr:(id)arg1;
- (void)onTableViewEndDragging;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (void)makeCell:(id)arg1 indexPath:(id)arg2;
- (void)createCell:(id)arg1;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForFooterInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)completeQueryParamsWithTag:(long long)arg1;
- (void)onHttpRequestFail:(long long)arg1 errorMsg:(id)arg2 tag:(long long)arg3;
- (void)onHttpRequestSuccess:(id)arg1 tag:(long long)arg2;
- (void)postDataForDel;
- (void)postDataForEdit;
- (void)postDataForAdd;
- (void)loadData;
- (void)topViewRightBtnClicked:(id)arg1;
- (void)topViewBackBtnClicked:(id)arg1;
- (void)onPopFromNavStack;
- (void)onHide;
- (void)onParseNavBackPageParams:(id)arg1;
- (void)onShow;
- (void)onWillShow;
- (void)onParsePageParams:(id)arg1;
- (void)onClose;
- (void)onCleanData;
- (void)onCreate;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

