//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BaseFormVc.h"

#import "CSTkpBtnPanelDelegate.h"
#import "CSTkpFormPanelDelegate.h"
#import "CSTkpMenuPanelDelegate.h"

@class CSTkpBtnPanel, CSTkpFormPanel, CSTkpMenuPanel, CSTodNotePanel, NSString, TakeoutPostOrderFormData;

@interface XsTkPostTakeoutOrderVc : BaseFormVc <CSTkpFormPanelDelegate, CSTkpMenuPanelDelegate, CSTkpBtnPanelDelegate>
{
    int _selPayTypeTag;
    CSTodNotePanel *_ctrlNotePanel;
    CSTkpFormPanel *_ctrlFormPanel;
    CSTkpMenuPanel *_ctrlMenuPanel;
    CSTkpBtnPanel *_ctrlBtnPanel;
    TakeoutPostOrderFormData *_dto;
    NSString *_takeoutId;
    NSString *_rePageKey;
}

@property(nonatomic) int selPayTypeTag; // @synthesize selPayTypeTag=_selPayTypeTag;
@property(retain, nonatomic) NSString *rePageKey; // @synthesize rePageKey=_rePageKey;
@property(retain, nonatomic) NSString *takeoutId; // @synthesize takeoutId=_takeoutId;
@property(retain, nonatomic) TakeoutPostOrderFormData *dto; // @synthesize dto=_dto;
@property(retain, nonatomic) CSTkpBtnPanel *ctrlBtnPanel; // @synthesize ctrlBtnPanel=_ctrlBtnPanel;
@property(retain, nonatomic) CSTkpMenuPanel *ctrlMenuPanel; // @synthesize ctrlMenuPanel=_ctrlMenuPanel;
@property(retain, nonatomic) CSTkpFormPanel *ctrlFormPanel; // @synthesize ctrlFormPanel=_ctrlFormPanel;
@property(retain, nonatomic) CSTodNotePanel *ctrlNotePanel; // @synthesize ctrlNotePanel=_ctrlNotePanel;
- (void)onScrollViewEndDragging;
- (void)onTkpBtnPanelOrderBtnClicked;
- (void)onTkpMenuPanelChanged;
- (void)onTkpFormPanelChangePayType:(int)arg1;
- (void)completeQueryParamsWithTag:(long long)arg1;
- (void)onHttpRequestFail:(long long)arg1 errorMsg:(id)arg2;
- (void)completeLoadData;
- (void)onHttpRequestSuccess:(id)arg1 tag:(long long)arg2;
- (void)postDataForPostOrder;
- (void)postDataForOrderFormInfo;
- (void)loadData;
- (void)topViewBackBtnClicked:(id)arg1;
- (void)onPopFromNavStack;
- (void)onHide;
- (void)onParseNavBackPageParams:(id)arg1;
- (void)onShow;
- (void)onWillShow;
- (void)onParsePageParams:(id)arg1;
- (void)onClose;
- (void)onCleanData;
- (void)onCreate;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

