//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class TakeoutMenuSelPackDTO;

@interface XsTkUtil : NSObject
{
    TakeoutMenuSelPackDTO *_menuSelPack;
}

+ (id)i;
@property(retain, nonatomic) TakeoutMenuSelPackDTO *menuSelPack; // @synthesize menuSelPack=_menuSelPack;
- (id)dataWithIdentiferInForm:(id)arg1;
- (id)dataWithUuid:(id)arg1;
- (void)updateMenuSelNumInForm:(long long)arg1 dataIdentifer:(id)arg2;
- (void)updateSelGiftInForm:(id)arg1 dataIdentifer:(id)arg2;
- (id)menuSelPackJsonStr;
- (double)totalPrice;
- (long long)totalNum;
- (long long)numInCartWithMenuData:(id)arg1;
- (void)addPropertyMenuToCart:(id)arg1 num:(long long)arg2;
- (void)addMenuToCart:(id)arg1;
- (void)replaceCart:(id)arg1;
- (void)cleanCart;
- (void)dealloc;
- (id)init;

@end

