//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BaseSingleListVc.h"

#import "CSZyDishListCellViewDelegate.h"
#import "CSZyDishOrderCommBottomViewDelegate.h"

@class CSDishPeoplePanel, CSZyDishOrderCommBottomView, NSMutableArray, NSMutableDictionary, NSString;

@interface ZyDishCartConfirmVc : BaseSingleListVc <CSZyDishListCellViewDelegate, CSZyDishOrderCommBottomViewDelegate>
{
    int _fromTag;
    int _postTag;
    CSZyDishOrderCommBottomView *_ctrlSummaryPanel;
    CSDishPeoplePanel *_ctrlPeoplePanel;
    NSString *_uuid;
    NSString *_menuId;
    NSMutableArray *_flippedCellRows;
    NSMutableDictionary *_flippedIndexPaths;
}

@property(retain, nonatomic) NSMutableDictionary *flippedIndexPaths; // @synthesize flippedIndexPaths=_flippedIndexPaths;
@property(retain, nonatomic) NSMutableArray *flippedCellRows; // @synthesize flippedCellRows=_flippedCellRows;
@property(retain, nonatomic) NSString *menuId; // @synthesize menuId=_menuId;
@property(retain, nonatomic) NSString *uuid; // @synthesize uuid=_uuid;
@property(nonatomic) int postTag; // @synthesize postTag=_postTag;
@property(nonatomic) int fromTag; // @synthesize fromTag=_fromTag;
@property(retain, nonatomic) CSDishPeoplePanel *ctrlPeoplePanel; // @synthesize ctrlPeoplePanel=_ctrlPeoplePanel;
@property(retain, nonatomic) CSZyDishOrderCommBottomView *ctrlSummaryPanel; // @synthesize ctrlSummaryPanel=_ctrlSummaryPanel;
- (void)refreshPanel;
- (void)navBackWithPostTagAndMenuId;
- (void)alertHintViewOnClickTryAgainBtn;
- (void)alertView:(id)arg1 hideWithBtnIdx:(long long)arg2;
- (void)onCSZyDishOrderCommBottomViewBtnClicked:(id)arg1;
- (void)onDishListCellView:(id)arg1 dishData:(id)arg2 valueChangedTo:(long long)arg3 fromValue:(long long)arg4;
- (void)makeCell:(id)arg1 indexPath:(id)arg2;
- (void)createCell:(id)arg1;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (id)tableView:(id)arg1 titleForHeaderInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)completeQueryParams;
- (void)onHttpRequestFail:(long long)arg1 errorMsg:(id)arg2;
- (void)completeLoadData;
- (void)onHttpRequestSuccess:(id)arg1 tag:(long long)arg2;
- (void)postData;
- (void)topViewRightBtnClicked:(id)arg1;
- (void)topViewBackBtnClicked:(id)arg1;
- (void)onPopFromNavStack;
- (void)onHide;
- (void)onParseNavBackPageParams:(id)arg1;
- (void)onShow;
- (void)onWillShow;
- (void)onParsePageParams:(id)arg1;
- (void)onClose;
- (void)onCleanData;
- (void)onCreate;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

