//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray;

@interface ZyDishCart : NSObject
{
    NSMutableArray *_list;
}

+ (id)instance;
@property(retain, nonatomic) NSMutableArray *list; // @synthesize list=_list;
- (void)readDishCartFromCache;
- (void)saveDishCartToCache;
- (void)cleanDishCartCache;
- (_Bool)hasUnsavedDishes;
- (_Bool)chkCategoryHasDishes:(id)arg1;
- (id)fmtToListStr;
- (void)preloadCart:(id)arg1;
- (void)resetToEmpty;
- (void)reset;
- (void)cleanOutCategoriesWithEmptyList;
- (void)addDishData:(id)arg1 toCategory:(id)arg2 withSelectNum:(long long)arg3;
- (void)updateWithDishCategory:(id)arg1 dishData:(id)arg2 newSelectNum:(long long)arg3;
- (void)updateWithOnlyDishData:(id)arg1 newSelectNum:(long long)arg2;
- (void)addDishData:(id)arg1 withCountNum:(long long)arg2;
- (long long)findOrderNumById:(id)arg1;
- (_Bool)chkExistById:(id)arg1;
- (_Bool)chkIsHaveShiJia;
- (double)calTotalMoney;
- (void)dealloc;
- (id)init;

@end

