//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BaseDetailVc.h"

#import "CSZyDishListDelegate.h"
#import "CSZyDishOrderCategoryDelegate.h"
#import "CSZyDishOrderCommBottomViewDelegate.h"

@class CSZyDishList, CSZyDishOrderCategory, CSZyDishOrderCommBottomView, DishListDTO, DishListPackDTO, NSString;

@interface ZyDishOrderSelectionVc : BaseDetailVc <CSZyDishOrderCategoryDelegate, CSZyDishOrderCommBottomViewDelegate, CSZyDishListDelegate>
{
    int _fromTag;
    int _postTag;
    CSZyDishOrderCategory *_ctrlDishCategory;
    CSZyDishList *_ctrlDishList;
    CSZyDishOrderCommBottomView *_ctrlSummaryView;
    DishListPackDTO *_dto;
    NSString *_uuid;
    NSString *_menuId;
    DishListDTO *_selectedDishCategory;
    NSString *_restId;
    NSString *_orderId;
}

@property(retain, nonatomic) NSString *orderId; // @synthesize orderId=_orderId;
@property(retain, nonatomic) NSString *restId; // @synthesize restId=_restId;
@property(nonatomic) int postTag; // @synthesize postTag=_postTag;
@property(nonatomic) DishListDTO *selectedDishCategory; // @synthesize selectedDishCategory=_selectedDishCategory;
@property(retain, nonatomic) NSString *menuId; // @synthesize menuId=_menuId;
@property(nonatomic) int fromTag; // @synthesize fromTag=_fromTag;
@property(retain, nonatomic) NSString *uuid; // @synthesize uuid=_uuid;
@property(retain, nonatomic) DishListPackDTO *dto; // @synthesize dto=_dto;
@property(retain, nonatomic) CSZyDishOrderCommBottomView *ctrlSummaryView; // @synthesize ctrlSummaryView=_ctrlSummaryView;
@property(retain, nonatomic) CSZyDishList *ctrlDishList; // @synthesize ctrlDishList=_ctrlDishList;
@property(retain, nonatomic) CSZyDishOrderCategory *ctrlDishCategory; // @synthesize ctrlDishCategory=_ctrlDishCategory;
- (void)animateMenuDataForCart:(id)arg1 isAddingMenuData:(_Bool)arg2;
- (void)alertHintViewOnClickTryAgainBtn;
- (void)alertView:(id)arg1 hideWithBtnIdx:(long long)arg2;
- (void)onCSZyDishOrderCommBottomViewBtnClicked:(id)arg1;
- (void)onCSZyDishListCellView:(id)arg1 dishData:(id)arg2 valueChangedTo:(long long)arg3 fromValue:(long long)arg4;
- (void)onDishOrderCategorySelectAtRow:(long long)arg1;
- (void)completeQueryParams;
- (void)onHttpRequestFail:(long long)arg1 errorMsg:(id)arg2;
- (void)completeLoadData;
- (void)onHttpRequestSuccess:(id)arg1 tag:(long long)arg2;
- (void)loadData;
- (void)topViewRightBtnClicked:(id)arg1;
- (void)topViewBackBtnClicked:(id)arg1;
- (void)onPopFromNavStack;
- (void)onHide;
- (void)onParseNavBackPageParams:(id)arg1;
- (void)onShow;
- (void)onWillShow;
- (void)onParsePageParams:(id)arg1;
- (void)onClose;
- (void)onCleanData;
- (void)onCreate;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

