//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray, NSString, PageStatsPackData;

@interface ZyPageStatUtil : NSObject
{
    _Bool _needSaveTag;
    PageStatsPackData *_packData;
    NSMutableArray *_chatHisPageList;
    NSString *_chatCurrentPage;
}

+ (id)is;
@property(retain, nonatomic) NSString *chatCurrentPage; // @synthesize chatCurrentPage=_chatCurrentPage;
@property(retain, nonatomic) NSMutableArray *chatHisPageList; // @synthesize chatHisPageList=_chatHisPageList;
@property(nonatomic) _Bool needSaveTag; // @synthesize needSaveTag=_needSaveTag;
@property(retain, nonatomic) PageStatsPackData *packData; // @synthesize packData=_packData;
- (void)gaPageTrack:(id)arg1;
- (void)gaEventTrack:(id)arg1 action:(id)arg2 label:(id)arg3 value:(id)arg4;
- (void)gaTrackEvent:(id)arg1 eventName:(id)arg2 memo:(id)arg3;
- (void)gaTrackPv:(id)arg1 memo:(id)arg2 inTag:(_Bool)arg3;
- (void)notifyToUpload;
- (id)lastPageStatsData;
- (void)addToChatHisPageListWithName:(id)arg1 restId:(id)arg2 couponId:(id)arg3 orderId:(id)arg4 inTag:(_Bool)arg5;
- (void)resetChatParams;
- (id)browsePagesForChat;
- (void)save;
- (void)finishEvent;
- (void)addEvent:(id)arg1 memo:(id)arg2;
- (void)addEvent:(id)arg1;
- (void)addPage:(id)arg1 restId:(id)arg2 couponId:(id)arg3 orderId:(id)arg4 inTag:(_Bool)arg5;
- (void)addBkPage:(id)arg1 orderId:(id)arg2;
- (void)addBkPage:(id)arg1 couponId:(id)arg2;
- (void)addBkPage:(id)arg1 restId:(id)arg2;
- (void)addBkPage:(id)arg1;
- (void)addPage:(id)arg1 orderId:(id)arg2;
- (void)addPage:(id)arg1 couponId:(id)arg2;
- (void)addPage:(id)arg1 restId:(id)arg2;
- (void)addPage:(id)arg1;
- (void)dealloc;
- (id)init;

@end

