//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BaseDetailVc.h"

@class CSUIButton, NSString;

@interface ZyUserAddressBookUploadVc : BaseDetailVc
{
    CSUIButton *_ctrlSubmit;
    NSString *_fromPage;
}

@property(retain, nonatomic) NSString *fromPage; // @synthesize fromPage=_fromPage;
@property(retain, nonatomic) CSUIButton *ctrlSubmit; // @synthesize ctrlSubmit=_ctrlSubmit;
- (void)navBackWithSucc:(_Bool)arg1;
- (void)btnClick;
- (void)alertView:(id)arg1 hideWithBtnIdx:(long long)arg2;
- (void)completeQueryParams;
- (void)onHttpRequestFail:(long long)arg1 errorMsg:(id)arg2;
- (void)onHttpRequestSuccess:(id)arg1 tag:(long long)arg2;
- (void)loadData;
- (void)topViewBackBtnClicked:(id)arg1;
- (void)onWillShow;
- (void)onParsePageParams:(id)arg1;
- (void)onClose;
- (void)onCleanData;
- (void)onCreate;

@end

