//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BaseDetailVc.h"

#import "CSUIComboBoxDelegate.h"
#import "UITextFieldDelegate.h"

@class CSUIComboBox, CSZyInput, NSString;

@interface ZyUserProfileEditingVc : BaseDetailVc <UITextFieldDelegate, CSUIComboBoxDelegate>
{
    int _typeTag;
    int _selSexTag;
    CSZyInput *_ctrlTextField;
    CSUIComboBox *_ctrlSexComboBox;
}

@property(nonatomic) int selSexTag; // @synthesize selSexTag=_selSexTag;
@property(nonatomic) int typeTag; // @synthesize typeTag=_typeTag;
@property(retain, nonatomic) CSUIComboBox *ctrlSexComboBox; // @synthesize ctrlSexComboBox=_ctrlSexComboBox;
@property(retain, nonatomic) CSZyInput *ctrlTextField; // @synthesize ctrlTextField=_ctrlTextField;
- (id)cleanText;
- (void)hideKeyboard;
- (void)showKeyboard;
- (void)alertView:(id)arg1 hideWithBtnIdx:(long long)arg2;
- (void)comboBox:(id)arg1 didSelected:(long long)arg2 selectId:(id)arg3 selectName:(id)arg4;
- (_Bool)textFieldShouldReturn:(id)arg1;
- (void)completeQueryParams;
- (void)onHttpRequestFail:(long long)arg1 errorMsg:(id)arg2;
- (void)onHttpRequestSuccess:(id)arg1 tag:(long long)arg2;
- (void)postUserInfo;
- (void)topViewRightBtnClicked:(id)arg1;
- (void)onPopFromNavStack;
- (void)onHide;
- (void)onParseNavBackPageParams:(id)arg1;
- (void)onShow;
- (void)onWillShow;
- (void)onParsePageParams:(id)arg1;
- (void)onClose;
- (void)onCleanData;
- (void)onCreate;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

